### ISSUE TITLE
truffle.js gets overwritten during solidity-coverage run

### ISSUE THREAD

**Issue by Eenae** [sc-forks/solidity-coverage#104]
After performing solidity-coverage run [on this project](https://github.com/mixbytes/storiqa_ico/tree/036a57a6c71599b643145f4ec4e77d86b360dec1) I see that truffle.js was modified:
```diff
diff --git a/truffle.js b/truffle.js
index b38292c..0448d64 100644
--- a/truffle.js
+++ b/truffle.js
@@ -1,12 +1,12 @@
-require('babel-register');
-require('babel-polyfill');
 
-module.exports = {
-  networks: {
-    development: {
-      host: "localhost",
-      port: 8545,
-      network_id: "*" // Match any network id
-    }
-  }
-};
+      module.exports = {
+        networks: {
+          development: {
+            host: "localhost",
+            network_id: "*",
+            port: 8555,
+            gas: 17592186044415,
+            gasPrice: 1
+          }
+        }
+      };
```
And maybe even the bigger problem arises: statements like `require('babel-register');` are ignored and I believe thats the reason why most of the tests failed.

**Comment by Eenae** [comment]
I'm using solidity-coverage 0.2.2, truffle 3.4.9.

**Comment by cgewecke** [comment]
Hi @Eenae. If you want to preserve your own truffle.js you can declare a coverage network there, alongside your other networks. See the README for instructions. 

Closing this because it's addressed by our documentation but please reopen if you continue to have issues with it,

Thanks!
