### ISSUE TITLE
Gnosis / Pythereum

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#11]
+ Blocked by events.
+ Is their folder structure / the way tests are implemented somehow 'standard' for python based projects? 
+ Adding a custom version of the vm to the build.

**Comment by maurelian** [comment]
I would like to run a coverage report on this branch of gnosis: https://github.com/gnosis/gnosis-contracts/tree/security_audit, so I might as well help make it repeatable in the process. 

At a high level, what needs to be done to make this happen?

**Comment by cgewecke** [comment]
@maurelian Awesome! That's great. 

To step through the points above: The Gnosis contracts are heavily evented and the coverage tool should be able to handle that without erroring their tests.  I'm working on that this week. And they use the pyethereum vm - I modified [a version of that](https://github.com/sc-forks/pyethereum) last month to behave the way the tool expects it to so I think that part of the problem is also mostly solved. (Looks like it might need an upstream sync).

But the main thing that needs to be done is to figure out how to add a tool like this to their project. They're inside vagrant machine and they have apt AND npm installation steps in their build script. We need to be able to install a separate, second Pyethereum VM and be able to run their tests against it after instrumenting their code. I'm not really a Vagrant / Linux / Python person, so I'm not sure what's normal in that world. . . like I literally don't understand how their tests launch and stuff. Or how to install anything without using NPM. I'm completely JS basket-cased. 

Then: another question: is the way Gnosis is organized idiosyncratic? Or is there a pattern people who use the python tools in the eco-system typically follow? If the answer to the first question is yes - that doesn't really matter to me - Gnosis is such a significant project that it's worth analyzing their code regardless. But if the latter is the case - it would be great to figure out how to accommodate those devs. 

If you have any interest in working on either of those issues I'd be thrilled. Preemptively adding you to the org. (Obligates you to nothing :)  

Also - if you have any ideas or things you'd like to work on - I'm all ears.

**Comment by maurelian** [comment]
Sounds good. I'm a bit more comfortable with Python and vagrant, but haven't used them in a while, and already getting errors with `pip install`. Ideally there would be a python tool for this pupose, but there may be some best practices for using node modules in mostly python projects. 

I'll report back!

**Comment by cgewecke** [comment]
@maurelian Thanks! It would be great if the tool could *just* use npm but a second, modified VM could also be listed in the `requirements.txt` file. It's an extra step but whatever. 

Also: Was able to install the security_audit branch today and run their tests, but most of them seem to be failing. (13 fails / 4 successes). Just using their packages & instructions - haven't installed anything extra. In late April the tests all passed. . .

Have you gotten it to work? 

There is a fork of the project at [sc-forks/gnosis-contracts-coverage#security_audit](https://github.com/sc-forks/gnosis-contracts-coverage/tree/security_audit) with some small tweaks to the build script to get it to run on OSX Capitan, and some instructions (for me) in the readme about installing it and dealing with Vagrant. 

Is it possible their project is in a state of flux and the test suite is not really working at the moment?  Sort of wish they were using TravisCI so there was a baseline to check against . . .

**Comment by maurelian** [comment]
I'm getting a lot of failures too. Mostly `transaction failed`. 

I don't think Vagrant is actually a requirement, probably just something the included as a catch all for people with environment specific issues. 

I'll ask about the test suite.

**Comment by cgewecke** [comment]
@maurelian [This PR over there](https://github.com/gnosis/gnosis-contracts/pull/8) looks really promising and involves a complete refactor of the project into 'truffle' form. But with pytest.

**Comment by maurelian** [comment]
Update on this, I think they are still working on fixing some tests. I'll try to let you know when I hear from them.

**Comment by cgewecke** [comment]
@maurelian Ran this today:

+ Pretty much just works? . . . sort of shocked. Only unusual thing was that the MarketMaker tests take an incredibly long time to run under coverage and had to set the the mocha timeout option in `truffle.js` higher than the default. (Which is 5 minutes!!) Also requires Node7.

+ They might still be working on this but coverage is really good. Possibly the best I've seen for any project. . . .

[Link to sample report](https://sc-forks.github.io/gnosis-contracts-coverage/index.html)  

I'm closing this because nothing special needs to be done for them. Please feel free to reopen if you can't reproduce or see something weird in there.

**Comment by maurelian** [comment]
Thank you @cgewecke!
