### ISSUE TITLE
Weird behavior when coverageEnv dir already exists

### ISSUE THREAD

**Issue by nberger** [sc-forks/solidity-coverage#113]
When running the coverage task and the `coverageEnv` directory already exists, a few weird things happen:

1. A potentially endless recursive directory structure of coverageEnv directories is created, each with all the content of the current directory copied into it. To make it clear, it creates directories like `coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv...`, with all the content from the current dir (without node_modules) inside of each of them, until it fails with `cp: copyFileSync: could not write to dest file (code=ENAMETOOLONG)`

2. The coverage task keeps running "normally" after that error, and at the end it deletes all the recursive `coverageEnv` directory structure.

But I'm not really sure how "normally" it runs, probably some aspect of the coverage report would be missing at the end, perhaps it fails to create the `.sol.html` file for each contract, I didn't analyze what's missing in the end report.

**How did I find this error**? By interrupting one coverage run at the beginning, it seems it fails to call `cleanUp`. So that's another issue, probably [this line](https://github.com/sc-forks/solidity-coverage/blob/master/bin/exec.js#L20) that sets up the termination handler should be moved a few lines above, right after the app instance is created.

**How to reproduce**? Just create the coverageEnv with `mkdir coverageEnv` and then run `yarn coverage` in an instrumented project (I verified the behavior with both [WindingTree/LifToken](http://github.com/WindingTree/LifToken) and also with [OpenZeppelin/zeppelin-solidity](https://github.com/OpenZeppelin/zeppelin-solidity))

Full error when running into this on [Winding Tree LifToken](http://github.com/WindingTree/LifToken) (the output is shortened with `[...]` because it was too long):

```
Starting testrpc-sc to generate coverage
Generating coverage environment
mkdir: path already exists: ./coverageEnv
cp: copyFileSync: could not write to dest file (code=ENAMETOOLONG):coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/coverageEnv/[...]/coverage/lcov-report/contracts/LifMarketValidationMechanism.sol.html
cp: cannot create directory './coverageEnv': No such file or directory
Instrumenting  ./coverageEnv/contracts/LifCrowdsale.sol
Instrumenting  ./coverageEnv/contracts/LifMarketValidationMechanism.sol
[...]
```

It'd also be interesting to understand why the deeply nested structure is created, I inspected the code a little but couldn't find an answer to that question.

**Comment by cgewecke** [comment]
Ah yes @nberger, thanks for such a good bug report. The sigint handler should definitely be where you suggested. 

Fixing this will also hopefully solve lingering zombie testrpc-sc issues @utkarash2991 found recently in #57.

*Also* not sure about how the infinite `coverageEnv` is produced - it's maybe something to do with how shell's recursive copy works?

**Comment by cgewecke** [comment]
This should be fixed in `0.2.4`. 

Still a little weird when you're interrupting indirectly, i.e if you've launched the tool in a shell script. It keeps running for a while. But clean up seems to work there too. 

Thanks again and please re-open if you see this again.

**Comment by nberger** [comment]
@cgewecke thanks for the quick response!

Here's one possible explanation for the deeply nested structure, based on how shelljs `cp -r` seems to work: the process iterates each file in the working dir, sorted by name. When it gets to `coverageEnv` (that is in the source files list) some files were already copied into it and given we asked it to do a recursive copy, it obtains the files from `coverageEnv` (which is the files in working dir with names that come before `coverageEnv`) and copies them inside of `coverageEnv` but with its full path which starts with `coverageEnv`, so for example it creates `coverageEnv/coverageEnv/contracts`... and so on, so on, until the name is so long that luckily the whole thing blows up, before the disk gets full ;)

Does it make sense? I think so.

An easy solution seems to be to skip `coverageEnv` from the source files list, the same as with `node_modules`

**Comment by cgewecke** [comment]
Ah yes - that makes a lot sense! Thanks! 

Thought about checking for existence of coverageEnv or skipping and probably that would be the safest thing. But also think your solution re: positioning the sigint handler correctly should really work. :crossed_fingers: 

Might revisit this though, there's another issue pending around how we generate the env . . .

**Comment by nberger** [comment]
Sounds good! I agree, the sigint handler fix should make this issue very rare. Thanks!!
