### ISSUE TITLE
Byzantium testrpc-sc

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#115]
It looks like `ethereumjs-vm` is still working out a couple things. I assume testrpc will fork soon though....

Kind of wonder how they will release - as a beta? A full version? We might need to copy them.

**Comment by cgewecke** [comment]
Looks like it's about to [leave the harbour](https://github.com/ethereumjs/testrpc/issues/149#issuecomment-339458148) here.

>The current version of TestRPC targets ganache-core 1.1.3, but I'll do my best to get a release out which uses 1.1.4 later today. It'll very likely be version 5.0.0.

**Comment by benjamincburns** [comment]
Working on it now, anyway... not sure that it'll make it out today the way things are going, however.

**Comment by benjamincburns** [comment]
I've been having trouble getting it to play nice with the tests from `OpenZeppelin/zeppelin-solidity` so in the interim I published it as a beta release. To install, do `npm install -g ethereumjs-testrpc@beta`. I'll spend some more time tomorrow trying to sort out what's wrong.

**Comment by cgewecke** [comment]
Ah ok! Thanks so much @benjamincburns. Very exciting.

**Comment by cgewecke** [comment]
Scheduled for weekend of Nov4/5 2017. We also need to rationalize how testrpc-sc is structured and published since upstream is now aggressively maintaining and improving. We'll have to track a faster production schedule and possibly tag our own releases.

**Comment by benjamincburns** [comment]
Just a heads up, but you'll likely want to target testrpc@6.0.0 (still tagged as `beta`) and ganache-core 2.0.0 now. From what I can tell, this version has everything needed for complete support for byzantium.

Aside, perhaps we should get in touch out-of-band - I'm interested to know what was needed to make testrpc-sc work. Ideally we'd be able to support the needs of the solidity coverage project without you having to maintain a separate fork. I can't promise that I can make make this happen, but I'd like to better understand what it'd take.

**Comment by cgewecke** [comment]
Ok great! Thanks. I'm sending you a dm on gitter.
