### ISSUE TITLE
Reading trace file `allFiredEvents` fails silently on large files.

### ISSUE THREAD

**Issue by rudolfix** [sc-forks/solidity-coverage#119]
`readFileSync` will fail on files larger than ~260MB as described here.
https://github.com/nodejs/node/issues/9489
This will make solidity to fail with cryptic message when calling `toString` on the `readFileSync` results.
We encountered this problem due to (relatively) large number of tests we run on our code base.

Solution: use stream to read line by line as in this commit https://github.com/Neufund/solidity-coverage/commit/9a041d720722bee6ea3f0eecb02c45ac2c16f923
If maintainers are interested I can provide PR.

**Comment by cgewecke** [comment]
Whoa! That's a lot of events! Thanks for reporting.

Yes we'll happily take as a PR! Thank you @rudolfix.

**Comment by cgewecke** [comment]
@rudolfix Absolutely no pressure here but is your preference to open a PR or is it more convenient for you if we just steal this? With attribution of course. 

If PR that's great, and take as long as you like :)

**Comment by rudolfix** [comment]
Do you have gitter channel? All tests are passing except `app` test which throws on timeout
```
1) app "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
I run it with `npm run test`. I'd like all tests passing before I push PR

**Comment by cgewecke** [comment]
@rudolfix I DM'd you there.
