### ISSUE TITLE
Prompt to run truffle init

### ISSUE THREAD

**Issue by HaleTom** [sc-forks/solidity-coverage#127]
If I run `solidity-coverage` in a directory where truffle hasn't been initialised, I get:

```
Generating coverage environment
ls: no such file or directory: ./coverageEnv/contracts/**/*.sol
Launched testrpc on port 8555
Running: truffle test
(this can take a few seconds)...
/usr/lib/node_modules/truffle/build/cli.bundled.js:213349
      files = files.filter(function(file) {
                   ^

TypeError: Cannot read property 'filter' of undefined
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:213349:20
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:214669:25
    at FSReqWrap.oncomplete (fs.js:153:21)
Cleaning up...

        There was an error generating coverage. Possible reasons include:
        1. Another application is using port 8555
        2. Truffle crashed because your tests errored

      Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
```

I'm a noob, but it took me a while to work out what was going on.

Perhaps check if files is undefined and say something like:

"Can't find truffle files. Have you run "truffle init"?

**Comment by cgewecke** [comment]
@HaleTom Agree this could really be improved. There's no sanity check in the code and the message isn't helpful. 

(In theory) `solidity-coverage` can be used with non-truffle projects. Would a message like 

> `solidity-coverage` couldn't find a `contracts` folder with solidity files in it. Are you running it from the right directory? 

have helped?  

Also think this:
> 2. Truffle crashed because your tests errored  // <-- misspelled

Should be changed to this:
> 2. Your test runner (Truffle?) crashed because the tests errorred.

**Comment by HaleTom** [comment]
All suggestions LGTM, except [this](https://english.stackexchange.com/a/3068/147662) says `errored` is actually correct.

Cheers!

**Comment by cgewecke** [comment]
@HaleTom Hahahah!!! Thank you so much for that link. Kudos to you for excellent review work.  Doing some Byzantium upgrades to SC this weekend, will try get this issue resolved too. 

errored  

![screen shot 2017-11-04 at 11 27 23 am](https://user-images.githubusercontent.com/7332026/32408308-2f4a5fc4-c153-11e7-9111-b9ca24011439.png)

**Comment by HaleTom** [comment]
Welcome :)  The link I gave says it would be better to use:

`Your test runner (Truffle?) crashed because the tests encountered an error.`

**Comment by cgewecke** [comment]
Will do. Thanks!
