### ISSUE TITLE
Error: Unexpected token import

### ISSUE THREAD

**Issue by amexperts** [sc-forks/solidity-coverage#136]
I get the error `Unexpected token import` when running. How do I configure to support import with babel?

**Comment by cgewecke** [comment]
@amexperts [zeppelin-solidity](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/truffle-config.js) uses babel in their truffle.js. Does configuring like them resolve the issue? Make sure you add a coverage network to that conf file.

**Comment by amexperts** [comment]
Thanks. Sorted now. I had missed adding the coverage network. cheers.
