### ISSUE TITLE
An event isn't mined correctly if it has only one argument

### ISSUE THREAD

**Issue by q0LoCo** [sc-forks/solidity-coverage#138]
For example:
``` solidity
event OnItemRemoved(uint256 indexed itemId);
```
I got
``` output
   { logIndex: '0x01',
    transactionIndex: '0x00',
    transactionHash: '0x5f0f11c0e9569747552b50868d6a15ae409893640d6b00720808f48b89964b75',
    blockHash: '0x6821f0c9b59beb12350210a4bd81ba5cc8183003bb70b9c542e46958b2e5c891',
    blockNumber: '0x1f',
    address: '0xc10066ccea4b30d39b42e7e5a1310a388649a626',
    data: '0x0',
    topics:
     [ '0xe9c597177fb8a2311e4bea1bdac704c74391768c3ed2f5477b56d089859bee46',
       '0x0000000000000000000000000000000000000000000000000000000000000001' ],
    type: 'mined' },
```
After changing to
``` solidity
event OnItemRemoved(uint256 indexed itemId, uint256 date);
```
I got
``` output
{ logIndex: 1,
    transactionIndex: 0,
    transactionHash: '0x2005cfaf2d61babacd48f0c4f7eeda264221d46748897369a68bc6146e1a9d81',
    blockHash: '0x66fb4d4ee6b3673aa60033047cf270113d8b04f1a4c27b9766cff2b5597a8314',
    blockNumber: 31,
    address: '0x02bc7f3054f954bb7a055e80b291af85503916f6',
    type: 'mined',
    event: 'OnItemRemoved',
    args: { itemId: [Object], date: [Object] } },
```
"truffle test" doesn't have this problem.

**Comment by cgewecke** [comment]
@q0LoCo Thanks for reporting, will investigate this. Out of curiosity which version of testrpc are you using when you run truffle test?

**Comment by q0LoCo** [comment]
TestRPC v4.1.3
Truffle v4.0.0-beta2

**Comment by cgewecke** [comment]
@q0LoCo Unfortunately I am not able to reproduce. With:
```javascript
event LogSingle(uint256 indexed itemId);
```

I get:
```javascript
{
  "logIndex": 0,
  "transactionIndex": 0,
  "transactionHash": "0xb087469bfdeb951f09d3b5b8fbde571d40700010b25b6032bc7043355388292e",
  "blockHash": "0x28259c22012e9971bdbddcf45f66dc6b268191d7570c85df9aa44e7d938f61c1",
  "blockNumber": 3,
  "address": "0x5fb0441756cdc44d3d2c4c2061b73199d563c680",
  "type": "mined",
  "event": "LogSingle",
  "args": {
   "itemId": "500"
  }
```

Our dev truffle is v4.0.0-beta2, as is my local. `testrpc-sc` is v4.0.1 (basically). If you have any interest you could try to duplicate your result using our `events` test:

+ contract is [here](https://github.com/sc-forks/solidity-coverage/blob/master/test/sources/cli/Events.sol)
+ truffle test is [here](https://github.com/sc-forks/solidity-coverage/blob/master/test/cli/events.js)
+ main test is [here](https://github.com/sc-forks/solidity-coverage/blob/master/test/app.js#L114) (make that `.only` to skip the rest of the suite)
+ verbose output can be turned on by setting [this variable](https://github.com/sc-forks/solidity-coverage/blob/master/test/app.js#L26) to false.

**Comment by q0LoCo** [comment]
I cannot reproduce it using your code. I try my code and still encounter this problem. 
Try copy, remove and clean up code to create a minimal example to reproduce it, but this time i don't encounter this problem.
Back to my original code, try remove build and coverage folder, also remove coverage.json file. 
Run again, now all tests pass. I just refactored our code yesterday and there are a lot of changes.
I will close the issue. And thank you for investigating.

**Comment by cgewecke** [comment]
Ok! Thanks for opening, maybe someone else will run into the same problem and we'll figure it out.
