### ISSUE TITLE
Catching `require()`'s in tests

### ISSUE THREAD

**Issue by nf-PostQuantum** [sc-forks/solidity-coverage#148]
I'm having an issue testing expected `require()`'s in my solidity tests, the tests that I
've written (that use [zeppelin-solidity](https://github.com/OpenZeppelin/zeppelin-solidity)'s `expectThrow` function) pass when running `truffle test`. However, when I run solidity-coverage I get the following:
```
     AssertionError: Expected throw, got 'Error: VM Exception while processing transaction: revert' instead
      at _callee$ (node_modules/zeppelin-solidity/test/helpers/expectThrow.js:13:5)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as throw] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/zeppelin-solidity/test/helpers/expectThrow.js:7:191)
      at node_modules/zeppelin-solidity/test/helpers/expectThrow.js:7:402
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```
I can't find any ways to catch this so I'm opening an issue for it.
My dependencies:
```
  "dependencies": {
    "babel-eslint": "^8.0.2",
    "eslint": "^4.10.0",
    "zeppelin-solidity": "^1.3.0"
  },
  "devDependencies": {
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "babel-register": "^6.26.0",
    "eslint-config-google": "^0.9.1",
    "solidity-coverage": "^0.3.5",
    "truffle": "^4.0.0-beta.2",
    "web3": "*"
  }
```

A culprit contract function:
```
  function setHash(string _identityType, bytes32 _hash) public onlyOwner {
    require(identityTypeToHash[_identityType] == 0x00);
    hashSet(msg.sender, _identityType);
    identityTypeToHash[_identityType] = _hash;
  }
```

A culprit test:
```
  it('shouldn\'t allow the owner to reset identity hashes', async function() {
    let IdentityRegisterInstance = await IdentityRegister.deployed();
    let identityAddress = await IdentityRegisterInstance.getUserIdentity({from: TOM});
    let IdentityInstance = await Identity.at(identityAddress);
    await expectThrow(IdentityInstance.setHash('fingerprint', TOM_HASH, {from: TOM}));
  });
```

**Comment by nf-PostQuantum** [comment]
Not a fix, but I copied over `expectThrow` and added the revert exception
```
export default async (promise) => {
  try {
    await promise;
  } catch (error) {
    const revert = error.message.search('revert') >= 1;
    const invalidOpcode = error.message.search('invalid opcode') >= 0;
    const outOfGas = error.message.search('out of gas') >= 0;
    assert(
      invalidOpcode || outOfGas || revert,
      'Expected throw, got \'' + error + '\' instead',
    );
    return;
  }
  assert.fail('Expected throw not received');
};
```

**Comment by area** [comment]
Which testrpc version are you running your tests against normally? At a glance, I think this is a difference in behaviour that I would expect if `solidity-coverage` was running post-Byzantium (which the latest is) and the one the tests were running against normally was not?

**Comment by nf-PostQuantum** [comment]
I'm not running `testrpc`, the wonder of `truffle test` is that it runs it's own testrpc so you don't need to have it in your deps, `truffle@4.0.1` uses `ethereumjs-testrpc@^4.0.1`

**Comment by area** [comment]
So from looking at [Truffle's commits](https://github.com/trufflesuite/truffle/commits/develop), 4.0.1 does not include the updates to `testrpc`. Truffle will therefore (I believe) still be pre-byzantium, when `require` still causes a `throw` rather than a `revert`. I think `solidity-coverage` is showing you the future, and your test will fail without coverage once Truffle updates too.

To fix, you will either need to stop expecting a `throw`, but a `revert` or, if a `throw` is what you want, you should use `assert` and not `require` in the contract itself.

**Comment by nf-PostQuantum** [comment]
Cool, so truffle is the issue, I should use up to date solidity syntax.
Awesome thanks 😄

**Comment by area** [comment]
Just to be clear: `require` is still valid solidity syntax, it just means different things pre- and post- fork, and unfortunately you're straddling that line between tests and coverage until Truffle updates.
