### ISSUE TITLE
Can't find contracts imported from node_modules

### ISSUE THREAD

**Issue by davesag** [sc-forks/solidity-coverage#152]
I'm using Truffle `4.0.1`

Some of my contracts `import 'zeppelin-solidity/contracts/token/ERC20.sol'`

* Running my tests from within `truffle develop` is just fine.
* Running my tests by running up my own `testrpc` and running `truffle test` runs just fine.

Running `solidity-coverage` however fails.

    Error: Could not find zeppelin-solidity/contracts/token/ERC20.sol from any sources; imported from /Users/davesag/src/myawesomeproject/coverageEnv/contracts/Escrow.sol

**Comment by area** [comment]
You need to set the `copyNodeModules` flag to true in your config. This will increase runtime; if we can get #117 working everywhere, then you would be able to specify just the zeppelin contracts, but that's not possible for now.

**Comment by davesag** [comment]
Cool that worked kind-of.  I've raised a separate issue, #153 for the error I am now getting.
