### ISSUE TITLE
Weird behavior with packages locked to a git commit

### ISSUE THREAD

**Issue by hickscorp** [sc-forks/solidity-coverage#165]
If in your package.json, you have something like this:

```
  "dependencies": {
    "zeppelin-solidity": "git+http://github.com/OpenZeppelin/zeppelin-solidity#ddcae6254ea4d15204f4830bd2580bce03423aec"
  },
```

And then if you configure `solidity-coverage` with something like this:

```
module.exports = {
  host: 'localhost',
  port: 8555,
  norpc: false,
  testCommand: 'yarn run truffle test --network coverage',
  copyPackages: ['zeppelin-solidity']
};
```

Then something very weird happens. The correct version of `zeppelin` is copied in the `coverageEnv` directory, until after the `Instrumenting...` steps are done, and then the package is reverted to the `1.4` version.

Eg:

If I `cat node_modules/zeppelin-solidity/contracts/math/SafeMath.sol`, I get the latest from their git repo. Each function is annotated `internal pure`.
However if I cat `cat coverageEnv/node_modules/zeppelin-solidity/contracts/math/SafeMath.sol` **before** the `Instrumenting...` steps, the file stays the same but if I do so just after the `Instrumenting...` steps, the file is reverted to their `1.4` branch version and the functions are incorrectly annotated `internal`.

What's going on?

**Comment by cgewecke** [comment]
@hickscorp The removal of the pure modifier during the instrumentation step is intentional. See #146 for more on why this necessary. Agree this is weird but believe coverage is running the zeppelin version you intend, apart from the modifications it makes to contracts in order to execute successfully.

**Comment by hickscorp** [comment]
@cgewecke My bad indeed. A coincidence that I was updating a package that adds modifier, and I thought the version of the package was being reverted. Thanks.
