### ISSUE TITLE
Fails to run if Truffle is a local dependency.

### ISSUE THREAD

**Issue by hickscorp** [sc-forks/solidity-coverage#166]
We use Truffle locally in each of our projects (We do not use global packages except for `npm` and `yarn` by convention, because we want all developers to run the same versions). Therefore, we run truffle via `yarn run truffle` or `./node_modules/truffle/bin/truffle`.

With this sort of setup, `solidity-coverage` becomes useless, because it hard-codes a `truffle compile --network coverage`.

**Comment by cgewecke** [comment]
@hickscorp Apologies for this and thank you for opening - it's behavior recently introduced by an effort to fix an unrelated bug. 

I will update the README to document the problem / solution this morning. You can keep truffle as local dependency if you set the 'copyNodeModules' option to true, or by qualifying the path for the 'compileCommand' option as shown [here](https://github.com/sc-forks/solidity-coverage/issues/163#issuecomment-350810131).

**Comment by hickscorp** [comment]
@cgewecke Thanks for the very quick update. I will adjust and try according to the instructions you provided.

**Comment by cgewecke** [comment]
@hickscorp Hopefully that worked. . . In any case, leaving this issue open and marking as a bug since it will probably be a problem for many people.

**Comment by area** [comment]
I don't think `copyNodeModules` works on its own, because the compileCommand will still look for a global truffle, right?

**Comment by cgewecke** [comment]
Fixed with `0.7.0`
