### ISSUE TITLE
Truffle times out on long loops w/ `Error: Could not connect to your Ethereum client.`

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#170]
An example of this @ [Consensys/Tokens](https://github.com/ConsenSys/Tokens/issues/103#issuecomment-353228030). 

Probably depends on the box and the loop but anything over ~10,000 iterations is redlining it.

**Comment by elenadimitrova** [comment]
We occasionally see this when running our test suite of ~140 tests

**Comment by cgewecke** [comment]
I think this might be a non-issue in `0.7.0`  - we just sit inside the vm and maintain an in memory map of line hits. 

No solidity-coverage related mysterious disconnection reports recently...
