### ISSUE TITLE
The 'contracts_build_directory' is not handled correctly (as it is handled by truffle)

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#184]
In order to make `solidity-coverage` handle the `contracts_build_directory` option in the same manner it is handled by `truffle`, one should prepend `../` to the value.

For example:

In my `truffle` configuration, I have `contracts_build_directory: "../../artifacts"`.

This makes `truffle` create a folder named `artifacts`, two levels above the root directory.

For `solidity-coverage` to do the same, I need to change it to `contracts_build_directory: "../../../artifacts"`.

It's as if `solidity-coverage` considers the root folder of the project to be one level deeper than what `truffle` considers it.

**Comment by cgewecke** [comment]
@barakman Thanks for noting this, makes sense. Labeling as a bug.

**Comment by barakman** [comment]
I've actually discovered just a few days ago, that this problem goes all the way back to `truffle`.

The `contracts_build_directory` option is not supported correctly when you try anything other than `truffle compile` (for example, `truffle migrate`).

I have reported it on their GIT as well (see [here](https://github.com/trufflesuite/truffle/issues/862)).

Thanks

**Comment by cgewecke** [comment]
Ah ok, I'm going to close here then and will self-assign over there.
