### ISSUE TITLE
Testrpc does not exit upon coverage competion (Linux)

### ISSUE THREAD

**Issue by adamstaveley** [sc-forks/solidity-coverage#186]
If I run coverage twice, testrpc will throw `Error: listen EADDRINUSE :::8555` on the second try.

As a result I have to manually close the testrpc process spawned by solidity-coverage before running again. It looks as though it should kill the process from a brief look through the code. 

OS is Ubuntu 16.04.

**Comment by cgewecke** [comment]
@adamstaveley Out of curiosity how are you invoking the coverage tool? Also which version are you using?

**Comment by adamstaveley** [comment]
@cgewecke I have it installed locally as a dev dependency. Originally invoked through an npm script (e.g. `"coverage": "solidity-coverage"`) but using `node_modules/.bin/solidity-coverage` produces the same result. I also tried reinstalling it but had the same issue. 

The version is 0.4.9.

I tested on macOS today and it worked as expected with testrpc exiting on coverage completion.

**Comment by area** [comment]
It seems as if OSX and Linux [differ on how they handle child processes](https://github.com/nodejs/node-v0.x-archive/issues/8649) when using `.kill()`. But we're just using `childprocess.exec` to directly launch `testrpc`, aren't we? There shouldn't be any children, should there?

**Comment by fvictorio** [comment]
Can confirm, this is happening to me too in Ubuntu 17.10.

**Comment by mswezey23** [comment]
Confirming again - does not kill process on Ubuntu

**Comment by cgewecke** [comment]
It looks like Linux might require that you [destroy the stdout, stdout streams](https://github.com/nodejs/node/issues/5451#issuecomment-189441200) of the child process as well. Will add that in the next release and see if it resolves this.

**Comment by cgewecke** [comment]
@adamstaveley 
@mswezey23 
@fvictorio 

Have added logic to kill stdout/stderr streams on exit to `0.5.0`. If any of you have a chance, could you run that version and see if this is resolved? Tx!

**Comment by zoenolan** [comment]
Just updated [asset-token](https://github.com/clearmatics/asset-token/commit/ca935725903ba5d86cb50a6c86e4c8e7a8642a08) to 0.5.0. Still seeing the node process after a coverage run on Ubuntu 17.10

**Comment by mswezey23** [comment]
I still get this error as it does not close: 

testRpc stout:
Ganache CLI v6.1.2 (ganache-core: 2.1.0)
Error: listen EADDRINUSE :::8555

**Comment by fvictorio** [comment]
@cgewecke Have you tried using https://www.npmjs.com/package/tree-kill?

I was writing a script that, among other things, starts ganache and I was having a hard time killing it. Using tree-kill was the only thing that worked.

**Comment by cgewecke** [comment]
@fvictorio Thank you! No I haven't - I looked into more a while ago and it seemed like shell that exec runs in is not getting killed on Linux. So tree kill looks perfect.

**Comment by cgewecke** [comment]
Should be fixed in `0.5.1`. Thanks again @fvictorio.

**Comment by zoenolan** [comment]
Also works for us on Ubuntu 17.10

**Comment by mswezey23** [comment]
Works in 16.XX! 

Thanks!!!
