### ISSUE TITLE
Coverage for chosen files only

### ISSUE THREAD

**Issue by leonprou** [sc-forks/solidity-coverage#187]
This would be nice to have because of the coverage process is very long.

There is a `skipFiles` options,  but putting all contracts in the array is a little tiresome.

Thanks you, this project is great and I'm working to integrate it in out organisation.

**Comment by cgewecke** [comment]
@leonprou Hi, thanks for suggesting this and agree it would be useful. Not sure if this is helpful for your case but It's possible to skip entire folders. 
```
skipFiles: ['myFile.sol', 'myFolder']
```

**Comment by cgewecke** [comment]
It's not yet published but this is implemented as a command line option via #838 and issue is being tracked at #805
