### ISSUE TITLE
Any way to pass minimum required coverage?

### ISSUE THREAD

**Issue by aleybovich** [sc-forks/solidity-coverage#191]
Istanbul allows to pass a minimum coverage parameter `--check-coverage 90` and if the coverage is below that threshold, it returns an error code. This helps when setting up CI/CD, fo rexample in bitbucket or Jenkins pipelines - after the code is checked into a branch and coverage is run, it will show a failed build if the coverage is under the desired %. does `solidity-coverage` support that or could you make it support such a parameter? That will be essential to be able to use this tool in CI/CD

Thank you!

**Comment by cgewecke** [comment]
@aleybovich Great idea. Up to now we've relied on git services like Coveralls for build evaluation. Typically they signal failure whenever whenever coverage decreases from a previously achieved level, although they might be configurable.

In general we could and should expose any options Istanbul offers.

**Comment by area** [comment]
Istanbul can be run to just parse the coverage output in this way, rather than executing the tests. So something along the lines of

```istanbul check-coverage --statements 94 --branches 88 --functions 92 --lines 94```

will work right now for the purposes of CI.

**Comment by EdsonAlcala** [comment]
yeah, I solved it using @area code, just ran it after the coverage report was generated from solidity-coverage.

**Comment by cgewecke** [comment]
Cool, closing.
