### ISSUE TITLE
coverage tests always pass locally but fail on travis

### ISSUE THREAD

**Issue by szerintedmi** [sc-forks/solidity-coverage#197]
Our tests are passing locally with solidity-coverage but [fails randomly on travis](https://travis-ci.org/Augmint/augmint-contracts/builds/347085573). 

We used to have random crashes and issues with ganache-cli <  6.1.0 but but 6.1.0 proven to be very stable so far. Therefore we have ganache-cli 6.1.0-beta.2 in our local dev dependencies and tests are running locally and on travis like a charm.

So my guess is that in travis build solidity-coverage is running against a different ganache version.

What is the ganache version solidity-coverage is using and where does it get it from?

**Comment by area** [comment]
You are correct - we are using an old version of `ganache-cli` (in fact, predating the change to the name from `testrpc`). The new version is only in beta but fixes [issues like this one](https://github.com/trufflesuite/ganache-cli/issues/359) resulting in stable builds. Given it is only in beta, I have been loathe to update our version (we add some additional minor functionality to make coverage work, so it's not quite as simple as bumping our `package.json`).

In the meantime, for stable builds, you can monkeypatch the installed `testrpc` and `truffle` like we are doing at [Colony](https://github.com/joincolony/colonynetwork) - the relevant files are `temp-testrpc.patch`, `temp-truffle.patch`, and they are applied before running tests with the commands:

```
patch -N ./node_modules/ethereumjs-testrpc-sc/build/cli.node.js temp-testrpc.patch
patch -N ./node_modules/truffle/build/cli.bundled.js temp-truffle.patch
```

These commands disable use of the `evm_revert` during the work `truffle` does between tests, and so will slightly increase the test run time, but will make them stable. You might even be able to get away with just the truffle patch - the `testrpc` patch implements [this diff](https://github.com/ethereumjs/merkle-patricia-tree/pull/30) but I'm not 100% that it's required. It would be good to know if it wasn't necessary.

These monkeypatches will be able to be removed once `ganache-cli` used by `solidity-coverage` is updated.

**Comment by szerintedmi** [comment]
Thank you  @area !
I assume these patches work only on ganache-cli 6.0.3 and truffle 4.0.6 (as I see in your packages.json). We are on latest versions from both and I assume these would likely work only with exact same versions?

We also heavily rely on snapshots in our tests (a couple of more complex ones are actually even taking / reverting snapshots within the test case).

What boggles me is how it comes that coverage tests are running reliably locally while they keep randomly crashing on Travis. The packages should be the same (we are using the local version for every node modules in our scripts...). Any idea?

For now I will try to upload coverage reports manually from local coverage runs or try to figure out why local works and travis fails.

Side note: 
Apart from the [key not found db error](https://github.com/trufflesuite/ganache-cli/issues/359) which you mentioned we've been struggling with [Cannot read property 'pop' of undefined issue](https://github.com/trufflesuite/ganache-cli/issues/417) too. Both of those seems to have gone with [Ganache 6.1.0-beta.x](https://github.com/trufflesuite/ganache-cli/releases)
I understand you are hesitant to switch to beta but in our case it proved to be much more stable both for local development and tests (UI and contract) and  for CI.

**Comment by area** [comment]
> I assume these patches work only on ganache-cli 6.0.3 and truffle 4.0.6 (as I see in your packages.json). We are on latest versions from both and I assume these would likely work only with exact same versions?

They're fairly simple patches, so it would not surprise me if they worked on other versions. `patch` is pretty good at that sort of stuff.

>We also heavily rely on snapshots in our tests (a couple of more complex ones are actually even taking / reverting snapshots within the test case).

Ah, then this solution isn't really suitable for you.

> What boggles me is how it comes that coverage tests are running reliably locally while they keep randomly crashing on Travis. The packages should be the same (we are using the local version for every node modules in our scripts...). Any idea?

While the underlying issue is (I believe) still not quite known, it was definitely a race condition of some sort. Therefore, if your local build is running on a beefier computer than Travis (which is likely true), then it may avoid the race condition. If this hypothesis is true, then forcing high CPU usage locally while running the tests should trigger it.

> I understand you are hesitant to switch to beta but in our case it proved to be much more stable both for local development and tests (UI and contract) and for CI.

Yeah, I am aware. I was hoping it was going to come out of beta quickly, but that doesn't seem to be the case.

**Comment by szerintedmi** [comment]
FYI: ganache-cli 6.1.0 stable just has been released

**Comment by cgewecke** [comment]
@szerintedmi @area Tentatively scheduling this for Sunday, March 11 (this year) unless already done by then.

**Comment by cgewecke** [comment]
testrpc-sc uses the new ganache with `0.4.12`. This update passed our zeppelin E2E - hopefully it's ok -if you're on @area's patch you're probably good for a while anyway. 

Please feel free to re-open if this fix doesn't work or you continue to see instability.
