### ISSUE TITLE
Solidity-coverage breaks on `emit` keyword

### ISSUE THREAD

**Issue by aleybovich** [sc-forks/solidity-coverage#208]
I updated the compiler version to 0.4.21 and added `emit` when emitting events. Everything compiles fine and truffle tests run fine as well (I had to force update solc version in truffle install). But when running solidity-converage, I get the error about `emit` which tells me that the package is using an older version of solc. 

The error happens on instrumentation step (compilation step is successful).

How do I locally upgrade solc version that solidity-coverage is using?

**Comment by cgewecke** [comment]
@aleybovich If you have a chance could you post the error?  It's probably from our parser which needs to be fixed here to accept the new keyword.

**Comment by aleybovich** [comment]
@cgewecke this is the relevant part of the log:

> 

> Writing artifacts to ./build/contracts
> 
> Instrumenting  ./coverageEnv/contracts/CertificateIssuers.sol
> Cleaning up...
> There was a problem instrumenting ./coverageEnv/contracts/CertificateIssuers.sol: SyntaxError: Expected "!=", "%", "%=", "&", "&&", "&=", "*", "*=", "+", "++", "+=", ",", "-", "--", "-=", "/", "/*", "/=", ";", "<", "<<", "<<=", "<=", "=", "==", ">", ">=", ">>", ">>=", ">>>", "?", "^", "^=","|", "|=", "||", comment, end of line, or whitespace but "(" found. Line: 37, Column: 30
> Exiting without generating coverage...

**Comment by andresilva** [comment]
I also had the same issue. I added support for the `emit` keyword in the solidity parser (https://github.com/sc-forks/solidity-parser/pull/13) not sure if anything else needs to be changed here.

**Comment by cgewecke** [comment]
Published in `0.4.15` thanks to parser fix by @andresilva.
