### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined after Running: truffle test --network coverage  

### ISSUE THREAD

**Issue by emavgl** [sc-forks/solidity-coverage#210]
Hi, I would like to use your tool for a very simple contract. So, as explained in the README file I've installed truffle tools (globally with yarn) and run `npm install --save-dev solidity-coverage`. After that I have initialized a truffle project and tested it using ganache-cli and web3.js.

When I run your tool using `./node_modules/.bin/solidity-coverage` the logs are the following:

```
Generating coverage environment
Running: truffle compile  
(this can take a few seconds)...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/oddeven.sol...
Writing artifacts to ./build/contracts

Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Instrumenting  ./coverageEnv/contracts/oddeven.sol
Running: truffle compile  
(this can take a few seconds)...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/oddeven.sol...
Writing artifacts to ./build/contracts

Launched testrpc on port 8555
Running: truffle test  
(this can take a few seconds)...
TypeError: Cannot read property 'filter' of undefined
    at /home/my-user/.config/yarn/global/node_modules/truffle/build/webpack:/~/truffle-core/lib/commands/test.js:47:1
    at /home/my-user/.config/yarn/global/node_modules/truffle/build/webpack:/~/truffle-core/~/node-dir/lib/paths.js:72:1
    at FSReqWrap.oncomplete (fs.js:170:21)
Cleaning up...
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
```

I'm on Ubuntu 16.04 and I'm using solidity-coverage 0.4.14 and Truffle 4.1.3.   
Am I doing something wrong with the setup of the tools? Thank you in advance.

**Comment by cgewecke** [comment]
@emavgl I'm on OSX  an just ran the following successfully:
```shell
npm install -g truffle # Installed 4.1.3
mkdir metacoin
cd metacoin
truffle unbox metacoin
npm init
npm install --save-dev solidity-coverage
./node_modules/.bin/solidity-coverage # Produced report
```

One difference may be yarn? Another may be that something about the organization of your truffle project is unusual. Does `truffle test` on it's own work?

**Comment by emavgl** [comment]
Hi, thank you for your answer. Fortunately this was a stupid mistake.
The problem was that I didn't have a `test` folder in my truffle project and, although I was able to run the command `truffle test /path/of/test/script.js`, it throws that exception if I run `truffle test` without specifying any path (as it also happens when launching your tool). 

Consider handling this exception or adding a new `testFolder` field in the configuration file.

**Comment by cgewecke** [comment]
Thanks @emavgl. Glad it worked. Will take your suggestion under advisement.
