### ISSUE TITLE
solidity-coverage w/o truffle?

### ISSUE THREAD

**Issue by ewingrj** [sc-forks/solidity-coverage#216]
I'm not sure of the feasibility of this, but it would be great if this tool could be designed to work with tooling other then Truffle. Possibly by defining some type of interface that needs to be implemented?

**Comment by cgewecke** [comment]
@perissology Completely agree. That's always been a goal and we've tried make the test runner configurable in the [options](https://github.com/sc-forks/solidity-coverage#options). 

Unfortunately for reasons relating to the event based instrumentation strategy used here and growing strictness at Solidity about what kinds of functions can fire events, we've become  dependent on the truffle artifact / dev stack. We need to be able to modify the contract ABIs to end run restrictions for `view` and `pure` modifiers and run two compilation sweeps to get things to work correctly. That's meant that we need to have a clear definition of artifact location and compilation processes to be effective. Truffle provides those and is widely used. It's not adequate though.

You might be interested in [work](https://0xproject.com/docs/sol-cov) that has been going on at 0xProject to add coverage to their build. They're not on Truffle and have built an in-memory opcode based coverage tool tailored to their stack. I believe it's meant to be quite flexible though.

We've been interested in moving in that direction for [a while](https://github.com/sc-forks/solidity-coverage/issues/150), but this is a volunteer project and has limited engineering resources at the moment. 

If you have any suggestions about how to make things work for your use case (or want to work on this), would be more than happy to discuss. 

Thanks!

**Comment by cgewecke** [comment]
Closing via `0.7.0`. That releases [exposes an API][1] which lets you build a custom coverage runner. 

There are two [plugins][2] - one for Truffle, one for Buidler - which can be used as recipes if you need to tailor the tool for a different dev stack.

[1]: https://github.com/sc-forks/solidity-coverage/blob/master/docs/api.md#solidity-coverage-api
[2]: https://github.com/sc-forks/solidity-coverage/tree/master/plugins
