### ISSUE TITLE
Reimplement ternary instrumentation

### ISSUE THREAD

**Issue by area** [sc-forks/solidity-coverage#219]
So it seems our implementation for the instrumentation of ternary statements [was unsupported](https://github.com/ethereum/solidity/issues/3887) all along, so that's not going to be supported again like I hoped it was going to...

I think, unfortunately, this leaves us with replacing ternary statements with 'full' if/then/else statements as the only option if we want this branch coverage back...

**Comment by cgewecke** [comment]
This could be possible in the new design using a strategy similar to the one proposed for #175 [here](https://github.com/sc-forks/solidity-coverage/issues/175#issuecomment-532020343).

`0.7.0` instruments as shown below. Line/branch hits are tracked by inspecting the vm stack at each opcode step and picking out hashes we've passed to an injected "coverage" function:
```solidity
contract Test {
  function coverage_0xab123(bytes32 c__0xab123) public pure {}

  function a(uint x) public {

    coverage_0xab123(0xa9065...549e2); /* line */         
  
    if (x == 1) {
  
      coverage_0xab123(0x85e7e...afacf); /* branch */ 
      coverage_0xab123(0xfa262...4fb28); /* line */  
 
      x = 3;
  
    } else { 
      coverage_0xab123(0xb54c1...3ef6b); /* branch */ 
    }
}
```

If we modify this approach and define two coverage functions which return true/false bool respectively...
```solidity
function covFn_True(bytes32 hash) public pure returns (bool) {
  return true; 
}

function covFn_False(bytes32 hash) public pure returns (bool) {}
```

We should be able to detect ternary branches by injecting like this:
```solidity
a  ?  b : c;

// Transformed to:
( covFn_True(h) && a || covFn_False(h) ) ? b : c;
```
If `a == true`, the true branch gets marked (and executes).
if `a == false`, the false branch gets marked (but does not execute).

I think this is correct but the injection logic itself might be tricky to get right with complex conditions.

**Comment by cgewecke** [comment]
This was done in v0.8.x. Closing...
