### ISSUE TITLE
0.4.22 features not supported (constructor)

### ISSUE THREAD

**Issue by aleybovich** [sc-forks/solidity-coverage#220]
Solidity 0.4.22 introduced the new way of defining constructors by introducing `constructor` keyword (https://github.com/ethereum/solidity/releases/tag/v0.4.22):

Instead of

```
contract Escrow {
    function Escrow(arg1) { ... }
}
```

Now it's 
```
contract Escrow {
    contructor (arg1) { ... }
}
```

Solidity-coverage needs to be updated to support `constructor`. Currently, it throws an error:

```
There was a problem instrumenting ./coverageEnv/contracts/Escrow.sol: SyntaxError: Expected "[", "constant", "internal", "private", "public", comment, end of line, identifier, or whitespace but "(" found. Line: 61, Column: 17
Exiting without generating coverage...
```

**Comment by cgewecke** [comment]
@aleybovich `0.5.0`  supports `constructor`. Closing, please ping if there are continuing issues with this. 

Thanks for opening!
