### ISSUE TITLE
Should Update to Latest Ganache

### ISSUE THREAD

**Issue by mbeylin** [sc-forks/solidity-coverage#223]
My tests fail when called by `solidity-coverage`, however they all pass when calling `truffle test`. 

This seems to occur for a number of reasons:
- the testrpc instance that `solidity-coverage` uses doesn't allow for time mutations (ie calling `evm_increaseTime` returns `Invalid JSON RPC response from provider`)
- the testrpc instance doesn't use the default mnemonic that ganache uses: `candy maple cake sugar pudding cream honey rich smooth crumble sweet treat`

I believe these could both be fixed by using a newer version of ganache-cli instead of a testrpc instance

**Comment by cgewecke** [comment]
Hi @mbeylin. The face is testrpc, the heart is ganache. We're publishing it from [this branch](https://github.com/sc-forks/testrpc-sc/tree/coverage) and the last update was mid-March. Only thing that is older is `ethereumjs-vm` which is from the Byzantium fork.

You might fix the default mnemonic issue by adding it via the `testrpcOptions` in solcover.js. Another possibility is  to configure things in a shell script and launch testrpc-sc separately. There's a nice example of this is at Zeppelin [here](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/scripts/test.sh). If you go that route you should set `norpc` to true in solcover.js. Agree this isn't super convenient.

Re: `increaseTime` - Zeppelin is increasing time [here](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/helpers/increaseTime.js) and their tests [look clean](https://travis-ci.org/OpenZeppelin/zeppelin-solidity/jobs/370345343) using `0.4.15`.  Do you see a difference between your case and theirs that might narrow this issue a bit?

**Comment by mbeylin** [comment]
My apologies, I believe I simply wasn't properly running testrpc. I'll close this issue, but regardless thank you for the quick support 👍

**Comment by cgewecke** [comment]
@mbeylin Oh no worries!
