### ISSUE TITLE
Easily Configurable ETH Balance parameter for accounts

### ISSUE THREAD

**Issue by mswezey23** [sc-forks/solidity-coverage#228]
Currently, Solidity Coverage does not have a trivial way of setting the default ETH balance for the testRPC accounts.

This makes it difficult to test caps of token sales at a proper rate. One has to get creative in hitting the cap by either:

1) Setting the cap lower to make sure the code works - which may not fit everyone's needs
2) A better approach, calculate a HIGH rate that allows the cap to be hit within 100 ETH balance per account.
3) Create a lot of accounts... not ideal in any testing situation. 

Regardless of the 3 above workarounds - they are not ideal for long-term development. 

Ganache has this in their config file: 
"default_balance_ether": 10000
(https://github.com/trufflesuite/ganache/issues/84)

I propose that in the next release, this feature should be added in some sort of fashion that makes sense.

**Comment by cgewecke** [comment]
Hi @mswezey23, thanks for opening. 

It doesn't seem to be documented at `ganache-cli` but it's possible to set the default balance using the `--defaultEtherBalance` flag. Solidity-coverage uses a coverage enabled ganache fork called `testrpc-sc` under the hood so any option over there is available here as well.  You have two options if you want to configure solidity-coverage to run like this:

+ set `norpc: true` in `.solcover.js` and launch `testrpc-sc` separately at the command line with whatever additional flags you need. More info in the FAQ [here](https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-testrpc-sc-on-its-own)

+ use the `testrpcOptions` key in `.solcover.js` to specify additional flags. More info in the options section of the README [here](https://github.com/sc-forks/solidity-coverage#options)

**Comment by mswezey23** [comment]
Hey @cgewecke 

Worked like a charm! Thanks so much for keeping up my responses and maintaining Solidity Coverage! 🎉
