### ISSUE TITLE
Error: The contract code couldn't be stored, please check your gas amount.

### ISSUE THREAD

**Issue by aleybovich** [sc-forks/solidity-coverage#229]
In my dev environment I use Ganache and deploying my smart contracts there works fine: `truffle migrate --reset` deploys the contracts.

But, when running `solidity-coverage` I get the error: `Error: The contract code couldn't be stored, please check your gas amount.`

Any ideas?

**Comment by cgewecke** [comment]
+ are you using the coverage network with the correctly specified (high) gas?
+ have you hardcoded gas values in your migrations scripts somewhere?

**Comment by aleybovich** [comment]
I tried adding a coverage config with max gas but the didn't help. I refactored the contract that was having the issue, and the error went away. Still don't know why it was happening, but does no more :)
