### ISSUE TITLE
Installation fails in Ubuntu 18.04

### ISSUE THREAD

**Issue by 24thsaint** [sc-forks/solidity-coverage#239]
Steps to reproduce:
1. Be on Ubuntu 18.04
2. Node version: 8.11.2
3. npm version: 6.0.1

> npm install --save-dev solidity-coverage

Output:
```
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/baymax/.npm/_logs/2018-05-24T07_15_23_847Z-debug.log
```
Debug log:
[2018-05-24T07_15_23_847Z-debug.log](https://github.com/sc-forks/solidity-coverage/files/2034230/2018-05-24T07_15_23_847Z-debug.log)

**Comment by cgewecke** [comment]
@24thsaint I tried to reproduce this in TravisCI which runs Ubuntu/Trusty and was not able to. (Test [here](https://travis-ci.org/cgewecke/tree-kill-test). )

Have you installed re-installed npm recently (to upgrade to v6)? It's possible that something has gone wrong there - have seen a lot of reports of installation breaking. Is solidity-coverage the only tool you're having a problem pulling down from npm?

**Comment by 24thsaint** [comment]
Hello. Tried to install today. Seems like the publish yesterday fixed something?

This is fixed now. :smile:  Thank you so much for an amazing package, keep it up! :heart_eyes: 

![screenshot from 2018-05-25 09-28-18](https://user-images.githubusercontent.com/8315544/40521411-1075b9a0-5ffe-11e8-9a38-3032fe40b879.png)
