### ISSUE TITLE
Zero percent coverage

### ISSUE THREAD

**Issue by juztin** [sc-forks/solidity-coverage#241]
---
node: 10.1.0
npm: 5.6.0
truffle: 4.1.8
---

Unable to get any reported coverage of a contract implementation, although it does show 100% of the interface is covered.

---

Contract is setup similar to:  

```
    ┌───────────┐  ┌─────────┐
    │ Interface │  │ Library │
    ├───────────┤  └─────────┘
    │ +methodA  │        │
    └───────────┘        │
         │               │
         │               │
         │               │
    ┌──────────────┐     │
    │ Contract     │     │
    ├──────────────┤     │
    │ +libraryProp │─────┘
    │ +methodA     │
    └──────────────┘
```

After installing, and running, `solidity-coverage` we get the following:

```
---------------------|----------|----------|----------|----------|----------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------|----------|----------|----------|----------|----------------|
 contracts/          |        0 |        0 |        0 |        0 |                |
  Contract.sol       |        0 |        0 |        0 |        0 |... 411,412,414 |
  Interface.sol      |      100 |      100 |      100 |      100 |                |
---------------------|----------|----------|----------|----------|----------------|
All files            |        0 |        0 |        0 |        0 |                |
---------------------|----------|----------|----------|----------|----------------|
```

On the first run we're also experiencing the following error:

```
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
```

To work around this we do a ```% touch ./allFiredEvents```, and then re-run `./node_modules/.bin/solidity-coverage`.

Also, after adding some more in-depth code/tests, we also start running into:

```
Error: VM Exception while processing transaction: out of gas
...
```
_although regular unit tests run just fine. Also, the coverage is still generated_

**Comment by cgewecke** [comment]
@juztin It's likely you are not running the correct client - `./allFiredEvents` is generated by `testrpc-sc` (which launches automatically in the background unless configured otherwise) and contains events fired by the coverage instrumentation. 

Could you post your `truffle.js` & `.solcover.js`? Alternatively, look over the README and make sure you haven't accidentally missed something that's causing a regular `ganache-cli` client to run instead of the coverage client.

**Comment by juztin** [comment]
We're using a bit of a custom setup, I attempted changing things a few different ways, but 'am still stuck =( _(we're using Mist, instead of Ganache)_  

Here's what we've got for `truffle.js`:  

_(This is what we use for development and unit-tests, which is currently working for those)_
```javascript
module.exports = {
  networks: {
    mist: {
      host: '192.168.1.5',
      port: 8545,
      network_id: '*',
      gas: 4698712,
      from: '0x0000000000000000000000000000000000000'
    }
  }
};
```

...and `.solcover.js`  

_(not totally sure what is the "correct" thing for our Mist setup)_
```javascript
module.exports = {
  port: 8545,
  testCommand: 'node --max-old-space-size=4096 ../node_modules/.bin/truffle test --network mist',
  compileCommand: 'node --max-old-space-size=4096 ../node_modules/.bin/truffle compile --network mist',
  norpc: true,
  copyPackages: ['LibraryPackage']
};
```

I'm sure we're doing something silly to make it angry =)

**Comment by cgewecke** [comment]
@juztin 

Is mist required to get your test suite to run?

SC only works with a special coverage enabled client `ethereumjs-testrpc-sc`. You might try adding a `coverage` network to `truffle.js`:
```javascript
coverage: {
      host: "localhost",
      network_id: "*",
      port: 8555,         // <-- If you change this, also set the port option in .solcover.js.
      gas: 0xfffffffffff, // <-- Use this high gas value
      gasPrice: 0x01      // <-- Use this low gas price
    },
```
and :
+ replacing `--network mist` with `--network coverage` in `.solcover.js`
+ launching testrpc-sc separately at the command line 
```shell
node_modules/.bin/testrpc-sc --gasLimit 0xfffffffffff --port 8555
```

**Comment by cgewecke** [comment]
@juztin Sorry, unrelated - but did you use a tool to generate that nice graph of your contracts? If so - what?

**Comment by juztin** [comment]
Got it working!

_truffle.js_  
```javascript
module.exports = {
  networks: {
    mist: {
      host: '192.168.5.5',
      port: 8545,
      network_id: '*',
      gas: 4698712,
      from: '0x0000000000000000000000000000000000000'
    },
    coverage: {
      host: 'localhost',
      network_id: '*',
      port: 8555,
      gas: 0xfffffffffff,
      gasPrice: 0x01
    }
  }
};
```

_.solcover.js_
```javascript
module.exports = {
  copyPackages: ['LibraryPackage']
};
```
---

Hmmm...  
It's working now, for the first run, but all subsequent runs fail with a `Error: listen EADDRINUSE :::8555`.  
We're running the whole thing within a container, so we can just kill/relaunch the container, but it is consistently failing with this after the first successful run.

**Comment by cgewecke** [comment]
Ok great - you just need to capture the process ID of the testrpc-sc instance you're launching in the container and kill it explicitly when the test run stops (or detect an existing instance and use that instead of launching a new one). There's an example of doing this in a shell script at zeppelin-solidity [here](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/scripts/test.sh).

**Comment by juztin** [comment]
Thanks @cgewecke 

Sorry to bug you with a non-bug, but your help has been much appreciated _(Thanks for the link to the Zeppelin script, I hadn't thought of doing that, but that may save us some time)_

**Comment by juztin** [comment]
Sorry, missed your comment about the graphs =)

I did a lot of ASCII stuff in a previous life (BBS stuff), so I just threw it together real quick by hand. I have used the Vim plugin DrawIt before, which works pretty good too.

**Comment by cgewecke** [comment]
@juztin Sweet, thanks.
