### ISSUE TITLE
Unable to point truffle test to transpiled JS folder

### ISSUE THREAD

**Issue by justinkchen** [sc-forks/solidity-coverage#243]
Hi there, I'm currently using Typescript for my tests, and so I need to go through a transpile step with `tsc`.  However, it is in a separate folder and `truffle test `is looking for `.js` tests only in the `/test` folder .  When I try to point it to the transpile folder, it throws an error since I guess `shell.exec` doesn't like `truffle test transpiled/test/*.js` commands

**Comment by cgewecke** [comment]
@justinkchen Thanks for reporting - do you have a link to your project or a small reproduction case we could test a solution against?

**Comment by justinkchen** [comment]
I found a hacky way to work around it which is to copy and paste the .js files into the `test/` folder and then clean them up after running coverage lol https://github.com/SetProtocol/set-protocol-contracts/

**Comment by cgewecke** [comment]
This should be fixed with 0.7.0, which ships as a truffle plugin. 

There's now a cli flag that lets you specify the test file set:
```
truffle run coverage --file="transpiled/test/*.js"
```
