### ISSUE TITLE
ENOENT: no such file or directory, open './allFiredEvents'

### ISSUE THREAD

**Issue by etsangsplk** [sc-forks/solidity-coverage#245]
It looks like no such file or directory, open './allFiredEvents' is a recurring problem .

At cleaning phase:

Cleaning up...
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...

**Comment by cgewecke** [comment]
@etsangsplk Usually people see this error when they aren't running the special coverage enabled testrpc client that `solidity-coverage` uses. Could you share your `truffle.js` and `.solcover.js`? And look over the README to make sure your setup is correct?

It's important the network ports are right (defaults to 8555) and that truffle doesn't accidentally connect to a normal ganache instance.

**Comment by etsangsplk** [comment]
truffle-config.js
```
require('dotenv').config();
require('babel-register');
require('babel-polyfill');

const HDWalletProvider = require('truffle-hdwallet-provider');

const providerWithMnemonic = (mnemonic, rpcEndpoint) =>
  new HDWalletProvider(mnemonic, rpcEndpoint);

const infuraProvider = network => providerWithMnemonic(
  process.env.MNEMONIC || '',
  `https://${network}.infura.io/${process.env.INFURA_API_KEY}`
);

const ropstenProvider = process.env.SOLIDITY_COVERAGE
  ? undefined
  : infuraProvider('ropsten');

const networks = {
  development: {
    host: 'localhost',
    port: 8545,
    network_id: '*',
  },
  ropsten: {
    provider: ropstenProvider,
    network_id: 3,
  },
  coverage: {
    host: 'localhost',
    network_id: '*',
    port: 8555,
    gas: 0xfffffffffff,
    gasPrice: 0x01,
  },
  ganache: {
    host: 'localhost',
    port: 8545,
    network_id: '*',
  },
};
```
.solcover.js
```
module.exports = {
    norpc: true,
    testCommand: 'node --max-old-space-size=4096 ../node_modules/.bin/truffle test --network coverage',
    compileCommand: 'node --max-old-space-size=4096 ../node_modules/.bin/truffle compile --network coverage',
    skipFiles: []
}

```

**Comment by etsangsplk** [comment]
and I use ganache-cli

**Comment by etsangsplk** [comment]
scTopics is created..
allFiredEvents is never created.

**Comment by cgewecke** [comment]
@etsangsplk Instead of ganache-cli use `testrpc-sc` as shown [here](https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-testrpc-sc-on-its-own). It comes with solidity-coverage  - there's nothing special to download.

**Comment by etsangsplk** [comment]
@cgewecke I alreayd did 
./node_modules/.bin/testrpc-sc -> ../ethereumjs-testrpc-sc/build/cli.node.js

**Comment by etsangsplk** [comment]
Anyway to force it to create the file or user to set what file to create?

**Comment by cgewecke** [comment]
To be clear, in one terminal window you're launching the testrpc-sc
```shell
node_modules/.bin/testrpc-sc --gasLimit 0xfffffffffff --port 8555 
```
and in a second terminal you're running the coverage tool, correct?
```shell
./node_modules/.bin/solidity-coverage
```

The file must be generated in the course of the coverage run - it contains all of the coverage events that are fired as your tests run. These are then processed by the tool to generate the report.

**Comment by etsangsplk** [comment]
@cgewecke Yup I also have done the 2 terminals approach. The setup I have is essentially the same as 
OpenZeppelin/openzeppelin-solidity

**Comment by cgewecke** [comment]
@etsangsplk Can you share a link to your project so I can try to reproduce this? I'm out of ideas.

**Comment by cgewecke** [comment]
@etsangsplk Is this closeable?

**Comment by etsangsplk** [comment]
Just tried and also noticed there is a zombie testrpc process

**Comment by renardbebe** [comment]
I got the same error and do not know how to fix it.
Could you please help me with the **absolute path** of `truffle.js` and `.solcover.js`?
Thanks a lot...

**Comment by renardbebe** [comment]
@etsangsplk @cgewecke 
I just run 
**$ $(npm bin)/testrpc-sc --gasLimit 0xfffffffffff --port 8555**
and
**$ $(npm bin)/solidity-coverage**
in two terminals and it occurs:
```
testRpc stdout:
Ganache CLI v6.1.6 (ganache-core: 2.1.6)
Error: listen EADDRINUSE: address already in use 127.0.0.1:8555
    at Server.setupListenHandle [as _listen2] (net.js:1290:14)
    at listenInCluster (net.js:1338:12)
    at doListen (net.js:1469:7)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)

Cleaning up...
Shutting down testrpc-sc (pid 9776)
testRpc errored after launching as a childprocess.
Exiting without generating coverage...

```
How should this error be fixed? Could you please do me a favor - Thanks a lot.

**Comment by gkamtzir** [comment]
> @etsangsplk @cgewecke
> I just run
> **$ $(npm bin)/testrpc-sc --gasLimit 0xfffffffffff --port 8555**
> and
> **$ $(npm bin)/solidity-coverage**
> in two terminals and it occurs:
> 
> ```
> testRpc stdout:
> Ganache CLI v6.1.6 (ganache-core: 2.1.6)
> Error: listen EADDRINUSE: address already in use 127.0.0.1:8555
>     at Server.setupListenHandle [as _listen2] (net.js:1290:14)
>     at listenInCluster (net.js:1338:12)
>     at doListen (net.js:1469:7)
>     at internalTickCallback (internal/process/next_tick.js:72:19)
>     at process._tickCallback (internal/process/next_tick.js:47:5)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
>     at startup (internal/bootstrap/node.js:303:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
> 
> Cleaning up...
> Shutting down testrpc-sc (pid 9776)
> testRpc errored after launching as a childprocess.
> Exiting without generating coverage...
> ```
> 
> How should this error be fixed? Could you please do me a favor - Thanks a lot.

Hey @renardbebe !
Kinda late but this error occurs when the **norpc** property in the **.solcover.js** is set to false (or you haven't explicitly set it to true, since it always defaults to false) and a **testrpc** instance is, already, running. The **norpc** property basically instructs the **solidity-coverage** to create its own **testrpc** instance when it's set to false or to use an existing when it's set to true. For more details take a look at the options [here](https://github.com/sc-forks/solidity-coverage).

**Comment by PaulRBerg** [comment]
@gkamtzir is correct, but the same error occurs when importing contracts from packages in "node_modules" that have *not* been listed in `.solcover.js`.

Also see https://github.com/sc-forks/solidity-coverage/issues/131#issuecomment-417748614.
