### ISSUE TITLE
Problem instrumenting Constructor 0.4.24

### ISSUE THREAD

**Issue by asoong** [sc-forks/solidity-coverage#246]
Hi there, running v0.5.4 and running into an issue with my constructor:

`There was a problem instrumenting ./coverageEnv/contracts/core/SetToken.sol: SyntaxError: Expected ".", "[", "constant", "internal", "private", "public", comment, end of line, identifier, or whitespace but "(" found. Line: 132, Column: 16`

The source could can be found here: [SetToken.sol](https://github.com/SetProtocol/set-protocol-contracts/blob/master/contracts/core/SetToken.sol#L132).

Thank you!

**Comment by cgewecke** [comment]
@asoong I cloned SetToken, un-commented your skip file entry for `SetToken.sol` and ran `npm run coverage`. Everything just worked.
```
Writing artifacts to ./build/contracts

Instrumenting  ./coverageEnv/contracts/core/Core.sol
Instrumenting  ./coverageEnv/contracts/core/interfaces/ISetFactory.sol
Instrumenting  ./coverageEnv/contracts/core/interfaces/ISetToken.sol
Instrumenting  ./coverageEnv/contracts/core/interfaces/ITransferProxy.sol
Instrumenting  ./coverageEnv/contracts/core/interfaces/IVault.sol
Instrumenting  ./coverageEnv/contracts/core/SetToken.sol
Instrumenting  ./coverageEnv/contracts/core/SetTokenFactory.sol
Instrumenting  ./coverageEnv/contracts/core/TransferProxy.sol
Instrumenting  ./coverageEnv/contracts/core/Vault.sol
Instrumenting  ./coverageEnv/contracts/lib/AddressArrayUtils.sol
Instrumenting  ./coverageEnv/contracts/lib/Authorizable.sol
Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Skipping instrumentation of  ./coverageEnv/contracts/test/BadTokenMock.sol
Skipping instrumentation of  ./coverageEnv/contracts/test/DummyToken.sol
Skipping instrumentation of  ./coverageEnv/contracts/test/StandardTokenMock.sol
Skipping instrumentation of  ./coverageEnv/contracts/test/StandardTokenWithFeeMock.sol
Running: truffle compile --network coverage 
```
Coverage report:

![screen shot 2018-06-15 at 9 56 48 pm](https://user-images.githubusercontent.com/7332026/41495902-19e297f2-70e7-11e8-8aa9-4f9d9a5027bf.png)

Tests look really nice by the way :) Do you have any idea what might be causing this difference? 

I'm on:
OS: OSX
Node: v8.9.4

**Comment by asoong** [comment]
Unsure, but seemed to be my computer only. Heh heh, blasted away and it's working fine now. Thank you for your time!

**Comment by cgewecke** [comment]
Sweet! np.
