### ISSUE TITLE
Error when running SC on contracts using experimental ABIEncoderV2

### ISSUE THREAD

**Issue by marinatorras** [sc-forks/solidity-coverage#250]
I am running Solidity Coverage on a contract that uses structs with experimental ABIEncoderV2. The contract compiles and runs on Truffle, but when I run SC on it I get the following error:

`SyntaxError: Expected comment, end of line, string, or whitespace but "A" found. Line: 2, Column: 21
Exiting without generating coverage...`

The line where SC crashes is the following:

`pragma experimental ABIEncoderV2;`

I am currently running solidity-coverage version 0.4.15.
Let me know if there is any more information I can provide.

Thanks,

**Comment by cgewecke** [comment]
@marinatorras Thank you, perfect. Will fix in the next couple days.

**Comment by kmiyachi** [comment]
+1

**Comment by Astrovicis** [comment]
+1

**Comment by shessenauer** [comment]
+1

**Comment by kmiyachi** [comment]
Hey, any updates on this fix. Do you have any ideas of what file this bug is in/ if it is an easy fix by just avoiding calling an error in the parser when you hit the 'ABIEncoderV2' string?

**Comment by cgewecke** [comment]
@kimyachi I'm so sorry - I didn't get to this yet this week - things are slightly crazy at work. Will **really** fix this ASAP.

**Comment by cgewecke** [comment]
@marinatorras This should be fixed in `0.5.5` - thanks for reporting and apologies for the delay.

**Comment by marinatorras** [comment]
@cgewecke Awesome, thank you so much!

**Comment by HarryR** [comment]
Can confirm, ABIEncoderV2 doesn't barf with 0.5.5.
