### ISSUE TITLE
Heap out of memory when reading events from file (50,000 tests)

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#251]
Running a massive set of tests, I get this:
```
  51973 passing (5h)

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewUninitializedFixedArray
 5: v8::internal::WasmDebugInfo::SetupForTesting
 6: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 7: 000001FEEE7043C1
```

The contents of file `.solcover.js`:
```
module.exports = {
    port:           8555,
    norpc:          true,
    testCommand:    "node --max-old-space-size=8192 ../../node_modules/truffle/build/cli.bundled.js test --network=coverage",
    compileCommand: "node --max-old-space-size=8192 ../../node_modules/truffle/build/cli.bundled.js compile --network=coverage",
};
```

Environment:
- Windows 10
- node 8.11.2
- npm 6.1.0

**Comment by cgewecke** [comment]
@barakman Modified your issue title to make to disambiguate your case from the one we already advise about in the FAQ.

I don't know how to fix this. If anyone has any ideas, please weigh in.

**Comment by barakman** [comment]
@cgewecke:

I did a quick drill-through on the `solidity-coverage` source code.

The reason for this out-of-memory-problem is the line:

    .on('line', line => this.events.push(line))

In file `app.js`  / function `generateReport`.

I believe that a working solution would be to save these lines into a text file instead of an array.

You will then also need to change function `generate` (in file `coverageMap.js`), to take a text file instead of an array as input.

**Comment by barakman** [comment]
Note:

The solution above does not work, because the `allFiredEvents` stream is being read asynchronously.

I will post an update asap.

**Comment by cgewecke** [comment]
Note to self - 0.7.0 will resolve this by using an integer counter for intrumentation hits rather than processing them as individually enumerated events.  Mem consumption should be well within bounds (for this step anyway). 

It looks like this problem is also affecting colonyNetwork's test suites and forcing them to split their tests into two CI jobs. . .

**Comment by cgewecke** [comment]
`0.7.0` fixes this by handling everything in-process and it should have a much smaller memory footprint since hits are managed with a counter. 

Thanks for opening @barakman, hope you have a great new year!

**Comment by barakman** [comment]
@cgewecke: You're welcome.
This one in specific has been both enjoyable and excruciating to investigate and resolve (well, workaround)... As a matter of fact, in terms of difficulty, I believe that it was second to [Truffle 4 issue 729](https://github.com/trufflesuite/truffle/issues/729) only.
Thank you for providing this outstanding tool, which IMO is a must in every Ethereum project.
Happy New Year :)
