### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/Users/oaks-view/coverageEnv/.env’.

### ISSUE THREAD

**Issue by oaks-view** [sc-forks/solidity-coverage#253]
I get this error whenever I try to generate a coverage report for my node(express) application. I m running version 0.5.4 solidity-coverage and im not using any configuration through .solcover.js. Im 
This problem it appears to be an issue with solidity-coverage itself.  When it starts up it is supposed to copy all assets to a subdirectory prior to execution - however it appears to miss files beginning with “.”. 

Any way to get past this?

**Comment by cgewecke** [comment]
@oaks-view Ah yes, that makes sense. I think the problem is [here](https://github.com/sc-forks/solidity-coverage/blob/master/lib/app.js#L68) where we list the files in the root directory. We're not using the `-A` flag.

Will fix this shortly. Thank you!

**Comment by cgewecke** [comment]
This should be fixed in `v0.5.5`. . . please ping if you continue to have problems with it.

**Comment by oaks-view** [comment]
@cgewecke thanks for the update. The issue is resolved
