### ISSUE TITLE
Unable to compile source code not containing contract

### ISSUE THREAD

**Issue by 4000D** [sc-forks/solidity-coverage#257]
I usually use `_imports.sol` file just to import contracts from node_modules. `_imports.sol` is required to get truffle artifacts saved in `build/contracts` directory.

But solidity-coverage doesn't support a solidity file which does not contain `contract`.

**Comment by cgewecke** [comment]
@4000D Sorry I just have a few questions:

+ Can you link to a project on Github where you are doing this so we can see what's going wrong?  What is the error / result?
+ Do you have tests for these imports and need to get coverage for them? 
+ Is it possible to insert a fake, empty contract with a constructor in the `_imports.sol` to get around this problem? You could omit that contract from the report by using the `skipFiles` option in your `.solcover.js` config.

**Comment by cgewecke** [comment]
@4000D Closing due to lack of response. Please ping if this is still a problem.
