### ISSUE TITLE
Fails with: `Uncaught Error: Contract transaction couldn't be found after 50 blocks`

### ISSUE THREAD

**Issue by juztin** [sc-forks/solidity-coverage#261]
Have a project where quite a few tests are being created programatically, within 4 test files _(around 230 tests in total)_.  

When running either `truffle test` or `truffle develop`, then `test`, all tests run as expected with no exceptions.

When running with `solidity-coverage`, after the first test or two things seem to freeze for a second, then `ERROR: Uncaught Error: Contract transaction couldn't be found after 50 blocks`, after which the coverage graph is output.

When it does succeed, only a single function shows coverage _(a setup function for the contract(s) that's run before the generated tests)_

I was able to narrow down the failure to a single test files that does 2 `before` setups. If these are combined into a single `before` for both `contract` blocks, then `solidity-coverage` runs without error, although the results still only show a single function being covered.

**Comment by cgewecke** [comment]
@juztin Can you share your code? It's super unusual to see this code with testrpc / ganache. It implies that the client is mining. Is that the case?
> ERROR: Uncaught Error: Contract transaction couldn't be found after 50 blocks

**Comment by juztin** [comment]
Hey @cgewecke,

I think I'm gonna close this for now.  
I can't post the code I've been using _(it's for work, and you know how they can be)_. 
But I think it was related to some funky multi-promise stuff.
I ended up backtracking a bit on having super dynamic/generated tests, and the issue has gone away. _(it was probably something with my code to be honest)_.

**Comment by cgewecke** [comment]
Ok sweet thanks @juztin
