### ISSUE TITLE
Mysterious coverage drop?

### ISSUE THREAD

**Issue by nventuro** [sc-forks/solidity-coverage#268]
Hi!

On this [OpenZeppelin PR](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1137), I noticed our [coverage of a contract dropped to 0](https://coveralls.io/builds/18294588/source?filename=contracts/ownership/HasNoTokens.sol), though the [changes](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1137/files#diff-01929739950f027082f56ccf6991ba3e) to that file were insubstantial (in particular, the test that covers the related lines was not modified). Could you help us track this down so we can bump coverage up again?

Also, when testing locally I saw all of the `mocks` contracts were being [skipped](https://travis-ci.org/OpenZeppelin/openzeppelin-solidity/jobs/411351643#L2943) during the instrumentation phase, I take it this is so that coverage of those is not measured, and not a mistake?

Thanks a lot!

**Comment by nventuro** [comment]
Turns out it was my fault all along, thanks @cgewecke for spotting it right away! I fixed it in [this PR](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1149).

**Comment by cgewecke** [comment]
Sweet!
