### ISSUE TITLE
Skip assertions

### ISSUE THREAD

**Issue by nventuro** [sc-forks/solidity-coverage#269]
In OpenZeppelin, we're considering dropping some of our `assert`s and changing them to `require` (see [here](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1120) for some relevant discussion), changing the semantics of `assert` to 'shouldn't ever fail unless the code is buggy'. Because of that, `solidity-coverage` will report a line with partial coverage on each `assert`.

Could the requirement of `assert` failure being covered be dropped, or an option added to disable it (maybe with a huge error flag if the assertion ended up failing)? We'd hate to have our coverage figure drop because of a semantics difference.

Thank you for your time and awesome work!

**Comment by cgewecke** [comment]
@nventuro Yes. This was raised in #149 earlier this year and looking through the comments there I feel like both sides are reasonable...

I *think* we could add this as an option fairly easily as well.

**Comment by nventuro** [comment]
An option would be great, since there's not yet consensus on this topic. I look forward to it!

**Comment by PaulRBerg** [comment]
Should the label for this feature be updated to "0.8.0"?

I'm using solidity-coverage@0.7.10 and assertions are market as not covered:

<img width="1102" alt="Capture d’écran 2020-10-20 à 17 00 22" src="https://user-images.githubusercontent.com/8782666/96596773-c0734780-12f5-11eb-9236-ae12a9596f1b.png">

**Comment by cgewecke** [comment]
@PaulRBerg 

Purely out of curiosity, why do you prefer using `assert` over `require` in this case?

**Comment by PaulRBerg** [comment]
Because of a `require` statement that's executed before:

```solidity
require(vault.freeCollateral >= collateralAmount, "ERR_INSUFFICIENT_FREE_COLLATERAL");
```

Also because Solidity's [SMTChecker](https://solidity.readthedocs.io/en/v0.7.3/security-considerations.html) needs both requires and assertions to be able to run it.

**Comment by cgewecke** [comment]
@PaulRBerg 

Ah ok.. I would lean towards making this change without a major version bump since no one thinks these should branch and it's more like a bug. 

Thanks for the SMT link - I didn't realize these have a working application now.

**Comment by PaulRBerg** [comment]
Happy to help.

And yes, SMTChecker is actually useful! Check out this [presentation][1] by Leonardo Alt. It uses `assert` statements to identify bugs in a contract.

[1]: https://www.youtube.com/watch?v=QQbWpN76HEg

**Comment by KholdStare** [comment]
@cgewecke Can probably close this issue since the fix has been merged?

**Comment by cgewecke** [comment]
Thanks @KholdStare ... sorry for the delay.
