### ISSUE TITLE
Coverage doesn't run when upgrading from 0.5.4 to 0.5.7?

### ISSUE THREAD

**Issue by simondlr** [sc-forks/solidity-coverage#277]
Hey. Trying to debug this.

I upgraded to 0.5.7, but now none of the coverage wants to run.

The CI just states that "base fee exceeds gas limit".

https://circleci.com/gh/UjoTeam/contracts-badges/56?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.

Not sure what changed from 0.5.4 to 0.5.7 that causes this to fail now. I had to downgrade back to 0.5.4 to keep it working.

Any more code, logs, etc I can provide?

**Comment by cgewecke** [comment]
Hi @simondlr - thanks for reporting, will take a look. . . the main difference between the two versions is an upgrade to the coverage client, pulling in recent changes from ethereumjs-vm / ganache-cli (like error reason string support). If your tests run well with ganache-cli 6.1.2 then `0.5.4` should be good.

**Comment by simondlr** [comment]
So, did more debugging.

Running tests without coverage works fine with latest ganache-cli (6.1.8).

Running against ganache-cli 6.1.8 with solidity-coverage 0.5.4 OR 0.5.7 causes the issues. Solidity-coverage 0.5.4 with built-in testrpc works (since it's an older ganache-cli).

So, something that coverage is doing with my contracts are causing problems with the latest ganache-cli.
