### ISSUE TITLE
Add ability to skip certain files or folders from being copied into the coverage environment

### ISSUE THREAD

**Issue by sohkai** [sc-forks/solidity-coverage#284]
Similar to `skipFiles`, it would be great to have a `skipCopyFiles` (can't think of a better name right now...) that one could list local files or folders they wouldn't like to include in the coverage environment.

An example use case of this is where you have nested packages, and are using `solidity-coverage` at a non-leaf package.

**Comment by cgewecke** [comment]
The need to copy the entire project into a temp folder is gone in 0.7.0. 

We do some copying of solc files in the contracts folder to a temp folder for instrumentation, but there shouldn't be any serious issues with that. 

Closing as an artifact of the 0.6.x design.
