### ISSUE TITLE
I cannot run solidity-coverage in window 10

### ISSUE THREAD

**Issue by dovancao** [sc-forks/solidity-coverage#294]
I try to run

```
 ./node_modules/.bin/solidity-coverage
```

But It got this problem. How can i solve it?

![screenshot_1](https://user-images.githubusercontent.com/36324165/45606815-7f533e00-ba72-11e8-9a20-08c7c5e26fff.png)

Thank you for your help!

**Comment by maxsam4** [comment]
It should be fixed by https://github.com/sc-forks/solidity-coverage/pull/290
You may pick the changes yourself or wait for an npm update to be released.

**Comment by area** [comment]
I am assuming this was fixed by #290. If not, please reopen.
