### ISSUE TITLE
Contracts deployed during migration are not valid?

### ISSUE THREAD

**Issue by Amxx** [sc-forks/solidity-coverage#295]
I am trying to instrument some smart contracts that are deployed during the migration step. Logs from the migrations steps give me addresses of these contracts. 
Later, my tests try to access the smart contracts' functions but I get an error despite the address being the same one as the one in the logs:

`Error: Attempting to run transaction which calls a contract function, but recipient address 0xa8E1074E9b46394a32464bB993C27710fBf37937 is not a contract address`

Any clue what the issue might be. I access the contract using ethers.js library

PS: I tried to reset my directory doing `rm -r coverage.json coverage/`

**Comment by cgewecke** [comment]
This needs a reproduction case or a link to the repo where it's happening. Sorry for letting this languish for so long, but I'm going to close because it doesn't seem like other people are running into this...
