### ISSUE TITLE
Minor: fix configuration example in the main page

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#298]
In the main page, there is a [configuration example](https://www.npmjs.com/package/solidity-coverage#options) which uses `copyPackages: ['zeppelin-solidity']`.

This specific package is actually called `openzeppelin-solidity`, so you may want to spare this issue from many readers who will most likely copy-paste it into their configuration file.

**Comment by cgewecke** [comment]
This is fixed. Thanks!
