### ISSUE TITLE
Using relative paths rather than absolute

### ISSUE THREAD

**Issue by maxsam4** [sc-forks/solidity-coverage#300]
Currently, the path included in the event that is added by the instrumenter is an absolute path which can be huge.

Our instrumented contracts at https://github.com/PolymathNetwork/polymath-core have now become so big due to the absolute paths that they are failing to compile. They instrument and compile just fine if I move the project folder nearer to the root of the system as the absolute path becomes shorter.

I am not sure why absolute paths are currently being used over relative paths. I can provide a set of instrumented contracts that are failing to compile due to huge absolute path, if required.

Update: I have created a PR to fix this.

**Comment by cgewecke** [comment]
In work planned for `0.7.0` we will use an in-process memory to track file locations. Instrumentation will consist of a hash to those values.

**Comment by cgewecke** [comment]
Published w/ 0.7.0
