### ISSUE TITLE
upgrade web3 to 1.0.0-beta.xx

### ISSUE THREAD

**Issue by Amxx** [sc-forks/solidity-coverage#303]
I am trying to instrument the coverage of my tests that are written using web3 1.0.0-beta.35.
Apparently, solidity-coverage uses web3 0.20.6, which has a different api. For example, I'm used to doing web3.utils.keccak256, which is not a valid method in 0.20.6.

I'd like not to have to rewrite all my tests ... moreover I'd like to benefit from the ABIEncoderV2 support in web3 1.0.0-beta.36 when it becomes part of truffle@beta.

Is there an (easy) way to upgrade the version of web3 used by solidity coverage ?

**Comment by cgewecke** [comment]
Web3 is now beta-50 here. If you're using truffle, you're consuming their web3, not solidity-coverage's
