### ISSUE TITLE
code coverage with darq-truffle does not seem to work

### ISSUE THREAD

**Issue by lacabra** [sc-forks/solidity-coverage#304]
I'm trying to run solidity-coverage using [darq-truffle](https://www.npmjs.com/package/darq-truffle) instead of truffle to no avail. I can't find any information online, hence this issue.

For reference, I'm using the following public repo with branch `coverage`:
https://github.com/enigmampc/enigma-contract/tree/coverage

Relevant observations:
* This is my [truffle.js](https://github.com/enigmampc/enigma-contract/blob/coverage/truffle.js) and [.solcover.js](https://github.com/enigmampc/enigma-contract/blob/coverage/.solcover.js)
* The Solidity tests (via [Travis integration](https://travis-ci.com/enigmampc/enigma-contract)) are passing without `solidity-coverage`
* From the output below, one can notice two different errors:

1. `ls: no such file or directory: ./coverageEnv/build/contracts/*.json` which seems to be related to #242  except that I am not setting `contracts_build_directory` in truffle.js, and setting `buildDirPath` in `.solcover.js` does not seem to have any effect to this particular instance of the error.
2. `Error: ENOENT: no such file or directory, open './allFiredEvents'` which seems to be related to #245 except that I am not using any custom testrpc instance, and `norpc` parameter defaults to `false`. As you can see from the output below the testCommand launches testrpc on port 8555, which matches the configuration in truffle.js.

Output:
```
$ npx solidity-coverage
Generating coverage environment
Running: darq-truffle compile
(this can take a few seconds)...
(node:10796) ExperimentalWarning: The fs.promises API is experimental
ls: no such file or directory: ./coverageEnv/build/contracts/*.json
Instrumenting  ./coverageEnv/contracts/Billionare.sol
Instrumenting  ./coverageEnv/contracts/CoinMixer.sol
Instrumenting  ./coverageEnv/contracts/Enigma.sol
Instrumenting  ./coverageEnv/contracts/EnigmaToken.sol
Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Instrumenting  ./coverageEnv/contracts/utils/GetCode2.sol
Running: darq-truffle compile
(this can take a few seconds)...
(node:10798) ExperimentalWarning: The fs.promises API is experimental
ls: no such file or directory: ./coverageEnv/build/contracts/*.json
Launched testrpc on port 8555
Running: darq-truffle test --network coverage
(this can take a few seconds)...
(node:10801) ExperimentalWarning: The fs.promises API is experimental
Cleaning up...
Shutting down testrpc-sc (pid 10799)
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
```
Let me know what additional information you may need from me, or what other things can I try to get the root of the problem. Happy to help/contribute in any way I can, and thanks for your great work on this repo, can't wait to get it working in our setup. 👍

**Comment by elenadimitrova** [comment]
I believe `darq-truffle` is depreciated. It was distributed under `truffle@next` but now we have truffle v5

**Comment by cgewecke** [comment]
`0.6.0` is working fine with the latest Truffle. We're running E2E tests in CI vs openzeppelin-solidity and truffle's metacoin. Closing.
