### ISSUE TITLE
testrpc-sc doesn't return contract's require error message with revert error

### ISSUE THREAD

**Issue by Aniket-Engg** [sc-forks/solidity-coverage#305]
`testrpc-sc` doesn't return contract's `require` and `assert` error string along with error message as it has been updated in `ganache` and `truffle`. So tests checking the returned error message works fine with `truffle test` but breaks when trying to get coverage.

**Comment by felix2feng** [comment]
Having same issue here as well when using truffle's latest beta version

**Comment by KohliSuraj** [comment]
same issue here as well, any solutions?

**Comment by cgewecke** [comment]
This is fixed in `0.6.0`
