### ISSUE TITLE
solidity-coverage adds extra events which make unit-test fail

### ISSUE THREAD

**Issue by StefH** [sc-forks/solidity-coverage#310]
It seems that when using the latest solidity-coverage (0.5.11), truffle (5.0.0-next.25) ganache-cli (6.2.4-beta.1) and solc (0.5.0) additional events / logs are emitted during tests which make the unit-tests fail.

My test code was like:
``` js
it('addSupplier', async () => {
        // Act
        const result = await contract.addSupplier(supplier1, 'Supplier 1');

        // Assert
        assert.lengthOf(result.logs, 1);

        const log = result.logs[0];
        assert.isNotNull(log);

        const event = log.event;
        assert.equal(event, 'AddSupplierEvent');

        const eventArgs = log.args;
        assert.isNotEmpty(eventArgs.from);
        assert.isNotEmpty(eventArgs.id);
        assert.equal(eventArgs.id, supplier1);
        assert.equal(eventArgs.name, 'Supplier 1');
});
```

And I expected **1** event to be submitted : `AddSupplierEvent`, however the output shows:

```
Events emitted during test:
[Coverage]     ---------------------------
[Coverage]
[Coverage]     __FunctionCoverageSupplyChainLogContract(fileName: C:/.../contracts/SupplyChainLogContract.sol, fnId: 1)
[Coverage]     __CoverageSupplyChainLogContract(fileName: C:/.../contracts/SupplyChainLogContract.sol, lineNumber: 9)
[Coverage]     __StatementCoverageSupplyChainLogContract(fileName: C:/.../contracts/SupplyChainLogContract.sol, statementId: 1)
...
[Coverage]     AddSupplierEvent(from: 0xd721da73Adf6AfBFfaC15A8a4Bae662D5D02c351, id: 0x8caa8760a712e9E96868314Bc59711094BAB263E, name: Supplier 1)
```

Is this by design ?

**Comment by angus-hamill** [comment]
Yes, this is exactly how the coverage works. These events are added in the instrumenting step and then read while running tests in order to determine which lines/branches/etc. were hit.

This test will never be able to pass under coverage in its current state.
Your other option is to modify the test. Perhaps use the `EventEmitter` returned when calling `contract.AddSupplierEvent()`

**Comment by StefH** [comment]
Correct. Thanks for the confirmation.
Now I am using [truffle-assertions](https://github.com/rkalis/truffle-assertions) to fix this.

See also my question+answer here:
https://github.com/rkalis/truffle-assertions/issues/15
and
https://ethereum.stackexchange.com/questions/64137/solidity-coverage-adds-extra-events-which-make-unit-test-fail

**Comment by karolinkas** [comment]
Has this been resolved for you then @StefH ?

**Comment by StefH** [comment]
@karolinkas Yes.
You may close this issue for me.
