### ISSUE TITLE
ParserError: extraneous input '{' expecting ')'

### ISSUE THREAD

**Issue by lumir-mrkva** [sc-forks/solidity-coverage#320]
solidity-coverage `0.6.0-beta.5` from #318 is unable to instrument statements without enclosing blocks, like for example:

```
if (number == 1337) return "elite";
```
throws `ParserError: extraneous input '{' expecting ')'`

issue doesn't arise when enclosing block is added, but instrumenting should add block correctly automatically

**Comment by lumir-mrkva** [comment]
btw. it is possible this same issue is present in an earlier version `0.5.11`, but no error message was thrown for me, instrumentation just never finished - hanged forever

**Comment by area** [comment]
Hm, we have a test for this, but even modifying it to a contract like
```
pragma solidity ^0.5.0;

contract Test {
    function a(uint x) public returns (string memory) {
		if (x == 1337) return "elite";
    }
}
```
doesn't cause the issue to show. Can you provide a complete contract that demonstrates the issue?

**Comment by lumir-mrkva** [comment]
i tried again in clean environment and couldn't replicate it even with revision that didn't work before. i guess it  has to been unrelated problem that was fixed by just rebuilding contracts after i added blocks to code.
