### ISSUE TITLE
Instrumenting cannot parse `_000` notation for integers

### ISSUE THREAD

**Issue by KaiRo-at** [sc-forks/solidity-coverage#321]
With 0.6.0-beta.5, I get the following error:

`There was a problem instrumenting ./coverageEnv/contracts/xxx.sol: ParserError: missing ';' at '_000_000' (30:27)`

The Solidity line in question is

`        total = 50_000_000 * (uint256(10) ** decimals());`

This compiles and works fine with solc-js 0.5.7 and truffle 5.0.13, but solidity-coverage seems to not understand the `_000` syntax for integer readability in Solidity.

This is easily worked around by temporarily removing the underscores for running coverage, but it would be nice if it would be supported.

**Comment by cgewecke** [comment]
@KaiRo-at This was an issue at solidity-parser-antlr which has been resolved on master there. Just waiting for a publish. I'm closing this in favor of ticket about deps we need to update. Thanks for catching this!
