### ISSUE TITLE
Add support for `payable address`

### ISSUE THREAD

**Issue by radek1st** [sc-forks/solidity-coverage#322]
When using a payable address in the smart contract function like:

`function submit(address payable destination) public {...}`

getting instrumentation error:

`There was a problem instrumenting ./coverageEnv/contracts/X.sol: SyntaxError: Expected ")", ",", comment, end of line, or whitespace but "d" found. Line: 78, Column: 37`

**Comment by cgewecke** [comment]
Fixed in `0.6.0`. Thank for reporting.
