### ISSUE TITLE
Error instrumenting a large number of if statements without braces

### ISSUE THREAD

**Issue by angus-hamill** [sc-forks/solidity-coverage#324]
Instrumenting seem to fail when instrumenting a large number of if statements without braces.
[Here](https://github.com/angus-hamill/coverageTest) a project with a large (nonsensical) if/else without braces that fails instrumentation yet compiles and passes its tests.

Instrumentation gives the error `There was a problem instrumenting ./coverageEnv/contracts/MetaCoin.sol: ParserError: missing ';' at '}' (27:15)`

I believe this may be something occurring in the `blockWrap` method of `preprocessor.js`, it seems to occasionally be putting braces in the incorrect place like in the middle of a word for example.

**Comment by cgewecke** [comment]
@angus-hamill Added your repro as a regression test in #335 and believe this is fixed with `0.6.0`. Thanks for reporting :)
