### ISSUE TITLE
How to generate './allFiredEvents' file ?

### ISSUE THREAD

**Issue by renardbebe** [sc-forks/solidity-coverage#326]
**`Info.`**
```
Launched testrpc on port 8555
Running: truffle test --network coverage 
Using network 'coverage'.


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



  0 passing (1ms)

Cleaning up...
Shutting down testrpc-sc (pid 8818)
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
```

Could anybody help me with this issue?
I have tried many ways but nothing worked.
Sorry for interrupting and thanks a lot....

**Comment by renardbebe** [comment]
And I could not find the file `.solcover.js` ....

**Comment by yxliang01** [comment]
@renardbebe I think `.solcover.js` is optional that all configurable options will be using their default values.

**Comment by renardbebe** [comment]
But it can't generate the './allFiredEvents' file during the process.

I have tried `touch ./allFiredEvents` command to generate it, but it got **zero coverage percentage** after running, so I think I must have done something wrong....

Could anybody tell me how to generate the ./allFiredEvents file correctly?

**Comment by renardbebe** [comment]
My `truffle.js`

`module.exports = {
    networks: {
        development: {
            host: "localhost",
            port: 8545,
            network_id: "*"
        },
      coverage: {
        host: "localhost",
        network_id: "*",
        port: 8555,         // <-- If you change this, also set the port option in .solcover.js.
        gas: 0xfffffffffff, // <-- Use this high gas value
        gasPrice: 0x01      // <-- Use this low gas price
      },
    }
  };`

and I do not create `.solcover.js`.
During the process, `testrpc-sc` did not generate `./allFiredEvents` file.

**Comment by yxliang01** [comment]
@renardbebe Maybe you try to remove all the generated directories then run it again. I once got this error due to compilation problems.
