### ISSUE TITLE
Upgrade ethereumjs-testrpc-sc to 6.4.1

### ISSUE THREAD

**Issue by BrendanChou** [sc-forks/solidity-coverage#327]
So that Petersburg-compiled contracts can properly be tested for coverage

**Comment by cgewecke** [comment]
This is fixed on `solidity-coverage@beta`

**Comment by BrendanChou** [comment]
Good to see you back @cgewecke, missed your contributions

**Comment by fabianorodrigo** [comment]
How would it be possible to contribute to this project? Just clone the repository, make changes locally and create a pull request?

**Comment by cgewecke** [comment]
@fabianorodrigo Yes. Because there is work underway at the moment could you open an issue with the changes you'd like to make so we can talk about them first?

**Comment by fabianorodrigo** [comment]
> @fabianorodrigo Yes. Because there is work underway at the moment could you open an issue with the changes you'd like to make so we can talk about them first?

@cgewecke , how is the development environment setup? I cloned the repository and just call 'node bin/exec.js' but I got the message "couldn't find a 'contracts' folder to instrument". 
When I try do debug using VSCode I got '${file} can not be resolved. Please open an editor'.

Should I just create a folder 'contract' with some solidity files to see it running or is there a better way to do this?

**Comment by cgewecke** [comment]
@fabianorodrigo Apologies, I'm going to move your question to separate issue: #338.

**Comment by cgewecke** [comment]
Fixed in 0.6.0. Thanks @BrendanChou!
