### ISSUE TITLE
Check 0.6.0 on Bancor

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#328]
Input example:
```
assembly {
    if iszero(...) {
        ...
    }
}
```
Error printout:
```
There was a problem instrumenting...
SyntaxError: Expected "=:", "for", "function", "hex", "let", "return", "switch", "{", "}", comment, end of line, number, string, or whitespace but "i" found.
```
I believe that the reason for this is that in a "normal" `if` statement the expression is encapsulated with `()`, while in an "assembly" `if` statement the expression is **not** encapsulated with `()`.

Unfortunately, adding `()` in the assembly statement yields a compilation error.

I've been able to track the problem down to the invocation of function `parseInlineAssemblyBlock` from function `parseInlineAssemblyStatement` (in file `parser.js`, located under `node_modules/solidity-parser-sc/build`).

As a workaround, one can use a `switch` block instead of the `if` statement.

I am using solc v0.4.24.

Thanks

**Comment by cgewecke** [comment]
@barakman Hi. Could you try installing `solidity-coverage@beta` and see if this issue persists? That version uses a new parser which should be more robust. 

If you're still seeing it I will open an issue in the relevant repo.

**Comment by barakman** [comment]
@cgewecke:

I have later realized that the `if` is probably not supported, not because of the reason I had initially mentioned, but simply because of an earlier parser (or compiler) version, from when `jumpi` was the conventional way to achieve an `if` functionality (I realized this after trying to use `jumpi`, for which I got a "deprecated" message from my solc v0.4.24 compiler).

In any case, I have no problem trying this beta version, but the official npm page says that v0.5.11 is the latest version, so I will need to know what version to set in my `package.json` file.

Thank you for your help.

BTW, it is also critical for me to handle the [`staticcall` issue](https://github.com/sc-forks/solidity-coverage/issues/329), since at present I am obliged to handle it by tweaking your source code.

At present, I have the following two lines of code in one of my contracts:
```
/* SC0 */ if iszero(staticcall(gas, _dest, add(data, 32), mload(data), ret, 64)) {revert(0, 0)}
// SC1 // switch call(gas, _dest, 0, add(data, 32), mload(data), ret, 64) case 0 {revert(0, 0)}
```

And in file `app.js`, function `instrumentTarget`, I modify this:
```
contract = fs.readFileSync(contractPath).toString();
```
To this:
```
contract = fs.readFileSync(contractPath).toString().replace('/* SC0 */', '// SC0 //').replace('// SC1 //', '/* SC1 */');
```
This is a rather "nasty" hack, as you can probably understand, but I cannot utilize `solidity-coverage` to execute successfully on my contract-system otherwise.

Thanks!!!

**Comment by cgewecke** [comment]
Ah! Nice hack, thanks for sharing that.  

Over the next couple months we're going to look at a non-events based coverage strategy which should resolve this as well as other problems. But I don't think there will be a solution here before  the `0.7.0` release (in August?). 

Will try to publish the beta as `0.6.0` this week. It's currently developed on the `leapDao` branch if you're maintaining your own fork.

**Comment by barakman** [comment]
@cgewecke:

Great, thank you, I will give v0.6.0 a try once it's there.
It's actually good to know that `solidity-coverage` is being maintained and updated.
I was pretty sure otherwise, since it's been quite long since the current-latest version (v0.5.11) had been published.

I am currently relying on [this node script](https://github.com/bancorprotocol/contracts/blob/master/scripts/run-tests.js) for executing both `truffle test` and `solidity-coverage` via an `npm test` command.

As you can see, it assumes the viability of file `/ethereumjs-testrpc-sc/build/cli.node.js` under the `node_modules` directory.

I'd tend to guess that if you have a new parser and/or compiler, then it's going to be something other than `testrpc-sc`. I'd actually be very happy if it stayed under the exact same file name and path (since it would allow me to keep my script unhanged), but I'd settle for anything else, so long as I can support it in that script.

Thanks again :)

**Comment by cgewecke** [comment]
@barakman I will open a PR in bancor making sure it works when published. At first glance, the only thing in the script that might need a change is to add a `--allowUnlimitedContractSize` to the testrpc-sc invocation. `0.6.0` will be tracking a newer version of ganache-cli.

**Comment by barakman** [comment]
@cgewecke:
Great, thank you!
I'll be standing-by for this PR.

BTW, you may as well fix the huge memory-consumption issue that you have in the current version of `solidity-coverage`, which I have reported in the past (fails for extremely large test-suites, due to a preliminary "full-scale" memory allocation).

It might help you to see how I'm patching this problem in [this "npm post-install" script](https://github.com/bancorprotocol/contracts/blob/master/scripts/fix-modules.js) (lines 29-38), which is automatically executed at the end of my `npm install` (I'm pretty sure that I've also posted this patch when I reported that problem).

Thanks.

**Comment by cgewecke** [comment]
@barakman Update - I'm testing `0.6.0` against Bancor today (and finding solidity-coverage bugs) but it looks like you will probably be able to update without too much difficulty when problems here are fixed. Hopefully open there by Monday.

**Comment by barakman** [comment]
@cgewecke:

Thank you very much for that!

The assembly issues that I have mentioned in this thread and in [the other thread](https://github.com/sc-forks/solidity-coverage/issues/329) are currently applicable (i.e., reproducible) only on our [latest branch](https://github.com/bancorprotocol/contracts/tree/0.4.8), which we haven't merged to the master branch as of yet.

The link that I have provided in [one of the comments above](https://github.com/sc-forks/solidity-coverage/issues/328#issuecomment-507832246) actually leads to our master branch, so I have you did not rely (only) on this branch for testing the two assembly issues at hand.

I see that v0.6.0 is now available on npm official website, so I will give it a try and report back.

Any chance that this version is compatible with solc v0.4.x?

Thanks again :)

**Comment by cgewecke** [comment]
@barakman Actually - I found a bug in `0.6.0` while running the bancor tests and just merged a fix for it. Everything on Bancor master run ok with the aforementioned change and a small change to the launch invocation line in `run-tests.js`:
```diff
-        SOL_COVERAGE: [NODE_DIR + "/ethereumjs-testrpc-sc/build/cli.node.js", "--port=7555", "--gasPrice=0x1"        , "--gasLimit=0x1fffffffffffff"],
+        SOL_COVERAGE: [NODE_DIR + "/.bin/testrpc-sc", "--port=7555", "--gasPrice=0x1"        , "--gasLimit=0x1fffffffffffff"],
```

Haven't tested any other branches - will publish `0.6.1` in ~1 hour, have to run to something rn.

**Comment by cgewecke** [comment]
I got 0.6.2 to run Bancor locally without the static call hacks. Everything looks ok to me. Opened a PR over there but it doesn't seem setup for outside contributors really. Feel free to close that - I'm closing this, please ping if you run into problems.

**Comment by barakman** [comment]
> ```diff
> /.bin/testrpc-sc
> ```

You probably mean:
> ```diff
> /ethereumjs-testrpc-sc/cli.js
> ```

Since the file `testrpc-sc` under the `.bin` folder is not even a js file.

Thank you in any case, I'm testing it...

**Comment by barakman** [comment]
Works like a charm!
I've updated our repo to solidity-coverage v0.6.2.
Thanks :)
