### ISSUE TITLE
Solidity-coverage recognizes not a single line of tested code?

### ISSUE THREAD

**Issue by itinance** [sc-forks/solidity-coverage#330]
Hi everybody :)

I've done `solidity-coverage` on my project but it won't track any single line of code. Has anybody faced the same issue yet?

In my tests, I adopted the approach from OpenZeppelin-ETH to use mocks of my contracts, that inherits from the base contracts encapsulating the `initialize`-method into a constructor like here: https://github.com/itinance/ncd-token/blob/master/contracts/mocks/NCDTokenSaleImpl.sol.

Of the xxx-Impl-Files 100% coverage was recognized. But the underlying NCDTokenSale-file as example (like all the others) there were zero lines recognized in coverage although plenty of tests (58) were ran.

This is how it looks like:

<img width="649" alt="Screenshot 2019-07-01 22 30 16" src="https://user-images.githubusercontent.com/1758597/60466354-b4bcc700-9c53-11e9-85e8-c6fdfbd8320e.png">

The files with red colors are the files with code, the green lines are the files consisting only as a proxy with inheriting from the actual contracts.

Anything I can do here without rewriting any tests to use no Mock-contracts?

**Comment by cgewecke** [comment]
This looks like it was a config problem - have opened a PR in NCD which should resolve.

**Comment by itinance** [comment]
Thank you so much! I have tried it out, but are running in several "invalid opcode"-exceptions in beforeEach-functions, that aren't an issue running on ganache-cli. 

They even happen in very simple tests like https://github.com/itinance/ncd-token/blob/master/test/NCDTokenBasicTests.js#L16.

What could be the root cause here?

<img width="1258" alt="Screenshot 2019-07-02 00 04 25" src="https://user-images.githubusercontent.com/1758597/60547687-a4265280-9d20-11e9-99b6-3fe25841c697.png">

**Comment by itinance** [comment]
Ah, this was my fault! I used a different version of `coverage` as intended by @cgewecke in his PR :)  

Again, thank you so much! Really appreciated.

Explicitly upgrading to `solidity-coverage@0.6.0-beta.5` makes it work without the issues mentioned in my previous comment.
