### ISSUE TITLE
Info on setting up development environment and contributing

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#338]
In #327 @fabianorodrigo asked

> how is the development environment setup? I cloned the repository and just call 'node bin/exec.js' but I got the message "couldn't find a 'contracts' folder to instrument".
When I try do debug using VSCode I got '${file} can not be resolved. Please open an editor'.

> Should I just create a folder 'contract' with some solidity files to see it running or is there a better way to do this?

**Comment by cgewecke** [comment]
@fabianorodrigo Are you on windows? I'm not and it's a bit difficult to debug that OS for me....

In general we develop via the tests - if you look in [test/app.js](https://github.com/sc-forks/solidity-coverage/blob/master/test/app.js) you'll see tests that use fixtures for loading a mock project and executing coverage. 

(It's a bit of a mess tbh)

**Comment by fabianorodrigo** [comment]
> @fabianorodrigo Are you on windows? I'm not and it's a bit difficult to debug that OS for me....
> 
> In general we develop via the tests - if you look in [test/app.js](https://github.com/sc-forks/solidity-coverage/blob/master/test/app.js) you'll see tests that use fixtures for loading a mock project and executing coverage.
> 
> (It's a bit of a mess tbh)

I'm using Linux Ubuntu

**Comment by cgewecke** [comment]
Closing this for the time being, not sure how exactly what improvements would be useful. Might reopen elsewhere if there's a concrete proposal to document how SC is developed.
