### ISSUE TITLE
suggestion: release tags on commits

### ISSUE THREAD

**Issue by yxliang01** [sc-forks/solidity-coverage#347]
I think it would be better to tag the commits with release version number. E.g. https://github.com/sc-forks/solidity-coverage/commit/21db7095f2de701ac2c0be624e7e6774dcb78a23 can be tagged as v6.0.2 on git.

Thanks @cgewecke for your effort!

**Comment by cgewecke** [comment]
Yes, agree. It should already be tagged actually. (it is in my local). I use [npm version](https://docs.npmjs.com/cli/version) to increment the package, and that's included. 

Haven't been tagging testrpc-sc but I will start.

**Comment by yxliang01** [comment]
Not sure whether we are on the same page. By seeing the `version` field in `package.json`, indeed, can know the commit of the new release. However, it would be better to directly tagging using the `git` tagging functionality. i.e. tagging using `git tag`. If this is what you meant, I'll just close this issue :)

**Comment by cgewecke** [comment]
```
Users-MacBook-Air:solidity-coverage cgewecke$ git tag -l
v0.6.0
v0.6.2
```
0.6.1 is missing for some reason. The npm command (according to the docs) makes a git tagged commit. Idk.

**Comment by cgewecke** [comment]
I'll make sure and check this in future though. Thanks for highlighting.

**Comment by yxliang01** [comment]
Thanks!
