### ISSUE TITLE
Error encountered when generating coverage report on kyberNetwork

### ISSUE THREAD

**Issue by lin88xu** [sc-forks/solidity-coverage#349]
Hi,

I am trying to generate a coverage report using solidity-coverage on the kyber network swap smart contracts. The github link is:
https://github.com/KyberNetwork/smart-contracts.git

The following npm modules are used during the report generation:
1. Truffle@4.1.14
2. Solidity-coverage@0.6.2

In addition, all contract pragma are changed from minimal solc requirement of 0.4.18 to 0.4.24

Attached are the files that I have changed to facilitate the report generation:
[solcover.txt](https://github.com/sc-forks/solidity-coverage/files/3396269/solcover.txt)
[truffle-config.txt](https://github.com/sc-forks/solidity-coverage/files/3396270/truffle-config.txt)

Attached is the log generated during coverage report generation, the command I used is:
solidity-coverage | sed 's/\x1b\[[0-9;]*m//g' | tee ~/kyberNetwork-coverageReport.txt
[kyberNetwork-coverageReport.txt](https://github.com/sc-forks/solidity-coverage/files/3396209/kyberNetwork-coverageReport.txt)

Thank you

**Comment by cgewecke** [comment]
@lin88xu I see two problems:
+ There are compilation errors in the middle of your compilation output from not updating the pragmas correctly. Example:
```
,/home/linxu/smart-contracts-master/coverageEnv/contracts/mockContracts/NetworkFailingGetRate.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.22+commit.4cb486ee.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.24;
^---------------------^
```
And there's this, where a comma is being mangled into `N8ttt`. I don't know how that's happening, any ideas on your end?
```
event __StatementCoverageUtils2(string fileN8ttt statementId);
```

**Comment by lin88xu** [comment]
@cgewecke Thanks for your reply. Regarding the weird characters problem, sorry I don't have any idea. The compilation error problem has just been resolved at my end(by replacing the `solc` bundled with `truffle`), and this weird character problem is the only error I'm facing at the moment.

**Comment by cgewecke** [comment]
@lin88xu We're not seeing that in CI on Trusty or locally on OSX. You'll to link to a public repo I can clone and run the command on to get further, but I suspect this is something unusual about your OS.

**Comment by lin88xu** [comment]
@cgewecke  the public link is https://github.com/KyberNetwork/smart-contracts.git

**Comment by cgewecke** [comment]
@lin88xu That repo's master branch contains none of the changes you've described above. I've just cloned it and it's dependencies are more than a year out of date. It doesn't compile with the last version of Truffle 4. (4.1.15). It's missing basic instructions about how run a test suite - there's no `npm test` script.

**Comment by lin88xu** [comment]
@cgewecke The branch that I am currently working on is:
https://github.com/lin88xu/smart-contracts.git

From my observation, any versions of truffle other than v4.0.5 will result in truffle test errors. This include the devdependecy in the package.json which states that the required version of truffle is v4.0.1. Both versions of Truffle 4 (4.1.14 and 4.1.15) failed truffle test

**Comment by cgewecke** [comment]
@lin88xu Getting `truffle test` to pass is a prerequisite for debugging this and you'll need to use a higher solc than ships with 4.0.5 because we add statements to the solidity files that use the `emit` keyword. (I think support began around solc v0.4.22.). I see lots of contracts in your fork pinned to `0.4.18`.

**Comment by lin88xu** [comment]
@cgewecke Thanks for the advice. Maybe I shall try running the truffle test to see if it works out. Any progress on your side making truffle test work with versions higher than 4.0.5?

**Comment by cgewecke** [comment]
> Any progress on your side making truffle test work with versions higher than 4.0.5?

@lin88xu No. I'm also not trying to make them work - we don't have the resources here to upgrade an apparently abandoned code base across 10 solc versions. 

Do you mind if I close this issue? It seems solidity-coverage is not usable on Kyber in their current state. You can open a new issue if you run into difficulties after successfully compiling and testing with `solc v0.4.24`.

**Comment by cgewecke** [comment]
Closing per above.
