### ISSUE TITLE
Could not find truffle artifacts from imported packaged.

### ISSUE THREAD

**Issue by Amxx** [sc-forks/solidity-coverage#351]
My code uses external pieces of solidity such as from npm packages. For exemple, I use the ERC1538Proxy artifact from iexec-solidity. In my truffle migration script I import it with `artifacts.require("iexec-solidity/ERC1538Proxy")`.

my .solcover.js contains:
```
copyPackages: [
	'@ensdomains/ens',
	'iexec-solidity',
	'openzeppelin-solidity',
	'rlc-faucet-contract'
],
```

It works well when doing `truffle migrate && truffle test` but I get an error with solidity coverage:

`Error: Error: Could not find artifacts for iexec-solidity/ERC1538Proxy from any sources
    at Object.run (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
`

**Comment by Amxx** [comment]
Yes they are in the node_modules folder

**Comment by cgewecke** [comment]
@Amxx Weird - I'm not sure why migrating would make it able to find the folder, but good :)
