### ISSUE TITLE
Block limit not matching the gas limit (capping the 53 bits)

### ISSUE THREAD

**Issue by Amxx** [sc-forks/solidity-coverage#352]
I'm having issues deploying one of my modules (contract).

I get an "out of gas" error:
```
IexecPocoDelegate" ran out of gas (using a value you set in your network config or deployment parameters.)
   * Block limit:  0x13b4a9f85aaa9
   * Gas sent:     9007199254740991
```

ganache is running with parameters `-l 0x1FFFFFFFFFFFFF -g 0x1` and truffle.js uses the same parameters. I cannot go bigger than `0x1FFFFFFFFFFFFF` as it is the 53 bits limit to safely store numbers.

What am I missing here ? I get my contract is big but the optimized, non-instrumented version fits into a common block ...

**Comment by cgewecke** [comment]
@Amxx Are you using the default coverage network config values from the README? If so could you try running testrpc-sc without that line added: e.g `-l 0x1FFFFFFFFFFFFF -g 0x1`?

**Comment by Amxx** [comment]
my truffle.json contains:
```
coverage:
    {
      host:       "localhost",
      port:       8555,
      network_id: "*",
      gas:        0x1FFFFFFFFFFFFF,
      gasPrice:   0x01
    },
```

I tried using `0xFFFFFFFFFFFFF` instead of `0x1FFFFFFFFFFFFF` ... results are similar. I am using my own ganache, with `'no-rpc': true` in .solcover.js

I tried running the included testrpc instance with
```
port: 8555,
testrpcOptions: '-p 8555 -l 0x1FFFFFFFFFFFFF -g 0x1 -m "<my seed>" -i 1544020727674',
norpc: false,
```

but then I fail even sooner
```
"Migrations" exceeded the block limit (with a gas value you set).
   * Block limit:  0x54a29
   * Gas sent:     500000
```

**Comment by cgewecke** [comment]
@Amxx How about with this?
+ Do not launch your own ganache
+ Remove `-l 0x1FFFFFFFFFFFFF -g 0x1` from testrpc options
+ Set coverage.network gas to: `0xfffffffffff`

**Comment by Amxx** [comment]
This is really counterintuitive, but it works !
