### ISSUE TITLE
Error after coverage run: `Couldn't get a file descriptor referring to the console`

### ISSUE THREAD

**Issue by aleybovich** [sc-forks/solidity-coverage#361]
When I run coverage (0.6.3) in bash (both Elementary and Ubuntu 14 flavors), it successfully runs the tests, correct;y displays the coverage table, but then throws an error which fails the whole process (thus fails the CI):

```
Istanbul coverage reports generated
Cleaning up...
Shutting down testrpc-sc (pid 8639)
Done.
Couldn't get a file descriptor referring to the console
```

Any ideas what it could be?

**Comment by cgewecke** [comment]
@aleybovich That's very strange. The code at the point where `Done.` is logged reads:
```
self.log('Done.');
process.exit(0);
```
**Questions**
+ Are you running anything after solidity-coverage (like coveralls?) - i.e could it be a message from another program?  
+ Is this happening on Travis or Circle? If so could you share your config so I can try to reproduce?

**Comment by aleybovich** [comment]
@cgewecke - it must have been a glitch, I can no longer reproduce the issue.
