### ISSUE TITLE
Incorrect block number

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#362]
With `ganache-cli` 6.4.4, there is a discrepancy between the actual ("on-chain") block number and the reported ("off-chain") block number.

One would expect `web3.eth.blockNumber` to be equal to `block.number`, but the former is always "1 unit behind" the latter 

In other words, `web3.eth.blockNumber` is always equal to `block.number - 1`.

This problem seems to have been resolved on `ganache-cli` 6.5.1 (or possibly even on an earlier version).

I have reported it at https://github.com/trufflesuite/ganache-cli/issues/667, where you can see how to reproduce it very easily.

However being fixed, it is still present on `testrpc-sc` (the version of `ganache-cli` used by `solidity-coverage`).

Hence, upgrading to `ganache-cli` 6.5.1 yields exactly one of the following:
- If I don't fix the test to comply with v6.5.1, then `truffle test` fails
- If I do fix the test to comply with v6.5.1, then `solidity-coverage` fails

I have tested this on `solidity-coverage` 0.6.2 and 0.6.3 (the current latest version).

Would you be able to take the fix which occurred between `ganache-cli` 6.4.4 and `ganache-cli` 6.5.1, and apply it on `testrpc-sc`?

Thanks

**Comment by cgewecke** [comment]
@barakman Yes, will see if I can get this done today. 

Does 6.5.1 also fix the floating timestamp issue (#252)? I don't see that in the release notes but it looks like a fix was [merged](https://github.com/trufflesuite/ganache-core/pull/443) a couple weeks ago.

**Comment by cgewecke** [comment]
@barakman `0.6.4`. Closing but please ping if you're not seeing the change you hoped for.

**Comment by barakman** [comment]
@cgewecke:
Wow, thank you for the incredibly fast response to this.
I've upgraded both `ganache-cli` and `solidity-coverage`, and was able to fix the test to "comply" with both versions correctly.
Thanks!!!
