### ISSUE TITLE
docs: lacking supported truffle version information

### ISSUE THREAD

**Issue by yxliang01** [sc-forks/solidity-coverage#364]
There is no truffle version information stated in the documentation nor in the README(as far as I can see). While I can see for the latest version of solidity-coverage, Truffle v5 is supported, I think it's better to state at somewhere.

Thanks

**Comment by cgewecke** [comment]
@yxliang01 It seems to be working for both Truffle V4 and V5. Are you seeing something different?

**Comment by yxliang01** [comment]
@cgewecke Nope, it also seems to me it supports quite wide range of Truffle versions. But, I just feel like better to get some Truffle versioning information from the team in the sense that they are "officially supported".

**Comment by cgewecke** [comment]
@yxliang01 Good idea!  Just added that to first line of the usage notes section: 4705bf81b787cfdb4e4d1e5a708f517d87ebc406

**Comment by yxliang01** [comment]
Nice one. So, I think it means all Truffle version v4.x.x and v5.x.x are supported? And, it's irrelevant to the version of `truffle` listed as dependency of solidity-coverage?

**Comment by cgewecke** [comment]
@yxliang01 Yes it's definitely not relevant to the Truffle here - that's just a dev dependency for our tests and periodically upgraded to make sure they're not breaking us. 

I *think* it works for all Truffle 4 that meets the solc requirement, but I'm not sure when the move up to 0.4.22 was exactly. . .

**Comment by yxliang01** [comment]
I see. But, let's say if we manually replace the `solc` in any version of `truffle` v4, @cgewecke you would expect that it works well?

**Comment by cgewecke** [comment]
@yxliang01 Yes, I think it should be ok. Just lmk if you run into trouble with that though, it's useful to know.

**Comment by yxliang01** [comment]
Great! Thanks a lot.
