### ISSUE TITLE
Upgrade to latest stable web3 version

### ISSUE THREAD

**Issue by BrendanChou** [sc-forks/solidity-coverage#369]
Currently 1.2.1 at time of writing

**Comment by cgewecke** [comment]
This is published in `0.6.5` - web3-eth-abi is still pinned at beta.55 - it has a different interface than the web3 1.x stable does. 

@BrendanChou Out of curiosity would dydx have any interest in trialing a beta for solidity-coverage 0.7.0? It's not published yet but am getting quite close. You should be able to pick any ganache version with it and will be faster as well. On the other hand it will be a beta and might have problems, idk. 

Happily open a PR for that at a repo of your choosing if you think it might be helpful. Also completely understand if you prefer not to be experimented on though :)

**Comment by BrendanChou** [comment]
Sure if there's a 0.7.0.beta I can try getting it to run

**Comment by cgewecke** [comment]
@BrendanChou Which repo(s) would you run it on? I'd like to make sure it installs and runs ok before publishing.

**Comment by BrendanChou** [comment]
https://github.com/dydxprotocol/solo

**Comment by cgewecke** [comment]
Closing this for housekeeping - will re-open if are still concerns about these deps though.

dydx/solo with 0.7.0 is being tracked #372.
