### ISSUE TITLE
Update pythereum to filter events

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#37]

**Comment by maurelian** [comment]
whoops, didn't mean to close this... 
but was going to say that I'm not sure how actively pythereum will be maintained in the future, so this might not be the highest impact activity right now.

**Comment by cgewecke** [comment]
@maurelian is it also your sense that gnosis is going to migrate its test suite to JS? It sort of looks like that but . . .

**Comment by maurelian** [comment]
As of yesterday they were thinking of it, so it's quite possible.

**Comment by maurelian** [comment]
Watch here for confirmation: https://github.com/gnosis/gnosis-contracts/pull/9#issuecomment-311955200

**Comment by cgewecke** [comment]
Ok sounds good. Closing. If anyone wants to pursue this further please feel free to re-open for discussion.
