### ISSUE TITLE
Use ganache-cli instead of ethereumjs-testrpc-sc

### ISSUE THREAD

**Issue by BrendanChou** [sc-forks/solidity-coverage#373]
Now that the `ethereumjs-testrpc-sc` package tracks `ganache-cli`, why not just move to the more canonical version with updates that are released faster?

**Comment by cgewecke** [comment]
> why not just move to the more canonical version with updates that are released faster

@BrendanChou Oh do you mean 'just use ganache-cli'? Or track their beta?

**Comment by BrendanChou** [comment]
Not their beta, but `ethereumjs-testrpc-sc` is the same repo now right? I think it just uses the exact code in the `ganache-cli` repo. Just the npm package seems to release updates slower (not talking about beta versions, just stable versions).

So I'm wondering can we just update `package.json` to use ganache-cli instead? That way we don't have to wait for new npm publishes of `ethereumjs-testrpc-sc` which sometimes lag by weeks.

Unless they are not really the same repo which in that case this issue can be closed

**Comment by cgewecke** [comment]
> So I'm wondering can we just update package.json to use ganache-cli instead? 

I wish this was possible but unfortunately testrpc-sc consumes a special fork of ethereumjs-vm (one of ganache's components) which logs the instrumentation solidity-coverage adds to the code. Hoping to remove this dependency in 0.7.0 FWIW. 

> That way we don't have to wait for new npm publishes of ethereumjs-testrpc-sc which sometimes lag by weeks.

Yes, this is bad and will try to track more closely. . . atm Truffle's [tests are failing](https://github.com/trufflesuite/truffle/pull/2296) with the newest ganache and am waiting a little bit to see what happens with that.

**Comment by BrendanChou** [comment]
Okay that makes sense, will close for now
