### ISSUE TITLE
Truffle test fail only with solidity-coverage

### ISSUE THREAD

**Issue by jklepatch** [sc-forks/solidity-coverage#416]
It's the second time this happen. And I dont see the common point.

Is it possible to skip the test phase of solidity-coverage or at least exclude some tests?

**Comment by cgewecke** [comment]
@jklepatch Have you tried the new beta version -`7.0.0-beta.2`? The tests might pass, and It also has a [way of skipping](https://github.com/sc-forks/solidity-coverage/blob/beta/docs/advanced.md#skipping-tests) tests easily.

There are new docs for 0.7.0 [here](https://github.com/sc-forks/solidity-coverage/tree/beta#install)
There is a guide to upgrading from 0.6.0 to 0.7.0 [here](https://github.com/sc-forks/solidity-coverage/blob/beta/docs/upgrade.md#upgrading-from-06x-to-070-betax)

If your project is public I can take a look and see why the test might be failing as well....

**Comment by jklepatch** [comment]
No I havent. What you linked is exactly what I need. I will just wait for the stable release.
My project is not public, but thanks for the help :)

**Comment by cgewecke** [comment]
@jklepatch No problem :)

I hope you don't mind but I'm going to close - there's nothing more we do here. (Because 0.7.0 involves quite substantial changes to how the project is installed, it will be a while before it leaves beta. )
