### ISSUE TITLE
Why force turning off solc optimizer in 0.7.0 beta?

### ISSUE THREAD

**Issue by boolafish** [sc-forks/solidity-coverage#417]
Hi, recently somehow I get a code that can only compile with optimizer on :sweat::sweat::sweat:

But anyway, just realized that during the coverage, it actually force flagging the using optimizer flag to false: https://github.com/sc-forks/solidity-coverage/blob/beta/dist/truffle.plugin.js#L92

Is there a reason to do so? Also, shall we also just keep in mind that the coverage would always be running without optimizer on?

**Comment by cgewecke** [comment]
@boolafish Yes, atm it always turns the optimizer off because it instruments the solidity by injecting small no-op statements which the optimizer might remove. 

Can you link to the code which only compiles w/ optimization on? Why does it not work when optimization is off?

**Comment by cgewecke** [comment]
https://github.com/omisego/plasma-contracts/pull/328/commits/90d88261d1f0822e28a6b2a30c7580364728e318

**Comment by boolafish** [comment]
Yeah, the above is the fix on our side.
If you're interested, I put a problem-ish branch on my fork: 

branch: [fail_with_optimizer_off](https://github.com/boolafish/plasma-contracts/tree/fail_with_optimizer_off)
latest commit with some observation of mine: [here](https://github.com/boolafish/plasma-contracts/commit/1b78d6ea4f268e777092fcca5828ea268b8ba45c)

**Comment by cgewecke** [comment]
@boolafish Ah that's really interesting thank you. 

I think the coverage tool should probably try to be clearer about what the compilation settings are in the docs and terminal output. There are probably more cases like this....

**Comment by alsco77** [comment]
fwiw, I also had this issue and was lucky to search through existing issues on here for an answer. It's a hard one to communicate to the user, but yeah I think just being clearer about what the compilation settings are is a step in the right direction. Not sure why my method execution fails when optimisation is disabled though :)

**Comment by cgewecke** [comment]
@alsoc77 Out of curiosity - what is your compilation error message? Is the code where youre seeing this public?

**Comment by cgewecke** [comment]
For context @boolafish's error is 
```
"Assembly exception for bytecode"
```
which looks like a internal solidity crash... I wonder if these incidents should be collected and reported to solc.

**Comment by alsco77** [comment]
My scenario is a bit tricky to disect. I did end up figuring out a solution though.
I have a ContractFactory that has a `createContract` func in which it deploys a new <child>, and there was an issue in the bytecode of the constructor of the child that was causing a revert. One of the libraries that was linked to this child was using an external contract that hadn't been deployed, rather than referencing an interface of this contract.
So the solution was to create a local interface for this external contract.
I suspect the optimizer was figuring out what part of the external contract it needed, then just slicing that bit off and putting it in, whereas an unoptimized compilation was attempting to do something else.
Anyway, thanks for this. Love the plugin -- really appreciate the Istanbul reporting, thanks @cgewecke

**Comment by hiddentao** [comment]
I'm using the [Diamond Standard](https://github.com/ethereum/EIPs/issues/2535) contracts. In order to compile them I need the optimizer on. But since solcover turns off the optimizer my contracts won't compile in coverage mode :/

**Comment by Ferparishuertas** [comment]
CompileError: CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.
With optimizer it works.
It's a bunch os dmart contract with AbiEncoderv2 using structs as params and return values

Any idea how to make coverage work?

**Comment by cgewecke** [comment]
@Ferparishuertas 

No, sorry. Thanks for reporting this. 

I think these cases should be raised at [ethereum/solidity][1] if it's possible to generate minimized reproductions for them.  It seems strange that optimization would affect whether or not compilation succeeds. 


[1]: https://github.com/ethereum/solidity

**Comment by Ferparishuertas** [comment]
Will definetly do it. Any contract over 24k, with Abiv2encoder raises this problem with optimizer=false

**Comment by AndonMitev** [comment]
So guys do you came up with any solution about the
`CompilerError: Stack too deep when compiling inline assembly: Variable value0 is 1 slot(s) too deep inside the stack.
` Error.
Yes I'm using optimizer ON on hardhat config settings, but not able to run my coverage, is there anyway to turn it on in the plugin as well?

**Comment by cgewecke** [comment]
@AndonMitev No, haven't found a solution. This is an open issue about this at [solidity 10354][1]. If I understand the maintainer's comments there correctly, this is a known limitation of the solidity compiler and AbiEncoderV2. 

Out of curiosity, which compiler version are you using? 

[1]: https://github.com/ethereum/solidity/issues/10354#issuecomment-745749729

**Comment by AndonMitev** [comment]
> @AndonMitev No, haven't found a solution. This is an open issue about this at [solidity 10354](https://github.com/ethereum/solidity/issues/10354#issuecomment-745749729). If I understand the maintainer's comments there correctly, this is a known limitation of the solidity compiler and AbiEncoderV2.
> 
> Out of curiosity, which compiler version are you using?
> 
> One resource you might look at it is the argentlabs `Filter for Paraswap V4` cross link just above in this thread. There's an explanation of how they restructured their contracts to get around this problem in that PR.

version: '0.7.3',

**Comment by abdulsamijay** [comment]
Hey all,
Have we found a solution or a work-around to this ? I cant get coverage to run as it does not compile with optimizer on. I am facing the same issue as @AndonMitev 
`CompilerError: Stack too deep when compiling inline assembly: Variable value0 is 1 slot(s) too deep inside the stack. Error.`

**Comment by JasoonS** [comment]
BTW, I got it fixed and working here: https://npmjs.com/package/@float-capital/solidity-coverage

Hopefully will be up-streamed soon #642 +1 You can test it in the interim.

Simply install the package and change the following in your hardhat.config.js:

```diff
-require("solidity-coverage");
+require("@float-capital/solidity-coverage");
```

**Comment by TheBlockchainAuditor** [comment]
> BTW, I got it fixed and working here: https://npmjs.com/package/@float-capital/solidity-coverage
> 
> Hopefully will be up-streamed soon #642 +1 You can test it in the interim.
> 
> Simply install the package and change the following in your hardhat.config.js:
> 
> ```diff
> -require("solidity-coverage");
> +require("@float-capital/solidity-coverage");
> ```

This worked for me but I had to set my hardfork to berlin!

Thanks JasoonS!!

**Comment by soccerarenadev** [comment]
> BTW, I got it fixed and working here: https://npmjs.com/package/@float-capital/solidity-coverage
> 
> Hopefully will be up-streamed soon #642 👍 You can test it in the interim.
> 
> Simply install the package and change the following in your hardhat.config.js:
> 
> ```diff
> -require("solidity-coverage");
> +require("@float-capital/solidity-coverage");
> ```

I'm having the same problem of stack too deep.
However, that package seems quite old. 
Is there no way to fix this from "sc-forks"?

**Comment by cgewecke** [comment]
Closing this for housekeeping. v0.8.7 now supports viaIR natively. While the optimizer is usually. turned off, if `viaIR` is enabled it allows optimization.
