### ISSUE TITLE
Error: TypeError: Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by steven-gong-artos** [sc-forks/solidity-coverage#432]
Hi, 
I'm using solidity coverage with the following version:

> truffle:           v5.1.0
> ganache-core:      v2.8.0
> solidity-coverage: v0.7.0-beta.2

And receives the following error message:
> Istanbul reports written to ./coverage/ and ./coverage.json
> solidity-coverage cleaning up, shutting down ganache server
Error: TypeError: Cannot read property 'files' of undefined
    at Object.run (~\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js?abc3:92:1)
Truffle v5.1.0 (core: 5.1.0)
Node v10.16.3

I am using the default values in .solcover.js file.

Is there anything I should customize to fix this issue from the default configs?

Thanks

**Comment by cgewecke** [comment]
@steven-gong-artos If you have a sec could you try using an earlier version of Truffle - maybe 5.0.41 - they just released 5.1.0 - maybe behavior has changed slightly.

Also, are you getting a coverage report? Is everything except for this final error working?

**Comment by cgewecke** [comment]
@steven-gong-artos 

Was able to run solidity-coverage with Truffle's MetaCoin project on 5.1.0 without any problems.

Do you have a reproduction case for this? Would be happy to look at it.

**Comment by cgewecke** [comment]
@steven-gong-artos 

Suspect this might be caused by something similar to [truffle 2419][1]. In that case, an empty folder in the test directory triggers the error. Underlying cause is the [node-dir][2] module which solidity-coverage uses for a similar purpose. 

[1]: https://github.com/trufflesuite/truffle/issues/2419
[2]: https://github.com/fshost/node-dir/issues/53

**Comment by steven-gong-artos** [comment]
Hi @cgewecke, 
I've tried truffle 5.0.41 and it returns the same Error.
The coverage report is generated, and only this final error causes confusion.

**Comment by cgewecke** [comment]
@steven-gong-artos 

I was able to reproduce your error by adding an empty folder to the migrations folder. Could you check that directory for an empty folder, remove it and see if this error goes away?

**Comment by cgewecke** [comment]
Fix published in [0.7.0-beta.3](https://github.com/sc-forks/solidity-coverage/releases/tag/v0.7.0-beta.3)

**Comment by steven-gong-artos** [comment]
Thanks, @cgewecke , 
You are right, migrations/coverage is generated to contain some empty folders.
Once this migrations/coverage folder is removed, this TypeError disappears.
