### ISSUE TITLE
installing anything with npm that has `solidity-coverage` as a dependency fails

### ISSUE THREAD

**Issue by pythonpete32** [sc-forks/solidity-coverage#442]
Installing anything with npm that has `solidity-coverage` as a dependency fails

I recently migrated to Debian 10. but anything that I try to install via npm with `solidity-coverage` fails with a very strange error

```
npm ERR! Unexpected end of JSON input while parsing near '...YCRA9TVsSAnZWagAA6sQP'
```

I'm using `NVM` with node`10.15.3` I have no idea why this is happening other than its related to `solidity-coverage` which is basically impossible to avoid. [here is a copy of my npm log](https://gist.github.com/pythonpete32/83e4842ee2cb5bf77ce6e797370c5f4c)

**Comment by cgewecke** [comment]
Hi @pythonpete32, thanks for reporting. 

Tbh I haven't seen this error before. Solidity-coverage installs and runs the zeppelin-solidity test suite on a linux machine [without problems in CI][1]. 

From your log it looks like the installation error comes from `handlebars@4.0.1` and the only thing I found about that suggested running:
```
npm cache clean --force
```

Another possibility is to try installing the new beta (0.7.x). There are instructions about how to do that at the top of the README.

[1]: https://circleci.com/gh/sc-forks/solidity-coverage/tree/master

**Comment by pythonpete32** [comment]
`npm cache clean --force` worked! thank you
