### ISSUE TITLE
Does not install correctly using yarn

### ISSUE THREAD

**Issue by area** [sc-forks/solidity-coverage#45]
Unlike `npm`, `yarn` does not install binaries of dependencies to `./node_modules/.bin` (see [here](https://github.com/yarnpkg/yarn/issues/760)). As a result when we try and run `testrpc-sc`, it fails. This could be fixed by executing `./node_modules/ethereumjs-testrpc-sc/bin/testrpc` rather than `./node_modules/.bin/testrpc-sc`. Alternatively, the onus could be on the use a tool like [yarn-bin-fix](https://www.npmjs.com/package/yarn-bin-fix).

**Comment by cgewecke** [comment]
Yes, changing the path here seems reasonable. As long as we're confident that ethereumjs-testrpc-sc will always get installed at that location in `node_modules` and not be nested somewhere weird. But it  *should* be right?

**Comment by cgewecke** [comment]
Published with 0.1.4.

**Comment by cgewecke** [comment]
An additional note here: Have removed the post-install hook from our solidity-parser fork following [Elena's observation](https://github.com/ConsenSys/solidity-parser/issues/77#issuecomment-311887744) that yarn dgafs that. So  changes there are now slightly more complicated - when we pull the upstream master we have to `npm run build` and push the build too. And I believe anyone using yarn has to run `yarn update solidity-coverage` to see it. 

If this new approach is mistaken please let me know.
