### ISSUE TITLE
Upgrade the ganache dependency to support istanbul

### ISSUE THREAD

**Issue by Amxx** [sc-forks/solidity-coverage#468]
My code contains calls to the `chainid()` oppcode introduced in Istanbul. I've added `hardfork: "istanbul"` to the providerOptions, but it appears that the ganache-code dependency is not recent enough and does not support it.

**Comment by cgewecke** [comment]
@Amxx 

In .solcover-js you can specify which ever ganache version you've installed as a local dependency. (By default SC will use the copy packed with the version of Truffle you're running.)

```javascript
module.exports = {
  client: require('ganache-cli'),
  providerOptions: {
    hardfork: "istanbul"
  }
}
```

Does that resolve the issue for you?

**Comment by Amxx** [comment]
Worked perfectly. Thanks a lot!
