### ISSUE TITLE
Transaction reverted executing address(this).balance

### ISSUE THREAD

**Issue by The-3D** [sc-forks/solidity-coverage#469]
For some reason, i'm getting a transaction revert while trying to fetch the balance of a contract. The same exact code works perfectly fine in our local ganache, kovan, ropsten, mainnet.

I need to change it to 

```
            address payable self = address(this);
            balance = self.balance;
```

which is not optimal as it forces me to change the code every time i want to run the coverage. Any hint on this?

**Comment by cgewecke** [comment]
Hi @The-3D.  

Do you have reproduction steps for this which include the exact code that needs to be changed, your solidity-coverage and ganache versions, and which plugin you're using (e.g. Truffle or Buidler)? 

When you run `ganache-cli --version` locally, does it report the same ganache-core version as that listed at the beginning of the solidity-coverage run? 

If not, you should explicitly set it via the `client` key in `.solcover.js` (See [options](https://github.com/sc-forks/solidity-coverage#config-options)).

**Example** 
```js 
module.exports = {
  client: require('ganache-cli'),
  providerOptions: {
    hardfork: "istanbul"
  }
}
```

**Comment by cgewecke** [comment]
Closing for house-keeping. Please just ping if you're still having difficulties with this.
