### ISSUE TITLE
Migrating Token not possible

### ISSUE THREAD

**Issue by skyeatshorizon** [sc-forks/solidity-coverage#472]
Hello I would like to migrate a ERC777 token to the chain. (using truffle)
When I use truffle test everything works fine and all test run without errors.
But when I use "coverage" I get the following message after compilation:
`Error: Error: Error: while migrating JoinToken: Returned error: VM Exception while processing transaction: revert
    at Object.run (/path/contract/node_modules/truffle/build/webpack:/packages/migrate/index.js?abc3:92:1)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Truffle v5.0.35 (core: 5.0.35)
Node v8.10.0`

I hope you can help me

**Comment by cgewecke** [comment]
@skyeatshorizon Apologies for the delay responding. 

If you put your project up on github and share a link I can take a look. 

Closing here because this doesn't look like a bug report atm.

**Comment by skyeatshorizon** [comment]
@cgewecke Thank you for offering to take a look. However can you first send me a mail. The project is large and I cannot share everything. mail: clockwise.inv@hotmail.com

**Comment by cgewecke** [comment]
Thanks for the link @skyeatshorizon, left some notes in your repo.

**Comment by azerpas** [comment]
Getting the same error. @cgewecke do you recall what was the issue?

**Comment by azerpas** [comment]
My migration was in fact the issue as the `ERC1820Registry` wasn't found in the `soliditycoverage` network. It just needed to be call with this network aswell.

Changes:
```diff
module.exports = async function (deployer, network, accounts) {
-   if (network === "development") {
+   if (network === "development" || network === "soliditycoverage") {
        // In a test environment an ERC777 token requires deploying an ERC1820 registry
        await singletons.ERC1820Registry(accounts[0]);
    }
```
