### ISSUE TITLE
Add a 0.6.X version that supports the istanbul hardfork

### ISSUE THREAD

**Issue by BrendanChou** [sc-forks/solidity-coverage#473]
For users who are still using 0.6.X, can you add a version that uses `ganache-cli` `v6.9.0` so that the Istanbul hardfork can be used?

**Comment by cgewecke** [comment]
Hi @BrendanChou!

I'd like to stop supporting 0.6.x. Are you trying to generate coverage for [dydx/solo][1]?  

I don't know if you've seen the [API docs][2] here but I'm hoping that it's +/- possible to write a short script using that and some of the helper utils for use-cases like yours. I'd be happy to help you do this and make any changes that are necessary to get it to work. 




[1]: https://github.com/dydxprotocol/solo
[2]: https://github.com/sc-forks/solidity-coverage/blob/master/docs/api.md

**Comment by BrendanChou** [comment]
Yeah, I couldn't really figure it out with 0.7.X, I figured it would be easiest to basically just update an npm package version and publish it as a new version for 0.6.X, although it's true that getting it to work with 0.7 may be more sustainable in the long term, it would be significantly more work up front

**Comment by cgewecke** [comment]
@BrendanChou Ok. Let me take a look at solo and see if I can get something to work. 

If not, we can consider the other option.

**Comment by BrendanChou** [comment]
Thanks, appreciate it

**Comment by cgewecke** [comment]
@BrendanChou My attempt is at [dydx/solo 398][1]. Please just lmk if you have questions or things seem wrong.

[1]: https://github.com/dydxprotocol/solo/pull/398

**Comment by BrendanChou** [comment]
Thanks! Will take a look today

**Comment by BrendanChou** [comment]
Great, thanks @cgewecke this is awesome, seems to work great! Currently copied the code onto my own PR so that it runs on our CI system, will clean up the linting and stuff a bit
