### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by gluxix** [sc-forks/solidity-coverage#475]
Hello!

Node 12 has a problem with [keccak](https://github.com/cryptocoinjs/keccak) package. This problem has been solved since 2.1.0 version. There are packages dependent on old version of keccak, e.g. ethereumjs-util under 6.2.0 version.

solidity-coverage requires "ganache-cli": "6.7.0" which requires ethereumjs-util@5. I'm going to create an issue to ganache-cli with this problem, but in this project ganache-cli version is set like exactly matched. Could you use ^version or ~version? When gahache-cli solves the problem, your package will automatically works fine with Node 12.

Thank you!

**Comment by gluxix** [comment]
I've created an [issue](https://github.com/trufflesuite/ganache-cli/issues/717) in genache-cli package.

**Comment by cgewecke** [comment]
@gluxix Could you go into further detail about what problems you're seeing with ganache? 

I've updated (but pinned) ganache-cli in #476 and also set the E2E tests to run using Node 12.16.0. Those tests are passing and installation succeeds.

I *can* float ganache but would like to understand what issue you're seeing exactly...

**Comment by cgewecke** [comment]
@gluxix I see ganache has published your patch in 6.9.1 [here][1]. 

Did you know you can use any ganache version you want by setting the client key in `.solcover.js`?

For example, if you install 6.9.1 in your project as a dev dep and use the coverage config below...

```js 
// .solcover.js
module.exports = {
  client: require('ganache-cli'),
  providerOptions: {
    ...
  }
}
```
...coverage should use `6.9.1`. Let me know if that's not the case:


[1]: https://github.com/trufflesuite/ganache-cli/releases/tag/v6.9.1

**Comment by gluxix** [comment]
@cgewecke Thanks for attention :) I'll check your recommendations on Monday. Also I'll provide npm log.

**Comment by cgewecke** [comment]
Closing, please just lmk if this is still an issue.
