### ISSUE TITLE
Unparse-able solc 0.6.x syntax

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#481]
Tracking issue for new solc syntax that [parser-diligence][1] still has difficulty with:

+ file scoped structs & enums #file
+ contract types and enums as keys for mappings
+ payable as function call: payable(address) 
+ `receive` when used as a function in 0.5.x ([eth-gas-reporter 196][2])
+ { value: ..., gas: ... } (solc >= 0.6.2) (#483)

[1]: https://github.com/ConsenSys/solidity-parser-antlr/issues
[2]: https://github.com/cgewecke/eth-gas-reporter/issues/196

**Comment by fvictorio** [comment]
Hi @cgewecke. I created a fork of consensys's fork (yeah, I know...) and I'm actively working on it, since I need an up to date version of the parser for solhint and prettier-solidity. Check it out if you are interested: https://github.com/solidity-parser/parser

Almost all the issues you listed will be solved soon. The third one, `payable as function call`, is the exception; I will open an issue for that.

**Comment by cgewecke** [comment]
Oh great! Thanks @fvictorio.

**Comment by gitpusha** [comment]
Hi I think the issue I created earlier today is probably also relevant here #493

**Comment by fvictorio** [comment]
Oh, yeah, it is! @gitpusha could you please open an issue [here](https://github.com/solidity-parser/parser)? Thanks!

**Comment by gitpusha** [comment]
Hi @fvictorio . I will open an issue there. thanks!

**Comment by fvictorio** [comment]
@cgewecke `@solidity-parser/parser@0.5.1` should have all these issues fixed, I think, in case you want to give it a try.

**Comment by fvictorio** [comment]
(Except the one that @gitpusha created, sorry, didn't notice it was added to this list)

**Comment by cgewecke** [comment]
> Except the one that @gitpusha created, sorry, didn't notice it was added to this list

Ah sorry! I didn't get a chance yesterday to test that one out...

@fvictorio Fantastic. Thanks so much for doing all this, just amazing. 🎉 🎉

**Comment by fvictorio** [comment]
FYI I just ran the parser in all OpenZeppelin's contracts and, at least, there weren't any errors.

**Comment by cgewecke** [comment]
`0.7.4`

Thanks again @fvictorio!
