### ISSUE TITLE
"unresolved libraries" error in Truffle migrations

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#482]
Opening and closing in case someone runs into this...

At [synthetix 452][1], libraries were not linking as expected. Their migrations fn looked like:
```js
module.export = async function(deployer, network, accounts){
  await deployer.deploy(LibA)

  deployer.link(LibA, ContractA); // Needs to be awaited
  await deployer.deploy(ContractA); 

  ...
}
```
For unknowns reasons when Truffle runs this in the plugin context the link method (which is technically async) needs to be awaited, otherwise there's a race-condition failure. Basically, this fixes...

```js
await deployer.link(LibA, ContractA)
```

[1]: https://github.com/Synthetixio/synthetix/pull/452#issuecomment-596106873

**Comment by Destiner** [comment]
Error message to make this searchable:
```
Error: while migrating X: X contains unresolved libraries. You must deploy and link the following libraries before you can deploy a new version of X: A, B, C
```
