### ISSUE TITLE
{value: ...} syntax needs support

### ISSUE THREAD

**Issue by KaiRo-at** [sc-forks/solidity-coverage#483]
See https://github.com/ethereum/solidity/releases/tag/v0.6.4
`General: Deprecated value(...) and gas(...) in favor of {value: ...} and {gas: ...}`

That syntax currently causes failures to run solidity-coverage (using 0.7.2).

**Comment by cgewecke** [comment]
Thanks @KaiRo-at, I will add this to the growing list in #481.  

It's also being tracked in [solidity-parser-diligence 14](https://github.com/ConsenSys/solidity-parser-antlr/issues/14)

**Comment by cgewecke** [comment]
Should be fixed with `0.7.4`.
