### ISSUE TITLE
Buidler fails on api initialization

### ISSUE THREAD

**Issue by maxsam4** [sc-forks/solidity-coverage#489]
Since I upgraded `builder` to version `1.3.0-rc.0`, coverage has stopped working with the following error:
`Error BDLR301: Invalid value null for argument testfiles of type string`

Seems like buidler no longer accepts null values for `--testfiles`, `--solcoverjs` and `--temp` which seems to be the default ones used by solidity-coverage.

**Comment by cgewecke** [comment]
@maxsam4 Thanks for reporting. What was the last version you were using that worked?

**Comment by justinjmoses** [comment]
It worked on `1.2.0`

**Comment by cgewecke** [comment]
@maxsam4 Fixed this in #490, will publish this am...

**Comment by cgewecke** [comment]
Should be resolved with `0.7.3`, please just ping if you're still seeing any problems with the cli options (or any other Buidler stuff)
