### ISSUE TITLE
Error: sender doesn't have enough funds to send tx. The upfront cost is: 1000000000000045452 and the sender's account only has: 999999999944771288

### ISSUE THREAD

**Issue by gitpusha** [sc-forks/solidity-coverage#503]
Hi,

Env:
```
    "@nomiclabs/buidler": "1.2.0",
    "@nomiclabs/buidler-ethers": "1.2.0",
    "@nomiclabs/buidler-waffle": "1.2.0",
    "chai": "^4.2.0",
    "coveralls": "^3.1.0",
    "ethereum-waffle": "2.4.1",
    "ethers": "4.0.47",
    "solc": "^0.6.6",
    "solidity-coverage": "https://github.com/sc-forks/solidity-coverage.git",
```

`usePlugin("solidity-coverage");`
```
coverage: {
      url: "http://127.0.0.1:8555",
    },
```
**Just now my coverage stopped working with this error:**
```
  1) "before each" hook for "Should let the owner transferOwnership":
     Error: sender doesn't have enough funds to send tx. The upfront cost is: 1000000000000045452 and the sender's account only has: 999999999944771288
      at HttpProvider.send (node_modules/@nomiclabs/buidler/src/internal/core/providers/http.ts:36:34)
      at /Users/luis/Desktop/gelato-V1/node_modules/@nomiclabs/buidler/src/internal/core/providers/accounts.ts:219:21
      at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
      at /Users/luis/Desktop/gelato-V1/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:23:21
      at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
      at /Users/luis/Desktop/gelato-V1/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:41:21
      at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/buidler-ethers/src/ethers-provider-wrapper.ts:13:48)
      at /Users/luis/Desktop/gelato-V1/node_modules/ethers/providers/json-rpc-provider.js:127:35
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Context.<anonymous> (test/gelato_core/core/GelatoCore.exec.test.js:142:3)
```

The weird thing is the **all** **tests** **pass** on **buidlerevm** with `npx buidler test`.

The error only creeps up when I run `npx buidler coverage --network coverage`.

Another weird thing:
I did not change the `"Should let the owner transferOwnership":` test. 

I am using the exotic version of `solidity-coverage` ("solidity-coverage": "https://github.com/sc-forks/solidity-coverage.git") though.

I assume this bug appears during a contract deployment. But it's hard to tell where it's thrown because the stack trace says:
` at Context.<anonymous> (test/gelato_core/core/GelatoCore.exec.test.js:142:3)`

but the Error says this

`  1) "before each" hook for "Should let the owner transferOwnership":`

These are two completely separate test files.

**@cgewecke do you have any idea what I can do to fix it?**

**Comment by gitpusha** [comment]
I am closing because this bug was caused by my own mistake.

I accidentally removed the outermost `describe` block wrapping the first `beforeEach`.

However, it was still confusing that the `npx buidler test` command worked and the `coverage` one did not.  I assume this must be due to differences between ganache and buidlerevm speed?

**Comment by cgewecke** [comment]
Ha ha I was just responding, did you get this to work?

**Comment by cgewecke** [comment]
> I assume this must be due to differences between ganache and buidlerevm speed

Yes, that's possible.

**Comment by gitpusha** [comment]
You are very quick to respond. I am happy I could spare you some trouble. 

I just configured our CI with coveralls and it's pretty cool. I can't wait for the buidler-gas-reporter codechecks to work too!

**Comment by cgewecke** [comment]
@gitpusha Yes, will try to figure out what's wrong with buidler-gas-reporter and patch today. (Sorry about that.)

**Comment by gitpusha** [comment]
Thanks! don't worry!


Coveralls work on our CI again. Thanks for your tools!
![Uploading image.png…]()

**Comment by PaulRBerg** [comment]
I'm getting the same issue and I double-checked that I have no bogus `beforeEach` hook. This is the issue:

> Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.

The catch is that the contract code size does **not** exceed the limit of 24,576 bytes when not running the coverage script. Likely what happens is that solidity-coverage bumps the bytecode size beyond the limit because it adds its instrumenting logic.

@cgewecke should I open a separate issue for this? A clearer error message would be nice.

**Comment by PaulRBerg** [comment]
FWIW, this is the said contract:

https://github.com/MainframeHQ/mainframe-lending-protocol/blob/ca556c36463615fb9661e71881df1466c8eb6461/contracts/YToken.sol

Yet another reason why I should start stubbing contracts in my tests instead of deploying the canonical versions.

**Comment by cgewecke** [comment]
@PaulRBerg 

The size limit should not be an issue - it's [disabled by default][1] when solidity-coverage launches ganache. 

Does this resolve if you fund ganache accounts with a larger balance in `.solcover.js` providerOptions, e.g
```js
module.exports = {
  providerOptions: {
      default_balance_ether: 100000000,
  }
};
```

[1]: https://github.com/sc-forks/solidity-coverage/blob/db1f2f5c105e09b8567bf2bfba9ff38243d747af/lib/api.js#L153-L156

**Comment by PaulRBerg** [comment]
That fixed it. Thank you!
