### ISSUE TITLE
Error while parsing assembly

### ISSUE THREAD

**Issue by prashantprabhakar** [sc-forks/solidity-coverage#505]
The smart contract function passes in truffle tests but fails with truffle coverage.

`function getChainID() public pure returns (uint256 id) {
        assembly {
            id := chainid()
        }
    }`

I read a related issue [here](https://github.com/sc-forks/solidity-coverage/issues/425).  So adding `let` before id does not give coverage error but of course, returns 0 in the contract which is not intended. 

This function works for coverage too but gives incorrect result.

`function getChainID() public pure returns (uint256 id) {
        assembly {
            let id := chainid()
        }
    }`

Solidity-coverage version: 0.7.5

**Comment by cgewecke** [comment]
This should be ok now
