### ISSUE TITLE
Runtime Error parsing beforeEach when using buidler-deploy plugin

### ISSUE THREAD

**Issue by travisdmathis** [sc-forks/solidity-coverage#506]
Compiler: 0.6.6
Coverage: 0.7.5

```
1) PanDAO Contract Network
       "before each" hook:
     Uncaught RuntimeError: abort(Error: Method [object Object] not supported.). Build with -s ASSERTIONS=1 for more info.
      at process.abort (.coverage_cache/compilers/soljson-v0.6.6+commit.6c089d02.js:1:14382)
      at process.emit (node_modules/@nomiclabs/buidler/node_modules/source-map-support/source-map-support.js:495:21)
      at process.emit (node_modules/ganache-cli/node_modules/source-map-support/source-map-support.js:465:21)
      at process.object.process.function.process.on.process.emit (node_modules/ganache-cli/build/ganache-core.node.cli.js:37:31967)
      at process.emit (node_modules/source-map-support/source-map-support.js:465:21)
      at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
      at process._tickCallback (internal/process/next_tick.js:69:34)
```

```
beforeEach(async () => {
    [agent, address1, address2] = await bre.getSigners();

    await deployments.fixture();

    // setup needed contracts
    Manager = await deployments.get("Manager");
    manager = new ethers.Contract(Manager.address, Manager.abi, agent);

    EternalStorage = await deployments.get("EternalStorage");
    eternalStorage = new ethers.Contract(
      EternalStorage.address,
      EternalStorage.abi,
      agent
    );

    MockToken = await bre.getContractFactory("Token");
    mockToken = await MockToken.deploy();
    await mockToken.deployed();
  });
```

Tests pass
```
All contracts have already been compiled, skipping compilation.


  PanDAO Contract Network
    Manager Contract
      ✓ Manager is stored in EternalStorage
      ✓ Can get contract address by contract name
      ✓ Agent owns deployed Manager contract
      ✓ Can create an Insurance Pool if it doesn't exist (442ms)
      ✓ Fails to create Insurance Pool if it already exists (269ms)
      ✓ Fails to create an Insurance Pool if not Agent


  6 passing (2s)
```

**Comment by cgewecke** [comment]
Hi @travisdmathis, thanks for reporting. Was able to reproduce with pandao-bamboo.

Just looked at this quickly and it's failing within `deployments.fixture`. Seems like an interaction bug between the builder-deploy plugin and solidity-coverage. Will investigate...

**Comment by travisdmathis** [comment]
@cgewecke that's the conclusion I came to as well, but because it was getting swallowed was hard to be sure.

**Comment by travisdmathis** [comment]
@cgewecke the buidler-deploy guys found the issue

https://github.com/wighawag/buidler-deploy-ts-test/commit/f3c8bd74cc5f17fe6648b163897c34dd8990bda0

From @wighawag

this can be fixed using this workaround :  https://github.com/wighawag/buidler-deploy-ts-test/commit/f3c8bd74cc5f17fe6648b163897c34dd8990bda0
the problem is basically that ethers expect a sendAsync function to be present. 
buidler will fix that in a future version with a provider compatibility layer

But for now, plugin need to handle that and currently buidler-deploy assume the provider is set at the get-go. unfortunately solidity-coverage create a new provider and thus do not get the extra sendAsync added

the fix I did is doing it on teh test by importing a module that perform the fix, so this is a workaround and there might be ways to fix it in buidler-ethers-v5 instead. Did not have time to look into it more

**Comment by cgewecke** [comment]
@travisdmathis Ok cool, that's great. Are you seeing the report you expect etc with that patch?

**Comment by travisdmathis** [comment]
@cgewecke this issue is resolved completely w/ latest version of buidler-deploy/0.6.10 solc

**Comment by cgewecke** [comment]
@travisdmathis Great! Thanks so much. Will close then.
