### ISSUE TITLE
Use custom ganache-cli configuration

### ISSUE THREAD

**Issue by chrsengel** [sc-forks/solidity-coverage#509]
As my contract suite is using multiple defi protocols I need to use a mainnet fork that unlocks a couple of addresses. For that I use ganache-cli with these of options.

```javascript
ganache-cli -f \"http://localhost:8545\" -p \"8547\" -m \"...\" -l 8000000 -a 20 -e 10000 -i 1 -u ... -u ...
```

My `truffle-config.js` then uses this network config with the corresponding port.

```javascript
// version 5.1.28
networks: {
    development: {
      host: "127.0.0.1",
      port: 8547,
      network_id: "*",
      networkCheckTimeout: 50000,
    },
  },
```

I can't figure out how to use solidity-coverage with these options. If I run it with `--network development` it obviously starts its own testrpc network. But that won't work for me as I explained. I haven't found any info on this in the docs or previous issues.

Is there any way I can use this tool with my own mainnet fork?

**Comment by cgewecke** [comment]
solidity-coverage needs to launch ganache itself so it can hook into the evm and track execution. You can use any ganache version and set options for it in `.solcover.js` `providerOptions`:

```js
module.exports = {
  client: require('ganache-cli'),
  providerOptions: {
    ....
  }
  ...
}
```

The options keys are in the format described for [ganache-core][1]. They're slightly different than those used for the cli command flags.

You can set which network the tool should use it via the network flag. For the Truffle plugin this would look like:
```
truffle run coverage --network <network-name>
```

[1]: https://github.com/trufflesuite/ganache-core#options

**Comment by chrsengel** [comment]
Thanks I missed the core options section. That seems to at least start it. Now I'm getting tons of these TypeErrors:

```bash
/home/chris/dethlify/contract/.coverage_contracts/Premium.sol:109:1: Overriding function is here:
function coverage_0x325c31b1(bytes32 c__0x325c31b1) public pure {}
^----------------------------------------------------------------^
,/home/chris/dethlify/contract/.coverage_contracts/Premium.sol:109:1: TypeError: Function needs to specify overridden contracts "BaseHeader" and "BaseState".
function coverage_0x325c31b1(bytes32 c__0x325c31b1) public pure {}
^----------------------------------------------------------------^
```

Not sure what's going on here.

**Comment by cgewecke** [comment]
@chrsengel 

+ What compiler version are you using? 
+ If it's the v 0.6.x range, could you see if using a lower patch version resolves this?
+ Could you show the `Premium.sol` file or another Solidity file which results in the same error?

**Comment by cgewecke** [comment]
@chrsengel 

If you have multiple contracts defined in `Premium.sol` which inherit from each other, you might be able to work around the compilation problem by putting each contract in its own file. 

(Just saw that the code here might not handle that case very well...)

**Comment by chrsengel** [comment]
Oh yes that was the problem. I put all contracts in separate files and it works. Thanks a lot for your help!
