### ISSUE TITLE
[Buidler plugin] Load ganache lazily

### ISSUE THREAD

**Issue by alcuadrado** [sc-forks/solidity-coverage#514]
Hey @cgewecke,

We had a bug report on Buidler about ts line numbers being wrong when a test failed. After debugging it, I figure out that removing `solidity-coverage` from their plugin fixed it.

The reason for this is that the plugin always loads `ganache-cli`, which breaks the source maps. [Something similar happens to `waffle`](https://github.com/EthWorks/Waffle/issues/281).

Can you refactor the plugin so that it only loads Ganache right before using it? This is probably a two-line change, but I'm not familiar at all with the plugin.

Thanks!

**Comment by cgewecke** [comment]
`0.7.7`
