### ISSUE TITLE
Try / Catch in solidity v6 treated as single line.

### ISSUE THREAD

**Issue by moose-code** [sc-forks/solidity-coverage#520]
When creating a solidity coverage report, the try and catch are not treated as separate branches of execution (like and if and else I guess). This can be misleading as a '100% coverage' can be given even if the catch part is never executed. 

<img width="434" alt="Screenshot 2020-06-15 at 19 46 07" src="https://user-images.githubusercontent.com/20556729/84689174-dedcc700-af40-11ea-975f-65b87854a6c4.png">

Thanks in advance for taking a look :)

**Comment by cgewecke** [comment]
`0.7.8`
