### ISSUE TITLE
builder / waffle / solidity coverage does not set block gas limit

### ISSUE THREAD

**Issue by NoahMarconi** [sc-forks/solidity-coverage#521]
Trying to migrate our repo to `builder` with `solidity-coverage` and can't seem to get the block gas limit to increase. 

Here is the branch:
https://github.com/NoahMarconi/grant-contracts/tree/chore/builder

Reproduce error:
```
npm i
npm run coverage
```

# Expected result

I added some `console.log`ing to the tests files and the block limit is expected to match the block limit in the config files:

https://github.com/NoahMarconi/grant-contracts/blob/chore/builder/.solcover.js
or
https://github.com/NoahMarconi/grant-contracts/blob/chore/builder/buidler.config.ts#L17 

# Actual Result

Tests fail due to exceeding block gas limit and logged gas limit shows default (not a match to config):

```
{
  hash: '0xa3140b6198675adcc8756dbefa3a941cebcbe22765420febd1a883527c31b199',
  parentHash: '0xb01b4d31243fe2e78059bdaa74b9fbcca16694a2e0e5b3f76fe93dfe31a5a767',
  number: 2,
  timestamp: 1592317651,
  nonce: '0x0000000000000000',
  difficulty: 0,
  gasLimit: BigNumber { _hex: '0x6691b7' },
  gasUsed: BigNumber { _hex: '0x0' },
  miner: '0x0000000000000000000000000000000000000000',
  extraData: '0x',
  transactions: []
}
```

**Comment by cgewecke** [comment]
@NoahMarconi Could you try without configuring the gas in the network? Coverage should be able auto-set the correct settings itself.

**Comment by NoahMarconi** [comment]
Thanks @cgewecke I had some help debugging from @alcuadrado and determined the problem was definitely user error. I was using waffle in my tests instead of `bre.waffle.provider`.

I'm all set now
