### ISSUE TITLE
Running buidler plugin with --testfiles glob

### ISSUE THREAD

**Issue by alsco77** [sc-forks/solidity-coverage#524]
X-post from `buidler` > https://github.com/nomiclabs/buidler/issues/665

Running `yarn buidler coverage --network coverage --solcoverjs ./.solcover.js --testfiles test/**/Test*.ts --show-stack-traces` results in the following output (even after `0.7.9`):

`Error BDLR308: Unrecognized positional argument test/governance/TestDelayedClaimableGovernor.spec.`

**Comment by cgewecke** [comment]
@alsco77 

Thanks for debugging ... as you note in the corresponding Buidler issue the globs need to be enclosed in quotes at the command line. 

Will update the docs.

**Comment by cgewecke** [comment]
Docs (both README and BUIDLER_README) are updated.

Thanks again!
