### ISSUE TITLE
Buidler tests pass but coverage fails with Error: VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by Michael-A-Heuer** [sc-forks/solidity-coverage#525]
The output can be found here:
https://travis-ci.com/github/ArborVote/ArborVote/builds/174095899
Am I doing something wrong here?

**Comment by cgewecke** [comment]
@Michael-A-Heuer

Hi, tbh I am not completely certain what's going on. 

Inserting time delays in the `vote` and `finalizeLeaves` tests after the `updateStage` step got the tests to pass. I see some `now` dependent logic in your contract...suspect BuidlerEVM and ganache are managing time differently and there might be a logic problem with the way `updateStage` and `advanceStage` interact.

Both clients support the same [RPC endpoints for programmatically advancing time][1] ...using those is a common way of testing code w/ time-based logic fwiw. 

[1]: https://buidler.dev/buidler-evm/#special-testing-debugging-methods

Added delays like this:
```js
it("should change the number of votes and vote tokens left.", async function() {
    await arborVote.advanceStage();
    expect(await arborVote.getStage()).to.equal(2);

    // vote on arg 1
    expect(await arborVote.getVotes(1)).to.equal(0);
    await new Promise(resolve => setTimeout(() => resolve(), 5000)) //<-- new
    await arborVote.voteFor(1, 2);
    ... etc...

it("should finalize the arguments.", async function() {
    await arborVote.advanceStage();
    expect(await arborVote.getStage()).to.equal(3);

    await new Promise(resolve => setTimeout(() => resolve(), 5000)) // <-- New
    await arborVote.finalizeLeaves();
```

Got this....

![Screen Shot 2020-07-02 at 1 48 48 PM](https://user-images.githubusercontent.com/7332026/86407955-e3a4b900-bc6a-11ea-9886-0f73222d6b55.png)

**Comment by Michael-A-Heuer** [comment]
Thank you very much for your help. It was like you said, but I don't fully understand what goes wrong as well.
Somehow, the `updateStage()` method reverted to an older stage during the tests, which can only happen if `now` has a smaller value at some later point in time (unless I am completely overlooking something). Strange.
I prevented this now, so that time delays aren't necessary.
