### ISSUE TITLE
Throw BuidlerPluginError instead of Error

### ISSUE THREAD

**Issue by fvictorio** [sc-forks/solidity-coverage#527]
Instead of:

```javascript
    if (process.exitCode > 0) throw new Error(ui.generate('tests-fail', [process.exitCode]));
```

consider doing

```javascript
    if (process.exitCode > 0) throw new BuidlerPluginError('solidity-coverage', ui.generate('tests-fail', [process.exitCode]));
```

Relevant section in the docs: https://buidler.dev/advanced/building-plugins.html#throwing-errors-from-your-plugins

**Comment by cgewecke** [comment]
This is fixed for the Hardhat plugin in `0.7.12`. Thanks for highlighting @fvictorio!
