### ISSUE TITLE
Crashes on new solidity 0.7.0 syntax

### ISSUE THREAD

**Issue by junderw** [sc-forks/solidity-coverage#528]
Depends on:
https://github.com/solidity-parser/parser/pull/24
https://github.com/solidity-parser/parser/issues/23

Related:
https://github.com/prettier-solidity/prettier-plugin-solidity/issues/310
https://github.com/protofire/solhint/issues/240

0.7.0 now forbids "public" or "internal" on constructors.

parser was throwing an error on the new syntax

**Comment by junderw** [comment]
@solidity-parser/parser just released v0.7.0 with a fix.

**Comment by junderw** [comment]
made PR #529

**Comment by cgewecke** [comment]
Thanks @junderw, fixed published with `0.7.10`
