### ISSUE TITLE
npx testrpc-sc 

### ISSUE THREAD

**Issue by fabianorodrigo** [sc-forks/solidity-coverage#532]
Hi guys,

I took an exception in a specific project when trying to execute solidity-coverage: npm ERR! 404 Not Found: testrpc-sc@latest
This project: https://github.com/fabianorodrigo/linha-financiamento-dapp

I'm taking a look at solidity-coverage@0.6.7 and I found this 'npx testrpc-sc' in the app.js below.
Actually this project doesn't exist in npmjs.com ... but solidity-coverage@0.6.7 works fine for other projects. Do you have a clue about it?

`
        this.testrpcProcess = childprocess.exec(
          `npx testrpc-sc ${options}`,
          execOpts,
`

**Comment by cgewecke** [comment]
Closing, testrpc-sc is part of 0.6.x and no longer receives code updates.
