### ISSUE TITLE
Tests Timeout

### ISSUE THREAD

**Issue by Anyhowclick** [sc-forks/solidity-coverage#533]
Hello, is there a way to increase the default server timeout for tests?

I'm getting some failing tests for sol4 coverage in this repo because the default 20000ms is exceeded:
https://github.com/KyberNetwork/kyber_reserves_sc/tree/develop

I tried this futile solution...
https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-out-of-time

**Steps to reproduce**
- clone the repo
- `yarn install`
- `yarn coverage4`

Any help would be appreciated! =)

**Comment by cgewecke** [comment]
@Anyhowclick 

It's possible to [set mocha options in `.solcover.js`][1]. Does configuring a higher `timeout` value that way help at all?  

cf: [mocha api options][2]


[1]:  https://github.com/sc-forks/solidity-coverage/blob/master/docs/advanced.md#skipping-tests
[2]:  https://mochajs.org/api/mocha

**Comment by Anyhowclick** [comment]
Ahhhhh damn it, not sure why I didn't try that. Thanks for the tip!

**Comment by cgewecke** [comment]
Oh good! Will update the docs with that solution..
