### ISSUE TITLE
Incorrect option example in README

### ISSUE THREAD

**Issue by chanhosuh** [sc-forks/solidity-coverage#534]
The readme is inconsistent with the usage of "=" with long options.  The readme gives the following example:
```
--testfiles="test/registry/*.ts"
```

Problem is, you'll get a `Error BDLR305: Unrecognized param` if you try using "=".  You have to do `--testfiles "test/registry/*.ts"` like in the other examples (except for `--file`, which I assume would fail).

**Comment by cgewecke** [comment]
Fixed this in `0.7.11`... thanks for reporting @chanhosuh!
