### ISSUE TITLE
Report shows 0% test coverage when there are running tests

### ISSUE THREAD

**Issue by jensendarren** [sc-forks/solidity-coverage#536]
I have a project where I would like to check test coverage for the Solidity Smart Contracts. I am using solidity-coverage via a buidler plugin and the test coverage is always 0%. The output from the tool appears to be perfectly fine, but the report yields no useful information since there are tests running for the Smart Contracts but the report returns the test coverage is 0%.

This project uses @openzeppelin/cli with Buidler and is *not* using Truffle.

Below are the config files and versions that I using (package.json):

```
"devDependencies": {
  "@nomiclabs/buidler": "^1.4.7",
  "@openzeppelin/test-environment": "^0.1.4",
  "chai": "^4.2.0",
  "ganache-cli": "^6.10.1",
  "mocha": "^8.1.3",
  "solidity-coverage": "^0.7.10"
}
```

The buidler.config.js file is as follows:

```
usePlugin('solidity-coverage')

module.exports = {
  solc: {
    version: "0.6.2"
  },
  networks: {
    coverage: {
      url: 'http://localhost:8555'
    }
  },
}
```

When I run the command:

`npx buidler coverage --network coverage`

I see the following (some content removed for brevity):

```
> server:            http://127.0.0.1:8555
> ganache-core:      v2.10.1
> solidity-coverage: v0.7.10

Network Info
============
> port:    8555
> network: coverage

Instrumenting for coverage...
=============================
Contract1.sol
Compiling...

Compiled 1 contract successfully
All contracts have already been compiled, skipping compilation.

...tests run here...

31 passing (10s)

------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
 Contract1.sol          |        0 |        0 |        0 |        0 |                |
------------------------|----------|----------|----------|----------|----------------|
All files               |        0 |        0 |        0 |        0 |                |
------------------------|----------|----------|----------|----------|----------------|
```

As can be seen from the output above, everything compiles, test run (and pass) but the report concludes there is 0% test coverage (but this number should be much higher since there are tests).

Any help would be greatly appreciated!

**Comment by cgewecke** [comment]
@jensendarren 

Could you try adding the flag `--temp artifacts` to your command? This will save the instrumented contracts to the `artifacts` folder and is useful if you have hardcoded paths to artifacts in your tests. (NB: it treats that folder as disposable and will delete it after the command).

If that doesn't work, could you send me a link to your project so I can debug further?

**Comment by jensendarren** [comment]
Hi @cgewecke many thanks for your suggestion. 

OpenZeppelin places build artifacts in the `build/contracts` folder so I tried updating the command to:

```
npx buidler coverage --temp 'build/contracts' --network coverage
```

Which results in an 'out of gas' error for all the tests (normally they all pass):

```
VM Exception while processing transaction: out of gas
```

So it now appears that the VM is not starting up with the expected settings for gas. Is there something else that I am missing perhaps in the config (shared above)?

Many thanks!

**Comment by cgewecke** [comment]
@jensendarren 

Normally solidity-coverage sets the client and provider gas levels at appropriately high levels...

I think it's possible this error comes from some kind of interaction of with the openzeppelin tools. 

`oz/test-environment` has written it's own script for running solidity-coverage:
+ [script][1]
+ [example usage as openzeppeliin-contract][2]

I don't know how this combines with Buidler though...you might need to make a small reproduction case of the error on Github for me to be able to debug further.

[1]: https://github.com/OpenZeppelin/openzeppelin-test-environment/blob/master/src/coverage.ts
[2]: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/scripts/coverage.js

**Comment by jensendarren** [comment]
HI @cgewecke - many thanks for sharing this! The example usage script you linked to from the OZ team in your previous comment works! Thank you!

**Comment by cgewecke** [comment]
Ok great! I will add something in the README about how to use their tools then. 

Closing.
