### ISSUE TITLE
Report showing 0% test coverage & unable to find contract artifact  

### ISSUE THREAD

**Issue by mfahampshire** [sc-forks/solidity-coverage#537]
This issue is similar to #536 but there are some differences and additional issues hence submitting it as its own issue. 

I am trying to check coverage for a smart contract which is a proxy atop imported contracts. Unfortunately the test coverage is always 0%, even though I have javascript tests in my `test` directory. I do get some output but then the coverage fails with an error. 

I am using `Truffle v5.1.45 (core: 5.1.45)`. Config files and versions below: 

- `package.json`
``` 
},
  "devDependencies": {
    "eslint": "^7.9.0",
    "solidity-coverage": "^0.7.9"
  }
```

- `.solcover.js`
```
module.exports = {
  skipFiles: ['test/Import.sol', 'test/ERC20Mock', 'interfaces/IContract1.sol', 'IContract2.sol'],
  providerOptions: {
    gasLimit: 0x1fffffffffffff,
    allowUnlimitedContractSize: true,
    default_balance_ether: 0x1fffffffffffff,
  }
};

```

- `truffle-config.js`
```
module.exports = {
  networks: {
      coverage: {
        gas: 0x1fffffffffffff,
        host: '127.0.0.1',
        port: 8555,
        network_id: "*",
      }
  },
  plugins: ["solidity-coverage"],
  compilers: {
    solc: {
      version: "0.5.13",
      //docker: true,
      settings: {
        optimizer: {
          enabled: true,
          runs: 200
        },
      }
    }
  }
};

```

Command being run is `truffle run coverage --solcoverjs ./.solcover.js --network coverage`, with the follow as a response (edited for brevity): 

```
> truffle run coverage --solcoverjs ./.solcover.js --network coverage


> Using Truffle library from local node_modules.

> server:            http://127.0.0.1:8555
> truffle:           v5.1.47
> ganache-core:      v2.11.2
> solidity-coverage: v0.7.9

Network Info
============
> id:      *
> port:    8555
> network: coverage


Instrumenting for coverage...
=============================

> Contract1.sol
> interfaces/IContract2.sol

[ ... contracts compile here ... ] 

> Compiled successfully using:
   - solc: 0.5.13+commit.5b0b510c.Emscripten.clang


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

------------------------------|----------|----------|----------|----------|----------------|
File                          |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------------|----------|----------|----------|----------|----------------|
 contracts/                   |        0 |        0 |        0 |        0 |                |
  Contract1.sol           |        0 |        0 |        0 |        0 |... 346,347,348 |
 contracts/interfaces/        |      100 |      100 |      100 |      100 |                |
  IContract2.sol |      100 |      100 |      100 |      100 |                |
------------------------------|----------|----------|----------|----------|----------------|
All files                     |        0 |        0 |        0 |        0 |                |
------------------------------|----------|----------|----------|----------|----------------|

> Istanbul reports written to ./coverage/ and ./coverage.json
> solidity-coverage cleaning up, shutting down ganache server
/home/path/to/repo/packages/contracts/node_modules/truffle/build/library.bundled.js:350276
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^

Error: Could not find artifacts for Contract 4 from any sources

```

The additional issue is that `Contract 4` exists in my build folder alongside all the other ABIs of contracts that I am using but is not found. 

Any advice or help would be much appreciated. Thanks!

**Comment by cgewecke** [comment]
Could you try adding the flag `--temp build` to your command? This will save the instrumented contracts to the artifacts folder and is useful if you have hardcoded paths to artifacts in your tests. (NB: it treats that folder as disposable and will delete it after the command).

If not could could you link to your project so I can debug further?

**Comment by mfahampshire** [comment]
Added `--temp build` so the entire command was `truffle run coverage --solcoverjs ./.solcover.js --network coverage --temp build` but unfortunately that didn't work. 

Thank you for the offer of debugging! The project is currently being developed as a private repo but we would be happy to give you access for the debugging - could we switch to email / telegram / another communication channel to discuss?

**Comment by cgewecke** [comment]
@mfahampshire Sure! My email is christophergewecke@gmail.com

**Comment by mfahampshire** [comment]
@cgewecke sent you a mail from max@curvelabs.eu . Thanks!

**Comment by cgewecke** [comment]
There were two issues here:

**Static Artifacts**

The project interacts with a contract system developed elsewhere, whose contracts are compiled using a different major solc version. Because Truffle doesn't support multiple compiler versions, artifacts for the externally developed contracts needed to be statically preserved in a `build` folder between test runs.

This was resolved by copying static artifacts from the `build` folder to `.coverage_artifacts` (a temporary folder SC uses to store instrumented artifacts in) during the [post-compilation workflow hook][1].

[1]: https://github.com/sc-forks/solidity-coverage/blob/master/docs/advanced.md#workflow-hooks

**Async `deployer.link`**

The migration scripts were failing on the `link` step. Technically `deployer.link` is async, but for unknown reasons the necessity of `await`-ing it is only an issue when `test` is invoked from within a Truffle plugin. The documentation at Truffle for migrations hasn't been updated in a long time and still shows Promise chain syntax (or just sync syntax) for everything. 

Will make a note in the README about this because it's super confusing / insane.
