### ISSUE TITLE
Support HardHat 

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#541]
- [ ] #540 
- [ ] Run BuidlerEVM via [buidler 619][1]
- [ ] Update Buidler E2E test 
- [ ] Use BuidlerPluginError (see #527)
- [ ] Speed up initialization by lazy loading & using ethers instead of web3

[1]: https://github.com/nomiclabs/buidler/pull/619

**Comment by PaulRBerg** [comment]
Looking forward to this!

**Comment by cgewecke** [comment]
`0.7.12`

See the new [Hardhat README][1] for installation instructions, etc.

By default coverage now runs on the HardhatEVM / network and requires no additional config or ganache provider setup. Also about 2X faster. 

Please just lmk if you run into any issues with this.

[1]: https://github.com/sc-forks/solidity-coverage/blob/master/HARDHAT_README.md#solidity-coverage

**Comment by PaulRBerg** [comment]
Amazing! I upgraded to 0.7.12 in my [solidity-template][1] and it works like a charm with Hardhat. Thanks @cgewecke!

https://github.com/PaulRBerg/solidity-template

**Comment by shalzz** [comment]
Hi,
This does work great unless you have set a different path for `artifacts` in `hardhat.config.{js,ts}`.

For example in my repo I have
```
  paths: {
    cache: "./build/cache",
    artifacts: "./build/artifacts",
  },
```
So with still the tests fail unless I run with `hardhat coverage --temp build/artifacts` since I'm also using the hardhat-typechain plugin which reads from the `artifacts` path.

I think the right thing to do here is for the plugin to have the artifacts be stored in the paths.artifacts path instead of the hardcoded `.coverage_artifacts` path

This is an example repo with this config: https://github.com/unipeer/unipeer

**Comment by cgewecke** [comment]
Hi @shalzz, thanks for reporting.  

Yes, I think at a minimum the README needs to highlight this option and discuss how to use w/ typechain or other plugins that also rely on the `paths.artifacts` value. 

The difficulty with storing coverage artifacts in the default location is that they are "corrupted" by the instrumentation the tool adds to the solidity code. And it's possible people rely on the artifacts folder being preserved across commands and would be upset when coverage automatically deletes it.   

Additionally, there is a bug discovered yesterday in the way `paths.artifacts` is set/read (#573) which I've cross-reported at [hardhat 1030][1]. Am waiting for advice about how to proceed there...
 

[1]: https://github.com/nomiclabs/hardhat/issues/1030

**Comment by shalzz** [comment]
Hi @cgewecke 

Yes that makes sense, I think the if #573 is fixed it should also address this issue, since then typechain can then just read the instrumented artifacts from the temp folder set by this plugin.

In any case thanks a lot for the plugin.
