### ISSUE TITLE
node-gyp

### ISSUE THREAD

**Issue by alcuadrado** [sc-forks/solidity-coverage#542]
Hey Chris!

I'm creating this issue because `solidity-coverage` is one of the few packages that, indirectly, still compiles native dependencies.

Your dependency `@truffle/provider` has a pinned version of `web3`, which has a pinned version of `websocket`.

I'm creating this issue to track it, but I have [already reported it on Truffle](https://github.com/trufflesuite/truffle/issues/3446).

Note that most probably you'll need to bump the major fo `@truffle/provider`.

Thanks

**Comment by cgewecke** [comment]
Ah ok! Thanks!

**Comment by alcuadrado** [comment]
Hey Chris,

Now we need to update `@truffle/provider` to `^0.2.24`, and `node-gyp` will be gone.

**Comment by cgewecke** [comment]
`0.7.12` 

(Thanks again @alcuadrado for tracking all this stuff.)
