### ISSUE TITLE
Add Vyper support

### ISSUE THREAD

**Issue by FreshmanQ** [sc-forks/solidity-coverage#544]
Hi guys,

I check your code on `plugin.util.js`, function `assembleFiles()`, you just filter out `.sol` files, however, there are other kinds of contracts, like `.vy`, which truffle compile handles correctly. I think it will be good to become more compatible.

**Comment by ninjaahhh** [comment]
+1

even though we are not instrumenting vyper but in cases our solidity files have a dependency on vyper contracts, it would be nice if they can be handled nicely.

failing scenario using truffle v5: have `A.sol` and `B.vy` under `contracts`, adding `B.vy` to skipped files but it's part of our testing dependency, then `truffle run coverage` won't compile the vyper file this failing the test

**Comment by cgewecke** [comment]
@ninjaahhh, @FreshmanQ Thanks for opening.

Agree this is a bug. Will fix.

**Comment by ninjaahhh** [comment]
thanks for the quick response.

here's a related issue on truffle side which may affect the fix: https://github.com/trufflesuite/truffle/issues/3455

hope it will help

**Comment by cgewecke** [comment]
This should be fixed in `0.7.12`. 

Vyper contracts will be automatically skipped for coverage, but they should now be included in Truffle's compilation set correctly.
