### ISSUE TITLE
"--testfiles" doesn't parse multiple folders and exclusions

### ISSUE THREAD

**Issue by PaulRBerg** [sc-forks/solidity-coverage#546]
## Current Behaviour

Here's [my script][1]:

```sh
buidler coverage --solcoverjs ./.solcover.js --network coverage --temp artifacts --testfiles \"./test/{integration,unit}/*.ts
```

When I run it, solidity-coverage attempts to run the tests in "./test/e2e" as well, although I whitelisted only the "./test/integration" and "./test/unit" folders. As per this [StackOverflow post][2], this should be possible.

Similarly, if I rewrite the glob like this:

```sh
./test/**/*.ts!(/test/e2e)
```

Or:

```sh
./test/**/*.ts!(/test/e2e/**/*.ts)
```

solidity-coverage continues to run the tests under "./test/e2e".

## Expected Behaviour

Globbing a few select folders and excluding path should be possible.

## Context

This happens when I run solidity-coverage as a Hardhat (formerly Buidler) plugin. I know that there had been [issues][3] with the "testfiles" glob when run via Hardhat, so maybe this is related.

[1]: https://github.com/MainframeHQ/mainframe-lending-protocol/blob/a61b240d078f18bd5406299ba238f26c4a77db71/package.json#L86
[2]: https://stackoverflow.com/questions/51907819/glob-sync-pattern-on-multiple-directories
[3]: https://github.com/sc-forks/solidity-coverage/issues/524#issuecomment-651136174

**Comment by cgewecke** [comment]
@PaulRBerg 

Not certain but there might be typo on your end - the option requires that the glob be enclosed in quotes.

Does it work as expected if you rewrite it as?
```
"coverage": "buidler coverage ...  --testfiles './test/{integration,unit}/*.ts'",
```

The glob processing is executed by [globby][1] here and should handle whatever glob syntax it permits:
https://github.com/sc-forks/solidity-coverage/blob/9a2c7cb70c4922764d79ca7b92d5cfebc751f0c2/plugins/resources/buidler.utils.js#L18-L24

[1]: https://github.com/sindresorhus/globby#globby-

**Comment by PaulRBerg** [comment]
Whoops, you're right. I used to have an enclosing \", but that got deleted when I edited the glob in most recent commits. I'm using \" instead of ' so that the script remains compatible with Windows.

Thanks!
