### ISSUE TITLE
Allow configuring default sender account in Buidler plugin

### ISSUE THREAD

**Issue by frangio** [sc-forks/solidity-coverage#552]
The default sender account is hardcoded to `accounts[0]`. I'd like to be able to configure it to something else.

https://github.com/sc-forks/solidity-coverage/blob/f1d4001802f8c6f1851e7e6f62800c0b13b4be0f/plugins/buidler.plugin.js#L66

**Comment by cgewecke** [comment]
@frangio 

This should be fixed in the Hardhat plugin now. Whatever you specify as `from` in your Hardhat (or other) network config should persist when coverage runs the tests as well. 

`0.7.12`
