### ISSUE TITLE
Add Zeppelin as a Hardhat E2E

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#555]
Bit of a chicken and egg sequence for this but in [#551 comment][1] frangio notes they will migrate to Hardhat when #541 is published

[1]: https://github.com/sc-forks/solidity-coverage/pull/551#issue-511569447

**Comment by frangio** [comment]
Note that we migrated to Buidler v1 a few days ago already. (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2397)

**Comment by cgewecke** [comment]
@frangio Oh! I misunderstood this, great thanks.
