### ISSUE TITLE
Support for npm scripts which call npm packages

### ISSUE THREAD

**Issue by maurelian** [sc-forks/solidity-coverage#56]
Try to run this on /0xProject/contracts. The tests run as is without issue (using `npm run test`, but throw an error when called via solidty-coverage. It seems to have something to do with the [npm scripts](https://github.com/0xProject/contracts/blob/master/package.json#L10): 

    "transpile": "rm -rf ./transpiled; copyfiles ./build/**/* ./transpiled; tsc",
    "test": "npm run transpile; truffle test",

Error message: 

```
Launching test command (this can take a few seconds)...

> 0x-smart-contracts@1.0.0 test /Users/primary/Projects/0x_contracts/coverageEnv
> npm run transpile; truffle test


> 0x-smart-contracts@1.0.0 transpile /Users/primary/Projects/0x_contracts/coverageEnv
> rm -rf ./transpiled; copyfiles ./build/**/* ./transpiled; tsc

sh: copyfiles: command not found
sh: tsc: command not found

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/primary/.nvm/versions/node/v7.10.0/bin/node" "/Users/primary/.nvm/versions/node/v7.10.0/bin/npm" "run" "transpile"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
```

I also tried changing the script to

`rm -rf ./transpiled; ./node_modules/.bin/copyfiles ./build/**/* ./transpiled; ./node_modules/.bin/tsc`

This gets me a new error, which seems closer to success: 

    error TS5023: Unknown compiler option 'baseUrl'.
    error TS5023: Unknown compiler option 'allowJs'.

**Comment by cgewecke** [comment]
So . . . in principal we *do* support this: since #44 it's possible to set a `copyNodeModules` option in `.solcover.js` to `true` and include node_modules in the coverage environment. For 0xProject this adds about 90 seconds to the total time coverage takes to run. And it's possible to get a report this way (recipe below).

However, I'm seeing some bewildering results:
+ running tests w/out coverage: 58 passing / 18 failing.
+ running test **with** coverage: 25 passing / 51 failing.

I don't understand why. Could be something in the transpilation step? Or not? Complicated build here! They're pushing the envelope. 

@maurelian Are you getting 58 passing / 18 failing running the tests as they suggest? If everything's passing for you then something is wrong on my end.

As far as configuration goes: 
My `.solcover.js` looks like this:
```javascript
module.exports = {
    testCommand: 'npm run transpile; truffle test --network coverage',
    copyNodeModules: true,
}
```

My `truffle.js` looks like this:
```javascript
module.exports = {
  networks: {
    development: {
      host: 'localhost',
      port: 8545,
      network_id: '*', // Match any network id
    },
    kovan: {
      host: 'localhost',
      port: 8546,
      network_id: '42',
      gas: 4612388,
    },
    coverage: {
      host: "localhost",
      network_id: "*",
      port: 8555,         // <-- Use port 8555  
      gas: 0xfffffffffff, // <-- Use this high gas value
      gasPrice: 0x01      // <-- Use this low gas price
    }
  },
  test_directory: 'transpiled/test',
  migrations_directory: 'transpiled/migrations',
};
```

NB: also fooled around with the network id param (b/c they specify one) in both testrpc and truffle.js and it made no noticeable difference.

**Comment by maurelian** [comment]
I had the tests running at some point, on some branch, but similarly am getting failures now. 

Sorry for sending you on a bug hunt that might not have been in your tool. Let me get back to you on this soon after talking to the team. :)

**Comment by cgewecke** [comment]
Oh not at all - I think there are definitely solidity-coverage bugs here! No worries.

**Comment by cgewecke** [comment]
I'm going to close because the question about how to call node packages from scripts is basically resolved. However - I'm adding 0xProject to the list of installation targets to test. And think an addendum to the README might be in order here because how to handle this issue is not super clear.

**Comment by maurelian** [comment]
I know this is closed, but I've made some progress, and also hitting a new wall! So it's worth reporting in. :)

Updates to the repo are here: https://github.com/maurelian/0x-contracts/tree/audit_coverage

Things I worked around: 
* 0x' tests are very sensitive to the testrpc version, so it needs to be @3.0.2 to get the tests running with their npm scripts.
* I had to make [this change](https://github.com/maurelian/0x-contracts/commit/752fe994ecbdb024b311b7d51377aff07767a9a9) to appease the parser. I don't think it would impact the report output
* I got tsc working by [modifying the options](https://github.com/maurelian/0x-contracts/commit/81172c3c8000f90e41ee82d06fd9a569b1bb01fe#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10). 

So at this point I'm getting a funny error: `/bin/sh: ./node_modules/truffle/cli.js: No such file or directory`

but it does exist. 

```bash
$ ./node_modules/truffle/cli.js version
Truffle v3.2.5

$ ./node_modules/.bin/solidity-coverage
Generating coverage environment
Instrumenting  ./coverageEnv/contracts/base/MultiSigWallet.sol
Instrumenting  ./coverageEnv/contracts/base/Ownable.sol
Instrumenting  ./coverageEnv/contracts/base/SafeMath.sol
Instrumenting  ./coverageEnv/contracts/base/StandardToken.sol
Instrumenting  ./coverageEnv/contracts/base/StandardTokenWithOverflowProtection.sol
Instrumenting  ./coverageEnv/contracts/base/Token.sol
Instrumenting  ./coverageEnv/contracts/Exchange.sol
Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Instrumenting  ./coverageEnv/contracts/MultiSigWalletWithTimeLock.sol
Instrumenting  ./coverageEnv/contracts/MultiSigWalletWithTimeLockExceptRemoveAuthorizedAddress.sol
Instrumenting  ./coverageEnv/contracts/Proxy.sol
Instrumenting  ./coverageEnv/contracts/TokenDistributionWithRegistry.sol
Instrumenting  ./coverageEnv/contracts/TokenRegistry.sol
Instrumenting  ./coverageEnv/contracts/tokens/DummyToken.sol
Instrumenting  ./coverageEnv/contracts/tokens/EtherToken.sol
Instrumenting  ./coverageEnv/contracts/tokens/Mintable.sol
Instrumenting  ./coverageEnv/contracts/tokens/ZRXToken.sol
Launching testrpc on port 8555
Launching test command (this can take a few seconds)...
/bin/sh: ./node_modules/truffle/cli.js: No such file or directory
Cleaning up...

    There was an error generating coverage. Possible reasons include:
    1. Another application is using port 8555
    2. Truffle crashed because your tests errored

  Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...


$ ls ./node_modules/truffle/cli.js
./node_modules/truffle/cli.js
```

**Comment by maurelian** [comment]
I fixed the previous error by [using the absolute path](https://github.com/maurelian/0x-contracts/commit/a9f8f85fa028501351e986ec3763225959d30a64) to truffle. 

The [report is at least generating now](https://htmlpreview.github.io/?https://raw.githubusercontent.com/maurelian/0x-contracts/blob/734eb5d9a6012c40269332ccc62f873c176f4e79/coverage/index.html), but I'm running out of gas, even after adding `ffff` to the gas limit.

**Comment by cgewecke** [comment]
Hmmmm. Interesting. This is great.

Will you try adding `--network coverage` to the invocation of truffle in the `testCommand` option and seeing if that changes things? Alternatively you could make the development network have the same config as the coverage network.

I might also revert the change to the gas in `truffle.js` unless it still runs out of gas when deploying the contract. I remember I used to make the gas values really huge and some are **too** big - they get ignored or fail silently.

**Comment by maurelian** [comment]
So, when I tried that, I was getting empty responses from testrpc. 

```Launching test command (this can take a few seconds)...
Error: Invalid JSON RPC response: ""```

Then I tried `norpc:true`, and just ran your fork in another terminal:

`./node_modules/ethereumjs-testrpc-sc/bin/testrpc  --gasLimit 0xfffffffffff --networkId 50 --port 8555`

And that worked! No idea what would be different, but it worked. That seems really weird to me, not sure what's up. Maybe some async stuff?

I also should double check the [report output](https://htmlpreview.github.io/?https://raw.githubusercontent.com/maurelian/0x-contracts/audit_coverage/coverage/contracts/index.html) against the actual tests, for accuracy.

**Comment by cgewecke** [comment]
Oh great! The testrpc disconnect thing is really frustrating. I can't figure that out. I'm going to add your `norpc` solution should to the README under Known Issues because it's happening a fair amount to other people too.

**Comment by maurelian** [comment]
although I think running testrpc in-memory is more elegant, I generally appreciate the feedback of running it in a separate terminal session.

**Comment by cgewecke** [comment]
Yes, I agree. I hoped that in-memory would just work and would make integration with CI more straightforward but it's actually been an unrelenting source of confusion and unreliability.

**Comment by maurelian** [comment]
Reviewing the report, I'm pretty sure it's missing somethings.

ie. you would at least expect to see the the if statement in this function being run, right?

![image](https://user-images.githubusercontent.com/23033765/27976345-159405f8-6334-11e7-946a-11d06cfc8419.png)

(as [seen here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/maurelian/0x-contracts/audit_coverage/coverage/contracts/Exchange.sol.html))

Happy to file an issue if you have a suggestion for what to call it. :)

**Comment by cgewecke** [comment]
Yes definitely file an issue as long the tests are actually making it past the require at line 126. . . I don't know what to call that either. Maybe 'Missing coverage after require' and link here.

**Comment by cgewecke** [comment]
They have some serious tests for that so if it's *not* making it past the require they have bug, which is conceivable. . .it might be worth logging what the values are around [here](https://github.com/0xProject/contracts/blob/master/test/ts/exchange/core.ts#L131). When I search the report for fillOrder the coverage looks consistent with not running that code. Like you can see that fillOrders don't complete. 

Which doesn't mean there isn't a problem here, but if that's the case shouldn't their tests error?

**Comment by cgewecke** [comment]
Checked the difference between testrpc 3.0.2 and testrpc-sc (which is based on 3.0.3). and saw that solc was temporarily pinned to 4.0.6 in that patch. I'm going to float it with a caret again . . .  don't know if that will change things but maybe.

**Comment by cgewecke** [comment]
Actually I'm pinning it to 0.4.8 because that's what testrpc@latest is.

**Comment by maurelian** [comment]
Is the solc version used determined by the testrpc version?

I'm not getting any compilation errors, and the `fillOrder` errors are all complaining about an `invalid opcode`, which is consistent with the evaluation of [`require(false)`](https://solidity.readthedocs.io/en/develop/control-structures.html#error-handling-assert-require-revert-and-exceptions). 

I'm experiencing a discrepancy between results which seem to vary depending on both the use of testrpc and when using solidity-coverage to run tests. 

Quick summary of my observations: 
* With the vanilla `ethereumjs-testrpc@3.02` and `npm run test` command: All tests are passing.
* With `./node_modules/ethereumjs-testrpc-sc/bin/testrpc` (no options), and `npm run test` command: `fillOrder` tests fail with the `invalid opcode` exception. I get `58 passing (26s)  38 failing`
* With `./node_modules/ethereumjs-testrpc-sc/bin/testrpc --gasLimit 0xfffffffffff --port 8555`, and `./node_modules/solidity-coverage/bin/exec.js` I get the same `invalid opcode` errors on `fillOrder` tests, but `66 passing (19s)  30 failing`

Any suggestions for troubleshooting? Feel free to ping me in slack. :)

**Comment by cgewecke** [comment]
I think the solc thing is irrelevant actually. I saw it in the testrpc deps but it looks like it's only used for the unit tests. I'm going to try to reproduce . . . 

Were I to make another wild guess, this problem is about signing and weird signing stuff somewhere from earlier this year.

**Comment by maurelian** [comment]
I tried a variation on case 2 above, to see if your testrpc fork depends on the gas limit setting. 
* With `./node_modules/ethereumjs-testrpc-sc/bin/testrpc --gasLimit 0xfffffffffff`, and `npm run test` I get `66 passing (20s) 30 failing`.

This at least brings the behavior of `./node_modules/solidity-coverage/bin/exec.js` and `npm run test` in line with each other, and seems to suggest that the issue is with `ethereumjs-testrpc-sc`. mishandling something?

**Comment by cgewecke** [comment]
Oh here is fine. This is `sc-core`. Could you `npm list ethereumjs-util` on your terminal and post the output so I can compare with what I have locally?

**Comment by maurelian** [comment]
```
$ npm list ethereumjs-util
0x-smart-contracts@1.0.0 /Users/primary/Projects/0x_contracts
├─┬ ethereumjs-abi@0.6.4
│ └── ethereumjs-util@4.5.0 
├── ethereumjs-util@5.1.2 
└─┬ solidity-coverage@0.1.7
  └─┬ ethereumjs-testrpc-sc@3.0.3 (git+https://github.com/sc-forks/testrpc-sc.git#15cc0fb8e031bee152c7b8e3f8df5f2ad33ca04f)
    ├─┬ ethereumjs-account@2.0.4
    │ └── ethereumjs-util@4.5.0 
    ├─┬ ethereumjs-block@1.2.2
    │ └── ethereumjs-util@4.5.0 
    ├─┬ ethereumjs-tx@1.1.2
    │ └── ethereumjs-util@4.5.0 
    ├─┬ ethereumjs-vm@2.0.2 (git+https://github.com/sc-forks/ethereumjs-vm-sc.git#328771cace30ed16ad5c1d13a69cda13d31173f9)
    │ └── ethereumjs-util@4.5.0 
    ├─┬ ethereumjs-wallet@0.6.0
    │ └── ethereumjs-util@4.5.0 
    └─┬ merkle-patricia-tree@2.1.2
      └── ethereumjs-util@4.5.0 


```

**Comment by cgewecke** [comment]
Oh and where is your testrpc3.0.2? Is that using ethereumjs-util@4.5.0?

**Comment by maurelian** [comment]
It's in `~/.config/yarn/global/node_modules/ethereumjs-testrpc`

When I `cd` there:
```
$ npm list ethereumjs-util
ethereumjs-testrpc@3.0.2 /Users/primary/.config/yarn/global/node_modules/ethereumjs-testrpc
├─┬ ethereumjs-block@1.2.2
│ ├─┬ ethereumjs-tx@1.3.0
│ │ └── ethereumjs-util@5.1.1 
│ └── UNMET DEPENDENCY ethereumjs-util@^4.0.1
├─┬ ethereumjs-tx@1.1.2
│ └── UNMET DEPENDENCY ethereumjs-util@^4.5.0
└── UNMET DEPENDENCY ethereumjs-util@~4.5.0
npm ERR! missing: ethereumjs-util@~4.5.0, required by ethereumjs-testrpc@3.0.2
npm ERR! missing: ethereumjs-util@^4.0.1, required by ethereumjs-block@1.2.2
npm ERR! missing: ethereumjs-util@^4.5.0, required by ethereumjs-tx@1.1.2
```

**Comment by cgewecke** [comment]
Hmmmm! Interesting! Well, I made a branch of `solidity-coverage` with a testrpc-sc that uses `ethereumjs-util@4.5.0`:
```
npm install --save-dev https://github.com/sc-forks/solidity-coverage.git#district
``` 

For the life of me cannot get past the typescript comp errors and it seems like the require paths in the tests on the `audit_coverage` branch are unexpected . . . I'm getting this right after the compilation step:
```
Error: Cannot find module '../../build/contracts/MultiSigWalletWithTimeLock.json'
```

Thanks for that slack invite - I read through a few weeks of it on Monday and it's completely fascinating! So cool.

**Comment by maurelian** [comment]
`Error: Cannot find module '../../build/contracts/MultiSigWalletWithTimeLock.json'`

IIRC that's fixed by running `npm run compile` before `npm run test`.

**Comment by cgewecke** [comment]
Ok. Revisiting, now . . .

**Comment by cgewecke** [comment]
Sadly I'm not making too much headway on this. . . Some of the errors are being triggered by network stuff that's hardcoded into the migrations files - there are places there where the testing environment network is assumed to be 'development'. That stuff is fixable / hackable.
 
But the signing? Is there any way that you can ask them about their signing protocol and if they are dependent on ethereumjs-util@4.x.x? Just plugging in an earlier version of the utils isn't working.

There was significant change to the way things are signed this spring - see this [ethereumjs-util PR](https://github.com/ethereumjs/ethereumjs-util/pull/67) and I *think* `testrpc-sc` is current in that regard, but I need to verify that and will write a test for it tomorrow. It's really important.
