### ISSUE TITLE
Zero coverage when using `hardhat_reset`

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#574]
Atm the tool [reaches][2] deep into the hardhat node to attach directly to the vm step event because hardhat's experimental trace hook seems to be missing pc-to-instruction data in some cases (calls to linked libraries, delegate calls, and/or factory contract deployments).

Per [this HH PR comment][1] is the vm destroyed on reset? 

If so perhaps detect by HARDHAT_NETWORK_RESET_EVENT and re-attach.

[1]: https://github.com/nomiclabs/hardhat/pull/1024#discussion_r526135164
[2]: https://github.com/sc-forks/solidity-coverage/blob/8660166ae09963e0b27f3ff1a7c1ed88bee2038a/lib/api.js#L279-L282

**Comment by cgewecke** [comment]
This was reported in the wild in an HH discord comment mid-feb....

**Comment by alcuadrado** [comment]
Hey Chris, I just noticed this issue. We added an event to our providers that is triggered when a `hardhat_reset` is run. I think this would help a lot. It's called `hardhatNetworkReset`, and it's triggered both in the in-memory HH Network provider, and in our HTTP Provider when connected to a remote HH Network instance.

**Comment by cgewecke** [comment]
@alcuadrado Great! That sounds like exactly what's needed. Thanks, will fix.

**Comment by ajb413** [comment]
Hello. Just ran into this issue myself. I am running a [hardhat reset](https://hardhat.org/guides/mainnet-forking.html#resetting-the-fork) in my mocha `beforeEach` to get my fork back to a specific block for each individual test. My main contract file went down to 0% coverage. Does anyone know of a workaround?

**Comment by cgewecke** [comment]
@ajb413 Apologies, this really needs to get fixed. You should be able to use `evm_snapshot` and `evm_revert` instead of `reset`.

**Comment by ajb413** [comment]
@cgewecke No need to apologize. Thank you so much for your workaround! It works perfectly. To help those that need this...

Old way, preferable, but does not work with solidity-coverage at the moment:
```js
describe('Some Contract', function() {

  beforeEach(async () => {
    await resetForkedChain();
    // code ...
  });

  // tests...

});

// Does not work with solidity-coverage at the moment
async function resetForkedChain() {
  // Parent directory's hardhat.config.js needs these to be set
  const forkUrl = hre.config.networks.hardhat.forking.url;
  const forkBlockNumber = hre.config.networks.hardhat.forking.blockNumber;
  await hre.network.provider.request({
    method: 'hardhat_reset',
    params: [{
      forking: {
        jsonRpcUrl: forkUrl,
        blockNumber: forkBlockNumber
      }
    }]
  });
}
```

workaround in the meantime:
```js
let snapshot;

describe('Some Contract', function() {

  before(async () => {
    // code ...
    await makeForkedChainSnapshot();
  });

  beforeEach(async () => {
    await resetForkedChain();
    await makeForkedChainSnapshot();
    // code ...
  });

  // tests...

});

async function resetForkedChain() {
  await hre.network.provider.request({
    method: 'evm_revert',
    params: [ snapshot ] // snapshot is global
  });
}

async function makeForkedChainSnapshot() {
  // snapshot is global
  snapshot = await hre.network.provider.request({ method: 'evm_snapshot' });
}

```

**Comment by adjisb** [comment]
Any advice on how to take a snapshot of the initial state of the evm ?
The problem I see is that when the test run there is a lot of stuff already there.... for example what if a previous test eats all my balance ?

**Comment by adjisb** [comment]
This fixes the issue on my side: https://github.com/sc-forks/solidity-coverage/pull/667

**Comment by cgewecke** [comment]
Update: there's ongoing work to support hardhat_reset at #681. Unfortunately it's proving difficult to re-attach a VM step event listener to the newly instantiated hardhat node created after the reset event. 

If anyone is interested in helping debug this issue further please feel free to experiment with #681 and open a PR against it. It has a simple failing unit test case.

**Comment by cgewecke** [comment]
This should be resolve in `0.7.18`
