### ISSUE TITLE
Errors with `no code at address` when using with GSN api

### ISSUE THREAD

**Issue by viraj124** [sc-forks/solidity-coverage#579]
My tests run while I have the solidity coverage plugin in my truffle config but when I run truffle run coverage I get the error 
``` Error: Cannot create instance of IPaymaster; no code at address 0x9561C133DD8580860B6b7E504bC5Aa500f0f06a7``` with IPaymaster being an interface and I have integrated open gsn where the contracts inherit some interfaces and hence the issue any workaround for this?

**Comment by viraj124** [comment]
I tried including the file in the skipped file section in .solcover.js here is my .solcover.js content
```
module.exports = {
  skipFiles: [
      'test/', './node_modules/@opengsn/gsn/contracts/interfaces/IPaymaster.sol'
  ]
}
```
and the command in my package.json
```     "coverage": "truffle run coverage --network development --solcoverjs ./.solcover.js && npx gsn start", ```
but the IPaymaster still isn't skipped.

**Comment by cgewecke** [comment]
Hi @viraj124. 

When you run `truffle test` on it's own does everything work as expected?

Do you have a link to the code so I can try to reproduce this?

**Comment by viraj124** [comment]
@cgewecke yes it does truffle test works fine only when I run coverage I get this no code error actually the code isn't open sourced I have my contracts integrated with https://opengsn.org/ and the people from the team told me that they faced issues with interfaces as well with the solidity coverage package, but still I wanted to give it a try and hence created an issue

**Comment by cgewecke** [comment]
@viraj124 

The thing is that your error does not look coverage related. It's what you'd see if you tried to deploy an interface contract in Truffle. We have lots of tests here for contracts that use interfaces and they pass. 

If you're running migrations, could you double-check that all your deployments and library linking statements use `await` correctly? Migrations run from within a truffle plugin like solidity-coverage are very sensitive to missing promise logic. 

Could you also look through your code and see if there's a location where you are trying to deploy `IPaymaster` directly? This is not allowed. A deployable contract will inherit from IPaymaster and implement all of its methods.   

If none of that works, I think the best way forward is to make a small reproduction case for the error that I can debug.

**Comment by viraj124** [comment]
@cgewecke so the thing is the point I get the error is 
   ```  // getting the gsn configuration
    config = await resolveConfigurationGSN(web3provider.currentProvider, {
      paymasterAddress: paymaster.address,
      logLevel: 1,
    }); 
```
My migrations are correct and I deploy using .new() in my tests and they have await there is no missing await and also I am not trying to deploy ``` IPaymaster ``` directly only a contract that inherits ``` IPaymaster ```

**Comment by viraj124** [comment]
would it be helpful if send a snippet of my test code, also I tried skipping the IPaymaster in .solcovr but it didn't work why is that ?

**Comment by cgewecke** [comment]
@viraj124 

Coverage doesn't instrument interfaces (or do anything with them). They have no functional code to cover.

What do you see if you put a log line right before that GSN config code and print `paymaster.address` for both `coverage` and `test`?

**Comment by cgewecke** [comment]
Oh @viraj124, are you instantiating Web3 yourself? Can you make sure that it's connecting to same port etc that solidity-coverage has launched ganache with? All that info is printed out at the top of the output when coverage starts.

**Comment by viraj124** [comment]
@cgewecke already tried this before actually when I do that I get 
``` 
 Error: Returned error: VM Exception while processing transaction: revert
``` 
in all my tests the thing is when I am running my tests I also need to run npx gsn start with ganache-cli since the gsn commands spins up the gsn specific external contracts I feel the issue might be due to that

**Comment by cgewecke** [comment]
Ah ok,  there are [workflow hooks][1] you can define in `.solcover.js` that let you run arbitrary additional logic if you need to after server launch.

[1]: https://github.com/sc-forks/solidity-coverage/blob/master/docs/advanced.md#workflow-hooks

**Comment by viraj124** [comment]
Sure will try it I am in IST Timezone so will like try this in 7-8 hours will keep you posted thanks for the help

**Comment by cgewecke** [comment]
Ok cool, no worries. I'm going to re-title this issue to reflect that this is about how to run coverage w/ GSN.

**Comment by viraj124** [comment]
@cgewecke I was trying it out for a while here is .solcover code
```
import { exec } from 'child_process';

async function runGSN(){
  exec('npx gsn start', (error, stdout, stderr) => {
    if (error) {
        console.log(`error: ${error.message}`);
        return;
    }
    if (stderr) {
        console.log(`stderr: ${stderr}`);
        return;
    }
    console.log(`stdout: ${stdout}`);
});
}

module.exports = {
  onServerReady: runGSN,
  skipFiles: [
      'test/', './node_modules@opengsn/gsn/contracts/interfaces/IPaymaster.sol'
  ]
}
```
the issue is because I need this command to run in a separate window sometimes i get time out some times my tx reverts because ``` npx gsn start ``` doesn't get started, the gsn team currently uses 0x coverage package maybe I need to try with that

**Comment by cgewecke** [comment]
@viraj124 

The hook is async. Perhaps you could await a timeout for a few seconds inside the hook while GSN spins up.

```js
async function runGSN(){
  exec('npx gsn start', (error, stdout, stderr) => {
    // ...etc
  });
  // Just sketching this idea, not sure it actually compiles...
  await new Promise((resolve) => setTimeout(()=> resolve(), 5000)) 
}
```

**Comment by viraj124** [comment]
@cgewecke yeah time out was the issue but for some reason now I get an overflow issue which I have seen for the first time my tests again all work fine
```
Relaying errors (1):
http://127.0.0.1:57118 => local view call to 'relayCall()' reverted: view call to 'relayCall' reverted in client: overflow (fault="overflow", operation="BigNumber.from", value=9007199254740991, code=NUMERIC_FAULT, version=bignumber/5.0.10)
```

**Comment by cgewecke** [comment]
@viraj124 

Hmm. Could you see if setting the block gas limit like this in `providerOptions` in `.solcover.js` fixes this?
```js
module.exports = {
  providerOptions: {
    gasLimit: "0xfffffffffff"
  }
}
```

**Comment by viraj124** [comment]
@cgewecke thanks it got resolved do I need to specify my accounts or something in solcver though I am generating new accounts from the provider since I get
 ``` 
Relaying errors (1):
http://127.0.0.1:49490 => paymaster rejected in local view call to 'relayCall()' : signature mismatch
``` 
now although I have done this in my package.json
```
truffle run coverage --network development
```

**Comment by viraj124** [comment]
resolved had to do some changes but done thanks @cgewecke for the other help 👍

**Comment by viraj124** [comment]
should I close this ?
also on another note can we like stay connected ? my email is virajm72@gmail.com

**Comment by cgewecke** [comment]
Sure! If you want to close feel free.

It's nice to meet you. 

My email is christophergewecke@gmail.com

**Comment by viraj124** [comment]
resolved
