### ISSUE TITLE
Seems like readme section for hardhat is wrong

### ISSUE THREAD

**Issue by cmark0v** [sc-forks/solidity-coverage#586]
version 0.7.12 does seem to need the config instructions specified for buidler rather than the simpler ones specified for hardhat. also thanks for this plugin :)

**Comment by cgewecke** [comment]
@cmark0v Could you describe what you're seeing when no extra config is added?

Using coverage `v0.7.13` and the latest hardhat `v2.0.4` coverage should run on the hardhat network by default without any cli flags or extra network settings.

**Comment by cgewecke** [comment]
Closing for now, please just ping if you have more info about this...
