### ISSUE TITLE
Error using `create2` and solc optimizer off

### ISSUE THREAD

**Issue by steffenix** [sc-forks/solidity-coverage#589]
## Stack
- hardhat
- waffle
-  solidity-coverage

I am looking for a clue on where to look at, my tests are working using tests, when I use coverage I am having some issues.
Can some code that has some issues but the optimizer fixes ?

I have narrow down the issue and it looks like the create2 function isn't behaving the say way.

**Comment by cgewecke** [comment]
> Can some code that has some issues but the optimizer fixes ?

So far, there are two known cases where people have discovered code which only compiles with the optimizer on. 
+ examples of the first are documented in #417 and relate to contract deployments happening in the constructor of a parent contract. The best description is [here][1].
+ the second is being investigated at [solidity 10354][2] and relates to using structs/ABIEncoderV2 triggering a `stack too deep` assembler error.


[1]: https://github.com/sc-forks/solidity-coverage/issues/417#issuecomment-537856312
[2]: https://github.com/ethereum/solidity/issues/10354

> I have narrow down the issue and it looks like the create2 function isn't behaving the say way.

Oh! Could you provide some more details to help reproduce the problem?  
+ what is the test failure like?
+ what is your compiler version and settings?
+ what is the `create2` code sequence like?

**Comment by steffenix** [comment]
I just found the cause of the issue.
I was using standard gas estimate when sending the transaction when switching to coverage I guess the contract I try to deploy using gets too big and create2 just returns address(0x0).

I have fixed the issue overriding the gas estimate.

**Comment by cgewecke** [comment]
Oh great! That's good to hear.

The extra gas needed is often really confusing, sorry about that.
