### ISSUE TITLE
Invalid input source specified

### ISSUE THREAD

**Issue by niran** [sc-forks/solidity-coverage#60]
When I ran `solidity-coverage` for the first time, it gave me this error:

```
Invalid input source specified.
Compiliation failed. See above.
```

After some debugging, it turns out that the problem was the paths on my imports. I'd been importing `"Contract.sol"` instead of `"./Contract.sol"` in my contracts. Since solidity-coverage is more particular about the current working directory than truffle is, someone else might run into this issue. It's not a solidity-coverage bug, but I'm creating an issue in the hopes that the next person to have that problem comes across it.

**Comment by cgewecke** [comment]
@niran Thanks so much! That makes sense. Good to know.

**Comment by HOkn** [comment]
For myself, it was the opposite.

Worked: import "./networkmanager.sol";
Did NOT work: import "networkmanager.sol";

**Comment by RomanOznobin** [comment]
Thanks so much to !!!

**Comment by cleanunicorn** [comment]
@HOkn That's exactly how you should do it. Your import should have the prefix `./`
This will work
`import "./networkmanager.sol";`

This will create the error
```
Invalid input source specified.
Compiliation failed. See above.
```
`import "networkmanager.sol";`

**Comment by EbubeUd** [comment]
For me, it occurred in my test scripts. What I did was to comment out this line
import "remix_accounts.sol";
