### ISSUE TITLE
support for >= solidity 0.7.4 file-level functions and constants

### ISSUE THREAD

**Issue by gitpusha** [sc-forks/solidity-coverage#604]
Hi @cgewecke , 

I am compiling with solidity `0.8.0` and I am using:
```json
"hardhat": "2.0.7",
"solidity-coverage": "0.7.13"
```
Since solidity version [0.7.1](https://github.com/ethereum/solidity/releases/tag/v0.7.1) you can `define functions at file level`. 

Since solidity version [0.7.4](https://github.com/ethereum/solidity/releases/tag/v0.7.4) `Constants can be defined at file level.` 

We are making use of both `file-level` [functions](https://github.com/gelatodigital/gelato-instadapp/blob/master/contracts/functions/dapps/FMaker.sol) and [constants](https://github.com/gelatodigital/gelato-instadapp/blob/master/contracts/constants/CAave.sol) `definitions` in our project (follow link to examples). 

I just configured `solidity-coverage` with `hardhat` (used it with buidler before) and we now use it also together with `coveralls`. Worked immediately with hardhat mainnet forking and it's so much faster now than in the ole buidler and ganache days. Amazing stuff! Love it. 

However, at the moment we still `skipFiles` free functions and constants definition `.sol` files via `.solcover.json` because it seems like `solidity-coverage` cannot compile those with `0.8.0` yet: 

See the errors we get: 

free functions: 

![functions](https://user-images.githubusercontent.com/36712489/104584385-d2e5ee80-5662-11eb-8cf2-54c30adead6b.jpg)

free constants:
![constants](https://user-images.githubusercontent.com/36712489/104584394-d6797580-5662-11eb-8bb1-c3ab4b78e4d6.png)

Probably the cause of the error is the same for both. 

**When do you think will you add support for free functions and constants?** (free functions are very important for our code)

Tagging @fvictorio because it might be related to [soliditiy-parser](https://github.com/solidity-parser/parser)

**Comment by cgewecke** [comment]
The latest parser supports this syntax - everything's ok there. 

The instrumentation of function-level defs needs to be fixed here though...

**Comment by cgewecke** [comment]
Should be fixed in `0.7.14` (just published). Thanks for a lot for reporting this. 

Ran `npx hardhat coverage` on the master branch of gelato-instadapp ... partial shot of the report including FMaker.sol:

![Screen Shot 2021-01-14 at 4 16 13 PM](https://user-images.githubusercontent.com/7332026/104665295-d76fce80-5685-11eb-86f2-6410cda3cb08.png)

Just lmk if you are still running into problems though...
