### ISSUE TITLE
Warning: Contract code exceeds 24576 bytes

### ISSUE THREAD

**Issue by gretzke** [sc-forks/solidity-coverage#609]
When running solidity coverage the following warning shows up during compilation:
```
Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
```
When running solidity-contract-size the largest contract does not exceed 17KB. Also these warnings are not produced when compiling with truffle.

**Comment by cgewecke** [comment]
@gretzke 

The coverage tool injects statements into the contract as instrumentation - e.g to track lines, branches etc - increasing the contract size. This technique is similar to what the nyc/istanbul coverage tool does under the hood for Javascript. 

The latest `solidity-coverage@beta` filters all Hardhat compiler warnings fwiw. There's more info about the beta [in these release notes][1]

[1]: https://github.com/sc-forks/solidity-coverage/releases/tag/v0.8.0-beta.0
