### ISSUE TITLE
explicitly called branches with ENUM not being recorded

### ISSUE THREAD

**Issue by YannyD** [sc-forks/solidity-coverage#614]
I have a test explicitly calling registry.alterAsset(0, 3, 0), which uses AssetLibrary function alterAttribute01() with _attributeIndex ==3.  However, that else if statement inside alterAttribute01() is not being recorded in the coverage.  Is this a problem with the enum variable?  The same exact thing is happening for returnAttribute01() function inside the AssetLibrary when _attributeIndex==3; that branch is untouched, as well.  

Is this a problem with enums or am I doing something wrong?

Repo visible here and coverage test runs with "yarn coverage":
https://github.com/YannyD/pandiSample

**Comment by cgewecke** [comment]
![Screen Shot 2021-02-08 at 11 10 25 PM](https://user-images.githubusercontent.com/7332026/107328258-4d880b00-6a63-11eb-8374-3b6199a2c65e.png)

The report shows that the `else` branch of the last condition is never executed - e.g there's no test with values outside the 0 - 3 range.

If you add a `require` statement to the top of the method as you've done with `returnAttribute01` (filtering for invalid inputs), the last clause can be made a pure `else`. Then add a test where `_attributeIndex` is an invalid value and your coverage for that method will be perfect. 

```solidity
function alterAttribute01(Asset01 storage _asset, uint _attributeIndex, uint _newValue) internal{
        require(_attributeIndex <=3, "Invalid _attributeIndex: must be between 0 and 3");
        if(_attributeIndex ==0) _asset.current_loan_balance = _newValue;
        else if(_attributeIndex ==1) _asset.original_loan_balance = _newValue;
        else if(_attributeIndex ==2) _asset.note_rate = _newValue;
        else _asset.property_type = PropertyType(_newValue);
 }
```

[Stack exchange: how to read an istanbul html report][1]

[1]: https://stackoverflow.com/questions/40247508/e-and-i-symbols-in-istanbul-html-reports
