### ISSUE TITLE
hardhat-deploy deployments.fixture() causes trouble with npx hardhat coverage

### ISSUE THREAD

**Issue by gitpusha** [sc-forks/solidity-coverage#617]
Hi @cgewecke , 

One of my test suites doesnt work with `npx hardhat coverage`. 

I use `npx hardhat coverage` and `hardhat-deploy` 's `deployments.fixture()`  in other repos as well without problem. 

But in this repo (private) the whole coverage suite fails and it seems to be related to the `beforeEach` `deployments.fixture()` 

![image](https://user-images.githubusercontent.com/36712489/108627456-fbc58480-7455-11eb-8e04-76f717d9f051.png)

The test suite runs fine without the coverage. 

With coverage, somehow the deployment process and maybe snapshot seems to be handled differently: 
![image](https://user-images.githubusercontent.com/36712489/108627527-5e1e8500-7456-11eb-8942-8b60b93e32e6.png)

The error I am getting clearly suggests that when I run the test suite with `npx hardhat coverage` somehow instead of reusing some deployed contract state it seems to rerun the deployment logic causing a revert in solidity because the state has already been intitialized. 

I can't wrap my head around why this only happens when I run `npx hardhat coverage` but not for my normal test runs with `npx hardhat test` . 

Any idea? 

```json
    "hardhat": "2.0.10",
    "hardhat-deploy": "0.7.0-beta.45",
    "hardhat-deploy-ethers": "0.3.0-beta.7",
    "solidity-coverage": "0.7.15"
```

**Comment by gitpusha** [comment]
Ok so now it works. 

I had a `coverage.json` file that I removed and when I reran it worked. 

However, coverage does not seem to work well for proxy contracts of course.

**Comment by vasek-code** [comment]
https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/4531
