### ISSUE TITLE
Selectively choose dependencies

### ISSUE THREAD

**Issue by gakonst** [sc-forks/solidity-coverage#625]
**Problem**

Currently when installing solidity-coverage, it pulls in web3, truffle provider, ganache-cli as well as other things which do not seem like they're used anywhere when e.g. used with only hardhat.

**Proposed Solution**

It'd be nice if the repo could be refactored in a way that it does not pull in additional dependencies that are not required

**Comment by cgewecke** [comment]
Hi @gakonst! Thanks for the suggestion. 

At the moment the tool ships with support for two plugins: Truffle and Hardhat. The dependencies you mention are necessary for the Truffle version. To eliminate them we'd need to publish plugins separately - so ... it would involve a change in the installation UX and increase maintenance overhead a bit.  Would probably migrate this project to a monorepo structure. 

I think that makes sense but maybe it would be good to list the tangible benefits of this change...what are they from your perspective?

**Comment by rmeissner** [comment]
Wouldn't it be nicer to have them as peer and dev dependencies, this would prevent that they are by default installed in all repos that use this nice project ;)

**Comment by paulrberg** [comment]
> I think that makes sense but maybe it would be good to list the tangible benefits of this change...what are they from your perspective?

[No more scrypt/ node-gyp errors/ warnings anymore](https://twitter.com/gakonst/status/1374725518117982218)!

May be worth it to consider the dev and peer deps approach.

**Comment by frangio** [comment]
My tangible benefit is faster installation times by reducing the total number of dependencies.

**Comment by frangio** [comment]
@cgewecke Can we revisit this? I've also opened https://github.com/sc-forks/solidity-coverage/issues/692 which is related but not exactly about dependencies.

**Comment by cgewecke** [comment]
@frangio #692 should definitely be done. ganache-cli shouldn't be a dependency here anymore either. 

`truffle-provider` is harder to remove from this though and I think that's where most of noise comes from.

**Comment by cgewecke** [comment]
Fixed in v8
