### ISSUE TITLE
Does not work with Solidity v0.8 "unchecked" blocks

### ISSUE THREAD

**Issue by paulrberg** [sc-forks/solidity-coverage#626]
# Description

Solidity v0.8 introduced [checked and unchecked arithmetic](https://docs.soliditylang.org/en/latest/control-structures.html#checked-or-unchecked-arithmetic).

I recently noticed that none of the code wrapped in my `unchecked` blocks is analysed by solidity-coverage. For instance, look at [line #149](https://coveralls.io/builds/38616686/source?filename=contracts%2FPRBMath.sol#L149) in Coveralls build no. 38616686 of my [prb-math](https://github.com/paulrberg/prb-math) repo:

<img width="1091" alt="Capture d’écran 2021-04-08 à 11 51 08" src="https://user-images.githubusercontent.com/8782666/113997338-b66fe180-9860-11eb-9bbb-72da20247d40.png">

None of the code inside is highlighted to reflect whether my tests hit those lines or not. In fact, I know of one line that definitely hasn't been reached by my tests, that is [line #230](https://coveralls.io/builds/38616686/source?filename=contracts%2FPRBMath.sol#L230) (and presumably this is also true of some of the many if branches in there).

# Environment

+ hardhat@2.1.1
+ prb-math@[f49d787](https://github.com/paulrberg/prb-math/commit/f49d787a1b9f5cf1dce2713afc60b4bbd4cf0c52)
+ solidity-coverage@0.7.16
+ solidity@0.8.3

**Comment by cgewecke** [comment]
@paulrberg Yes, makes sense. We need to add `unchecked` to the parse table and process it like other code blocks. 

Thanks for reporting.

**Comment by paulrberg** [comment]
Hey @cgewecke, is there any we could help you speed up development on this?

You may have heard about the [Gitcoin Grants](https://gitcoin.co/grants/) programme. You basically set up a profile, link it on GitHub and social media, then people can donate ETH and ERC-20 tokens.

I, and I'm sure [many others](https://twitter.com/PaulRBerg/status/1320003715986763777) too, would be happy to contribute to your grant.

**Comment by cgewecke** [comment]
@paulrberg Ah! Really sorry, this fell through cracks.... will look at this ASAP (and fix a few other things here)

Will look at grants, thanks!

**Comment by paulrberg** [comment]
Awesome.

**Comment by cgewecke** [comment]
Ok, weird.... I'll look at this again. Need to add a test for this syntax.

**Comment by cgewecke** [comment]
This is fixed in 0.7.21 (for real :) )

**Comment by paulrberg** [comment]
Amazing, thank you!
