### ISSUE TITLE
[TRUFFLE] Running ganache with a mainnet/testnet fork

### ISSUE THREAD

**Issue by haydenyoung** [sc-forks/solidity-coverage#628]
Hi,

When I run ganache-test I fork mainent/kovan so I can test various 3rd party oracles and defi projects. This works without trouble when using `truffle run test` which runs ganache-test `truffle run ganache-test`.

However, when I run solidity coverage, `truffle run coverage`, I get:

```
Error: Invalid JSON RPC response: ""
```

I noticed a similar issue https://github.com/sc-forks/solidity-coverage/issues/509 which seems very close to the problem I was having with forking mainnet/testnet.

So I added the required config to my solcover js file:

```
    client: require('ganache-cli'),
    providerOptions: {
        host: "localhost",
        port: 8545,
        network_id: "1234567890",
        gas: 6721975,
        networkCheckTimeout: 60000,
        fork: "https://eth-kovan.alchemyapi.io/v2/DjLaJSg4gNXdWfDmSufgzuFeRBs-2eRw",
        mnemonic: process.env.MNEMONIC
    }
```

but it doesn't really have any effect. I'm still getting:

```
Error: Invalid JSON RPC response: ""
```

or a different error:

```
TypeError: Cannot read property 'programCounter' of undefined
```

My understanding is that passing the same options to the ganache plugin should result in the same behaviour as if I run against ganache-test. However, perhaps I have my configuration wrong.

**Comment by haydenyoung** [comment]
I seem to have made some progress on this; I didn't realize I had to run the ganache cli I thought it would run with ganache test. My bad.

However, I'm now finding a different issue and it is very strange.

Firstly, when I run a development chain I fork kovan because I am testing some interactions with 3rd party contracts (mainly defi and oracles).

All my coverage tests run fine except when I test my contracts which call other contracts on Kovan. The strange thing is this:

When I call a 3rd party contract using Truffle's TruffleContract via JS I can interact with the contracts without problem. However when I call one my own contracts which calls the same 3rd party contract, the transaction is reverting.

So, it looks like the call to the 3rd party contract fails but only from my contract. I have verbose on ganache-cli but I'm not seeing any errors.

**Comment by haydenyoung** [comment]
I have created a small example of this issue which I hope will help with replication.

https://github.com/haydenyoung/metacoin

To install:

check out from git,
npm ci.

Make sure truffle and ganche-cli are installed.

Start up ganache-cli with a fork of kovan:

`npx ganache-cli -d -m "seed phrase" -f https://eth-kovan.alchemyapi.io/v2/DjLaJSg4gNXdWfDmSufgzuFeRBs-2eRw -v`

replacing seed phrase with what is configured in truffle-config.js.

Run tests to see a successful output:

`truffle test`

If everything is install correctly you should see successful output. I have just console.log(ged) the output but it should be bignumber.

Next, run:

`truffle run coverage`

This will result in a revert error which I am almost certain is a failure of the MetaCoin2 contract to contact the 3rd party chainlink contract. My expectation is that the MetaCoin2 contract should successfully communicate with the chainlink contract as it does above when running truffle test.

One other interesting thing is that I'm experiencing the same problem when integrating into a UI frontend using Vue.js. Same revert error.

One other thing is that this does not happen if I deploy two contracts from my project and have one communicate with the other.

If truffle test was breaking as well I would imagine there is some kind of abi issue. However, this seems quite inconsistent and I do not have this problem with truffle test but do with coverage and interacting with the contracts from a front end app.

**Comment by cgewecke** [comment]
solidity-coverage is no longer supporting ganache
