### ISSUE TITLE
Unable to pass man files to `--testfiles`

### ISSUE THREAD

**Issue by chiro-hiro** [sc-forks/solidity-coverage#631]
I'm try with:

```
npx hardhat coverage --solcoverjs ./.solcover.js  --testfiles "test/filea.ts test/fileb.ts"
npx hardhat coverage --solcoverjs ./.solcover.js  --testfiles "test/filea.ts,test/fileb.ts"
npx hardhat coverage --solcoverjs ./.solcover.js  --testfiles "test/filea.ts","test/fileb.ts"
```
None of them work, so I think something is possible to be wrong in these lines

https://github.com/sc-forks/solidity-coverage/blob/3c0f3a5c7db26e82974873bbf61cf462072a7c6d/plugins/resources/nomiclabs.utils.js#L18-L24

Might be, files need to be split first `files.split(',')`

**Comment by cgewecke** [comment]
@chiro-hiro The argument to `--testfiles` is processed by the globby package.  

[They have a syntax for what you're trying to do.][1].

Multiple named files can be specified using braces and a comma separated list. 
```
npx hardhat coverage --testfiles "{file1,file2,file3}"
```

[1]: https://github.com/sindresorhus/globby#globbing-patterns

**Comment by chiro-hiro** [comment]
@cgewecke Could you add that to document or README.md file :pray:

**Comment by cgewecke** [comment]
@chiro-hiro Yes, good idea.

**Comment by cgewecke** [comment]
f0aa876c3eaf2471a0141687df47c86649d02b10
