### ISSUE TITLE
Using `skipFiles` with `/` makes coverage file empty

### ISSUE THREAD

**Issue by transmissions11** [sc-forks/solidity-coverage#632]
Adding this `.solcover.js` file in [this project](https://github.com/rari-capital/nova)

```js
module.exports = {
  skipFiles: ["external/"],
};
```

Leads to a cover report file that looks like this:

<img width="1657" alt="Screen Shot 2021-05-15 at 3 06 34 PM" src="https://user-images.githubusercontent.com/26209401/118379434-24f63c80-b58f-11eb-9fb0-f03288063c53.png">

I have plenty of tests that result in much more coverage than this. Removing the skipFiles line will fill out the coverage report a lot more.

What's going on?

**Comment by TransmissionsDev** [comment]
Alright oddly enough if I configure a `.solcover.js` file like so:

```js
module.exports = {
  skipFiles: ["mocks", "external", "echidna"],
};
```

The remaining files still show coverage!

**Comment by amogh-jrules** [comment]
@TransmissionsDev Were you able to solve or pinpoint the issue? Facing the same problem on my end

**Comment by cgewecke** [comment]
Could you see if omitting the `/` on the folder string works? e.g. just
"myFolder" instead of "myFolder/"

**Comment by amogh-jrules** [comment]
@cgewecke Thanks for your prompt response
I am using it like this
```
    skipFiles : ["module/ModuleB.sol","./module/ModuleB.sol"]
```
And it results in the same issue described above

**Comment by cgewecke** [comment]
@amogh-jrules Out of curiosity does it work if you omit the path info there? 

Do you have solidity files with the same name under different folders and you'd like to skip one but not the other?

**Comment by amogh-jrules** [comment]
Yep, when I omit the path, it does show the coverage reports accurately and no, there are no name collisions. The main reason I am trying to skip certain contracts is because they belong on a different network and I am running coverage reports for another network.

**Comment by cgewecke** [comment]
@ivanzhelyazkov I know this is a bit confusing, but just don't use a trailing `/` to designate a folder with this option. 

This should work
```
skipFiles: ["interfaces", "test", "proxies", "libraries/ABDKMath64x64.sol"]
```

**Comment by ivanzhelyazkov** [comment]
Just tried this and it doesn't work:
`skipFiles: ["interfaces", "test", "proxies", "libraries/ABDKMath64x64.sol"]`

**Comment by cgewecke** [comment]
@ivanzhelyazkov What does your `contracts` folder look like? Have you verified that you're getting coverage without using skipFiles?

**Comment by ivanzhelyazkov** [comment]
My contracts folder is the following (omitting the names for brevity):
```
contracts/
 MainContract.sol
 SecondaryContract.sol
 interfaces/
  int1.sol
 libraries/
  lib1.sol
  lib2.sol
  lib3.sol
 proxies/
  proxy1.sol
  proxy2.sol
 test/
  test1.sol
  test2.sol
  test3.sol
  test4.sol
  test5.sol
```

When I run the coverage with the following skipFiles config:
`skipFiles: ["interfaces", "test", "proxies"]`
It works fine ; 
Showing MainContract.sol, SecondaryContract.sol, and the three contracts from libraries reports -
All the contract reports are > 90% coverage.

When I run the coverage with the following skipFiles config:
`skipFiles: ["interfaces", "test", "proxies", "libraries/ABDKMath64x64.sol"]`

It really skips the libraries/ABDKMath64x64.sol from the report, but:
It shows only SecondaryContract.sol's coverage report properly, 
while the other contracts' reports are shown to be "0%" covered on every test (Lines, Functions, etc.).

**Comment by nchamo** [comment]
Same thing is happening to me. If I specify a specific file, other files get a "0%"

**Comment by ivanzhelyazkov** [comment]
Found out the solution to this - you have to do a hardhat clean after adding the file, then run coverage.

**Comment by reynolkb** [comment]
i figured it out. you have to exclude `/contracts` since it knows to look there

```
module.exports = {
  skipFiles: ['./dependencies']
};
```

**Comment by fields93** [comment]
FYI I had the same issue, and solved it by running "npx hardhat clean" before re-running coverage as suggested by @ivanzhelyazkov

**Comment by gavinnewcomer** [comment]
> FYI I had the same issue, and solved it by running `npx hardhat clean` before re-running coverage as suggested by @ivanzhelyazkov

This should be done whenever changes are made to the skipFiles array.

**Comment by cgewecke** [comment]
Doing some issues cleanup prior to a release - this has been open a while, sorry. 

Will be tracking this problem at #860. The README has been updated to be clearer about using `hardhat clean` and what the format of skipFiles should be like.
