### ISSUE TITLE
"Callback was already called" - truffle run coverage

### ISSUE THREAD

**Issue by GAUTAMRAJU15** [sc-forks/solidity-coverage#633]
Package error

1. Hey there I installed the package locally using - `npm install solidity-coverage -D` .
2. Then I ran `truffle run coverage`.
3. It asked me to install `original-require` and `mocha` as dependencies. (image below)
4. I installed both packages, but now it gives me error - **`Callback was already called`**.

node version - `14.17.0 LTS`
npm version - `7.7.6`

<img width="532" alt="Screenshot 2021-05-17 at 1 56 43 PM" src="https://user-images.githubusercontent.com/13881992/118458369-4cc4dc00-b718-11eb-8c74-f1b36f9561a0.png">

<img width="491" alt="Screenshot 2021-05-17 at 1 56 35 PM" src="https://user-images.githubusercontent.com/13881992/118458378-4fbfcc80-b718-11eb-98d6-a134a7d6d5e6.png">

<img width="675" alt="Screenshot 2021-05-17 at 1 49 20 PM" src="https://user-images.githubusercontent.com/13881992/118455411-b04e0a00-b716-11eb-9f29-cd3030c781f2.png">

**Comment by cgewecke** [comment]
@GAUTAMRAJU15 

I think is caused by the version of ganache (included with solidity-coverage)  not working with Node 14. It needs to be upgrade (or removed altogether).

You should be able to get around this by adding a newer version of ganache as dependency to your project and adding this to `.solcover.js`

```js
module.exports = {
  client: require("ganache-cli"), // This will use ganache specified in your own dev dependencies
}
```

**Comment by GAUTAMRAJU15** [comment]
Thanks it worked out.
