### ISSUE TITLE
Fix ABIEncoder V2 compilation failures

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#636]
cf: [solidity 10354][1]

@dileepfrog discovered a way to configure the optimizer so stack too deep errors go away without stripping out the trace.
```
config.compilers.solc.settings.optimizer.enabled = false;
config.compilers.solc.settings.optimizer.details = {
  yul: true,
  yulDetails: {
    stackAllocation: true,
  },
};
```

**TODO**
- [ ] Check behavior across solc versions 

[1]: https://github.com/ethereum/solidity/issues/10354

**Comment by amalnathsathyan** [comment]
![image](https://user-images.githubusercontent.com/19988098/125230105-cd0d5500-e2f5-11eb-8193-5f6a77e5e357.png)
Still same error !! Any help ?

**Comment by washboardalex** [comment]
The above config change did not work for us, we are still experiencing this issue with compiler v0.7.5 and abi encoder v2.

**Comment by dileepfrog** [comment]
@amalnathsathyan @washboardalex You will need to make these changes to the solidity-coverage code itself, which overrides your project settings. For example, https://github.com/Float-Capital/solidity-coverage/commit/723ed39c13a5a8af524d0f82a0947bb21f06d08a#diff-21d7978b20ae71148e42ff520f3a63e74edba221f9285763d67eb1735d42fdbfR111

**Comment by cgewecke** [comment]
In `0.7.18` you can additionally specify any optimizer details via a `.solcover.js` config option. Have also added a little section to REAMDE FAQ docs with other configurations known to work. 

There's not much more we can do about this I think (unfortunately)
