### ISSUE TITLE
Hardhat network gas config is overridden

### ISSUE THREAD

**Issue by pilagod** [sc-forks/solidity-coverage#637]
I'm using solidity-coverage with hardhat. I found gas related fields defined in hardhat network config cannot apply to tests. And I saw this function is called when setting up hardhat network:

https://github.com/sc-forks/solidity-coverage/blob/f0aa876c3eaf2471a0141687df47c86649d02b10/plugins/resources/nomiclabs.utils.js#L125-L130

Default gas limit on `API` object is a bit too high for me (`0xffffffffff` = `1099511627775`), which causes some transactions in my tests are blocked by hardhat beforehand because `gasLimit` * `gasPrice` is greater than account balance.

I think we should just take values directly from config, let the network and user to decide what they actually need. 
 I wonder if there are other reasons that this function is serving for. If not, I think we can just remove this, I can make a PR to do this. Thanks 😃

**Comment by cgewecke** [comment]
@pilagod Can you get around this by increasing your default account balances in the config? 

It's a bit tricky to let people configure the gas here because for each case like yours there are many others where the config has preset gas values which are inappropriate for coverage and people OOG.

**Comment by pilagod** [comment]
@cgewecke Thanks for your reply 😃

I think I didn't express my thought clearly. What I mean is not to configure gas in the code, but in hardhat config. Current implementation will make hardhat config take no effect.

For example, given a hardhat config `hardhat.config.js`:

```js
module.exports = {
  networks: {
    hardhat: {
      // ...
      gas: 100000
    },
  }
}
```

With this setting, I expect my tests are running with gas limit `100000`, but the function `configureHardhatEVMGas` will always override it to `0xffffffffff`.

So I am wondering if there is any reason to hardcode gas information there. If not, I think it's better to just use the network config instead of constant values.

**Comment by cgewecke** [comment]
Yes, that's exactly the issue... people set gas limits in their config for lots of reasons, but only high gas limits work for coverage. 

I think we'd need to make gas configurable in a way that was coverage specific (maybe in `.solcover.js`) rather than lift it by default from the network settings

**Comment by pilagod** [comment]
@cgewecke No apology, you already do a great work! Thanks for your efforts devoting to this project. 💪

For my project I found default network config is enough, I will temporarily fork a copy to relax this limitation, and look forward to future update. 😃
