### ISSUE TITLE
Executing `hardhat coverage` throws "typechain_1.glob is not a function"

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#644]
I've reported this at https://github.com/nomiclabs/hardhat/issues/1672, but it is not clear and what side the problem is (HH or SC).

Can you please take a look?

Some more findings are reported further down that post, namely, about the need to set `taskArgsStore.noTypechain = true` somewhere (perhaps via HH and/or SC configuration files).

Thanks.

**Comment by cgewecke** [comment]
It looks like this was a typechain thing, sorry @barakman (hope all's well).
