### ISSUE TITLE
InvalidInputError: sender doesn't have enough funds to send tx.

### ISSUE THREAD

**Issue by SvenMeyer** [sc-forks/solidity-coverage#648]
tests runs fine without coverage, but when using coverage I get a strange error.

```
  1) 1_Whitelist.ts =================================================================

       "before all" hook for "set hasWhitelisting to true":
     InvalidInputError: sender doesn't have enough funds to send tx. The upfront cost is: 8796093022200000000000 and the sender's account only has: 2000000000000000000
      at TxPool._validateTransaction (node_modules/hardhat/src/internal/hardhat-network/provider/TxPool.ts:426:13)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at runNextTicks (internal/process/task_queues.js:66:3)
      at listOnTimeout (internal/timers.js:523:9)
      at processTimers (internal/timers.js:497:7)
      at TxPool.addTransaction (node_modules/hardhat/src/internal/hardhat-network/provider/TxPool.ts:102:5)
      at HardhatNode._addPendingTransaction (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1103:5)
      at HardhatNode._mineTransaction (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1111:5)
      at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1379:18)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:105:18)

```

strangely it looks like as if it depends on how I deploy the contract ...

https://github.com/paulrberg/solidity-template/discussions/50#discussioncomment-1085160

**Comment by wei3erHase** [comment]
ey yo @SvenMeyer , do you have an insight on what's the best way of deploying for coverage?

**Comment by 0xdavinchee** [comment]
any luck on this @SvenMeyer @wei3erHase ?

**Comment by wei3erHase** [comment]
@0xdavinchee I discovered that the hardhat network config is very different on the `networks` parameter, than the `gasReporter` config (for instance, if you need `allowUnlimitedContractSize: true` you have to set it on the gasReporter config). 

Even though, @SvenMeyer appears to be having an error on the deployment, as 2ETH are not enough to cover the tx.I don't remember right now what I was looking for here, what's your error?

**Comment by 0xdavinchee** [comment]
I'm trying to run coverage tests using hardhat + hardhat-truffle5 and I'm getting the same error as @SvenMeyer. The tests run fine when it's not running coverage.

**Comment by 0xdavinchee** [comment]
@wei3erHase it was a pretty weird bug, I had to estimate gas w/ web3 and input that into the sendTransaction call and it fixed it 🤷🏼

**Comment by wei3erHase** [comment]
@0xdavinchee when a tx is expected to revert (doesn't mean it will tho), hardhat cannot estimate the gas and you need to hardcode it :(

**Comment by b1acKr0se** [comment]
I'm having the same issue. It doesn't even show which line the problem occurs, so with a large test file it is very hard to debug.

**Comment by b1acKr0se** [comment]
I just wonder if it has anything to do with signer that is dynamically created (`ethers.Wallet.createRandom().connect(ethers.provider)`) because with this kind of signer I have to supply a value to `gasLimit`, otherwise it will set the `gasLimit` to be the upfront cost calculated from the blockGasLimit in hardhat config. It doesn't seem to be the case with signer generated from `ethers.getSigners()`.

**Comment by sirpy** [comment]
it seems to be related to ethers.Wallet.createRandom().connect(ethers.provider)
adding gaslimit and gasprice settings doesnt help

**Comment by rtentser** [comment]
For me it seems to fail on mint

Strangely, the same mint works perfectly, when called from inside another contract

Tests without coverage work fine

**Comment by mai1015** [comment]
any update yep, it happend to me as well. 
[[mai101
5/hardhat-starter-kit]](https://github.com/mai1015/hardhat-starter-kit/actions/runs/3924688953)
this shold give more info

**Comment by cgewecke** [comment]
Doing some issues cleanup prior to a new release and closing this.

In the latest version the `--network` flag triggers an error and advises people that the coverage tool only runs on the HardhatEVM network

`network` was really designed to support the ganache client which was able to listen on a port. It's deprecated and the plugin hasn't worked with it for a long anyway. 

Please just ping if you continue to run into this issue.

**Comment by VanijaDev** [comment]
> Edit: I found what was the problem in my case.
> 
> In my `hardhat.config.ts`, I set the `defaultNetwork` to `polygon_mumbai`. But from what I understand, the tests have to run on the hardhat local network.
> 
> So, while keeping the `defaultNetwork` in my config, I had to specify in my command that I want to use the hardhat network: `npx hardhat coverage --network hardhat`

Yes!!! Thank you!
