### ISSUE TITLE
Causes problems with Diamond facets

### ISSUE THREAD

**Issue by cliffhall** [sc-forks/solidity-coverage#649]
Briefly, the [Diamond Multi-Facet Proxy](https://eips.ethereum.org/EIPS/eip-2535) is a fine-grained proxy. It allows function selectors from multiple implementation contracts to be invoked with `delegatecall` rather than sending all unimplemented calls to a single implementation contract.

This pattern leans heavily on keeping track of which function selectors go with which contract. The developer must take care to make certain that proxied function selectors are unique across all facet contracts. 

When adding a facet to a Diamond proxy, the developer passes in a list of function selectors that should be proxied by the given implementation contract. On the JS side, when deploying, we just get the function selectors from the deployed facet and remove any selectors we don't want proxied. For instance, `supportsInterface(bytes4)` is one that is often implemented by several contracts in a system, but when you put them all behind a Diamond, you want to be certain which one is going to answer that call, and ignore the existence of all the others.

So that works fine and well, except for when it comes to running tests with `solidity-coverage`.  Apparently it is adding some instrumentation selectors that are present on all the facets. Since our unit tests don't take these unexpected function selectors into account, suddenly the unit tests dealing with adding new facets breaks because we're trying to add the same selector for multiple facets. 

Clearly the workaround at the moment will be for us to do a little diagnostic display and figure out which selectors are added by `solidity-coverage`, and remove them from the list we're about to try and add to the Diamond. That will work for me, but as Diamond adoption grows, when multiplied across all the folks who'll be deploying this advanced contract architecture and seeking 100% confidence in it, seems... heavy. 

I'd don't have a ready solution to offer here. A first help might just be documentation that enumerates all the function selectors that are added during instrumentation. Maybe next would be some function we could call with a contract to get those instrumentation selectors handed back to us in an array. We'd only want to do this is coverage is running, the function would need to be aware of that.

**Comment by mudgen** [comment]
Multiple people have reported problems using coverage with diamonds.  If diamond support or tooling were added to/for solidity-coverage it would be used by people.

**Comment by cgewecke** [comment]
@cliffhall 

If you have a chance, could you see if the change in PR #660 resolves your test failures?  (It restricts the instrumentation fns to `internal` visibility as long as they are contract (rather than file) scoped).

Have published the branch at tag `eip165` so ...
```
yarn add solidity-coverage@eip165 --dev
```

**Comment by cliffhall** [comment]
Wooohooo!!! @cgewecke that fixed it! Thanks so much!
<img width="723" alt="Screen Shot 2021-08-28 at 11 50 27 AM" src="https://user-images.githubusercontent.com/871933/131223479-a0c5206e-97c8-430d-ae36-d060cf0a6562.png"><img width="722" alt="Screen Shot 2021-08-28 at 11 49 25 AM" src="https://user-images.githubusercontent.com/871933/131223449-162be3ef-a498-4313-9c00-207fc9a862ad.png">

**Comment by cgewecke** [comment]
Okay awesome, thank you!

**Comment by failfmi** [comment]
Hey, is there a fix available in any of the `solidity-coverage` versions? cc @cgewecke

**Comment by cgewecke** [comment]
Yes, just published this (literally) 30 seconds ago: `0.7.18`

Let me know if it doesn't work.

**Comment by failfmi** [comment]
Literally speechless. You rock, sir

**Comment by failfmi** [comment]
@cgewecke, literally speechless. You rock, sir!

**Comment by cgewecke** [comment]
`0.7.18`
