### ISSUE TITLE
Make a gist / guide for setting up with CI 

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#65]
For robustness, recommend:

+ Using afterscript
+ Using sudo: required
+ Using a shell script that launches testrpc / setting norpc to true (copy zeppelin)

**Comment by maurelian** [comment]
This would be fantastic, I've been thinking about how the process should become more automated. 

One small thing is that the html output seems a bit heavy, so it would be very good to encourage adding it to the `.gitignore`.

**Comment by cgewecke** [comment]
@maurelian Yes, good idea. Making a note to myself here that this should probably be a doc in the repo that people can open PRs on and expand for their case. I have a clear sense of how to install on TravisCI but not CircleCI for example.

**Comment by maurelian** [comment]
Yeah, the readme is getting a bit unwieldy, I'd probably be more likely to submit PRs if it was clear where to put them. 

I really like how [WeiFund structure their docs](https://github.com/weifund/weifund-contracts).

**Comment by cgewecke** [comment]
Yes agreed. Thanks for the WeiFund link - that's a great model.
