### ISSUE TITLE
[truffle] Coverage fails if linking libraries deployed on previous migration

### ISSUE THREAD

**Issue by An-dz** [sc-forks/solidity-coverage#654]
With Truffle, if you have the libraries deployed on one migrations file and then try to link the libraries with a contract on a subsequent migrations file, _solidity-coverage_ will fail.

This does not happen without coverage. Tests and live deployments work with this type of linking without problems.

There's no error message, just the stack trace but it fails when trying to link the stuff `@solc/linker.js:29`:
```js
throw new Error('Invalid address specified for ' + libraryName);
```

Here's a very simple test case:

`test.sol`:
```solidity
pragma solidity >=0.4.0;
library TestLib {
    function test() external {
        require(msg.sender == address(0), "LOL");
    }
}
contract Test {
    function test() external {
        TestLib.test();
    }
}
```

`2-libs.js`:
```js
const TestLib = artifacts.require("TestLib");
module.exports = async function (deployer, network, accounts) {
    await deployer.deploy(TestLib);
};
```

`3-contract.js`:
```js
const TestLib = artifacts.require("TestLib");
const Test = artifacts.require("Test");
module.exports = async function (deployer, network, accounts) {
    await deployer.link(TestLib, Test);
    await deployer.deploy(Test);
};
```

## Versions:
**solidity-coverage**: 0.7.16 & 0.8.0-beta.0
**solc**: 0.8.7
**truffle**: 5.4.5

**Comment by eli1combo** [comment]
Is there any update on this problem? I also encountered this problem in the latest version(v0.8.0-beta.1). How do I fix it?

**Comment by An-dz** [comment]
@eli1combo The only way right now is to link the libraries in the same migrations file where you deploy them.

**Comment by cgewecke** [comment]
Truffle related, closing
