### ISSUE TITLE
TestRPC race condition

### ISSUE THREAD

**Issue by cag** [sc-forks/solidity-coverage#66]
I think there is a race condition causing the test command to fail when TestRPC is not ready to accept requests by the time the tests begin making them. I was able to possibly address this via a workaround. 

For more context, see the following Travis builds:

https://travis-ci.org/gnosis/gnosis-contracts/builds/253195228

https://travis-ci.org/gnosis/gnosis-contracts/builds/253307021

And this commit:

https://github.com/gnosis/gnosis-contracts/pull/21/commits/4606bb42807e4a58a638cbbcf2346949ceb17d58

**Comment by cgewecke** [comment]
@cag Awesome, thank you - that issue & how to resolve has been a source of no end of bewilderment. 

Do you have any objections to or thoughts about us cannibalizing the logic in run-with-testrpc that verifies testrpc started and returns a promise for internal use in `exec.js`?  ( Would credit you of course :smile: ) 

Adding run-with-testrpc as dep here is a possible way forward too but I'd like to have `exec.js` be as modular and flexible as possible. . . its refactor is under consideration at issue #20. 

Also, if you are in the mood to open a PR you are more than welcome to.  No obligation though.

**Comment by cag** [comment]
Thanks, yeah it is nuts yo. I dunno why allEventsFired didn't write when I
did this. I can open a PR though.

**Comment by cgewecke** [comment]
Ok perfect. Thanks man.
