### ISSUE TITLE
Number of uncovered lines

### ISSUE THREAD

**Issue by cbunnydev** [sc-forks/solidity-coverage#666]
The coverage result only shows 3 uncovered lines. Can I get all uncovered lines not only 3?

**Comment by cgewecke** [comment]
Could you go into a lot more detail about which lines you expect to be uncovered? Is there a way to reproduce what you're seeing?

**Comment by cgewecke** [comment]
Closing because no response & to protect repo from supernatural malevolence.

Please just ping if you continue to have problems getting a coverage measurement...
