### ISSUE TITLE
Is there anyway to exclude files instead of skipping files?

### ISSUE THREAD

**Issue by superical** [sc-forks/solidity-coverage#668]
I have added my mocks in the `skipFiles` in my config:
```
module.exports = {
  skipFiles: ['mocks']
};
```

It seems like there is an issue with adding `mocks` to `skipFiles` in that any lines of codes that were ran _through_ the mocks will not be counted to the coverage. So, if a mock `A.method` is calling an actual implementation `B.method`, the `B.method` will not be instrumented by the coverage because `A.method` is skipped. This will result in is a much lower coverage metric because anything ran through the mocks are not counted. 

Is this an issue or intended by design?

Perhaps what I needed is just excluding the mocks from the results instead of "skipping" them, but is this achievable in the config?

**Comment by cgewecke** [comment]
> any lines of codes that were ran through the mocks will not be counted to the coverage

This should not be the case. You might have missing coverage if you're using `hardhat_reset` in your test suite somewhere (If so see [#574 comment][1] for a workaround) 

If not could you provide a simple way to reproduce the issue? 

(An example of a repo that uses mock contracts extensively and skips measuring them without problems is [open-zeppelin][2])

[1]: https://github.com/sc-forks/solidity-coverage/issues/574#issuecomment-856330142
[2]: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/.solcover.js

**Comment by superical** [comment]
@cgewecke I've created an example repo to illustrate my issue and easier for you to test the issue You can clone from https://github.com/superical/solidity-coverage-mock and run hardhat coverage to see. You can check out my [config file](https://github.com/superical/solidity-coverage-mock/blob/master/.solcover.js) too.

When I don't add `mocks` to `skipFiles`, I get a full coverage:
![image](https://user-images.githubusercontent.com/2247766/135515203-1edc1c2b-072d-4a09-8de3-d43cd4321ebb.png)

But when I add `mocks` into `skipFiles`, my coverage has gone down by quite a bit in all categories:
![image](https://user-images.githubusercontent.com/2247766/135515333-4cc763c3-52db-4ca0-8a5e-fb1591a76cc2.png)

That's how I thought perhaps skipping the mocks made the lines that were called through them got excluded. Should adding files to `skipFiles` reduced the coverage?

**Comment by cgewecke** [comment]
Thanks for the reproduction! Great.

The issue is related to Hardhat's lazy compilation preserving artifact state while you change your configuration.  

If you run `npx hardhat clean && npx hardhat coverage` you should see perfect coverage for the skipped case as well.

(This is what I saw when I first cloned and ran the repo...)
![Screen Shot 2021-09-30 at 12 16 14 PM](https://user-images.githubusercontent.com/7332026/135517656-62323360-9270-4e66-b3de-89f5c91da40e.png)

**Comment by superical** [comment]
Awesome! It works now with your suggestion to add the cleaning! Thank you so much for the great work!😀
