### ISSUE TITLE
compile failure with sol 0.8.x custom errors

### ISSUE THREAD

**Issue by thetechnocratic** [sc-forks/solidity-coverage#672]
When compiling a contract that uses custom revert errors (sol ^0.8.4) solidity-coverage errors out with the following:
`Error in plugin solidity-coverage: Error: Could not instrument: MyContract.sol. (Please verify solc can compile this file without errors.) mismatched input '(' expecting {';', '='}`

compiling normally does not throw an error, so it seems solidity-coverage is using something different under the hood.

**Comment by cgewecke** [comment]
This should be resolved now.
