### ISSUE TITLE
Skipfiles produces random results

### ISSUE THREAD

**Issue by Dellybro** [sc-forks/solidity-coverage#674]
Hello,

My .solcover file looks like the following

```
module.exports = {
  skipFiles: [
    'abstracts',
    'accelerator/Accelerator.sol',
    'accelerator/Random.sol',
    'enums',
    'interfaces',
    'libs',
    'recovery',
    'test',
    'Airdrop.sol',
    'Token.sol',
  ],
};
```

And when i run `yarn coverage` I get the following results

<img width="618" alt="Screen Shot 2021-10-22 at 5 48 35 PM" src="https://user-images.githubusercontent.com/10732096/138535936-6d29120f-57a2-4049-8abe-75d095710069.png">

But when i remove `accelerator/Accelerator.sol` and `accelerator/Random.sol` from my skipfiles i get the following result

<img width="614" alt="Screen Shot 2021-10-22 at 5 49 11 PM" src="https://user-images.githubusercontent.com/10732096/138535958-d3cb527a-335d-497a-be7d-d5a4d6176154.png">

Not sure why coverage isn't letting me skip those 2 files without produces random results as shown above.

**Comment by JChanceHud** [comment]
Have a look at this issue, it solved the problem for me.

https://github.com/sc-forks/solidity-coverage/issues/668

**Comment by cgewecke** [comment]
Am going to track this problem at #680 going forward. Thanks for opening.
