### ISSUE TITLE
Revert when processing transaction 

### ISSUE THREAD

**Issue by AdamK222** [sc-forks/solidity-coverage#677]
In my ganache I have deployed Uniswap clone. I'm trying to run coverage but keep getting following error after all tests passed:

`Error: while migrating XXX: Returned error: VM Exception while processing transaction: revert`

In smart contract I have imports for @openzeppelin and @uniswap interfaces and contracts so I've created .solcover.js file:

```
module.exports = {
  copyNodeModules: true
}
```

Error doesn't appear when I'm not connecting my testing contract to Uniswap clone in ganache. I think error is related to this thing. Am I doing something wrong on testing ? Should I somehow include Uniswap's clone contracts to solidity-covarage even if I don't want to test them ?

Solc: 0.8.7, Optimizer: Yes with 200 runs
solidity-coverage: ^0.7.17
Truffle v5.4.16 (core: 5.4.16)
Node v12.18.4

**Comment by AdamK222** [comment]
Ok I think that I found an error in my code which is causing solidity coverage to fail. Is there any way to force solidity coverage to run its logic on ganeche server, not on its own server ?

**Comment by cgewecke** [comment]
@AdamK222 No ... to track execution it needs to hook into ganache's VM within it's own process. 

However, you should be able to configure solidity-coverage's ganache instance identically with the ganache you're launching at command line via the `providerOptions` option. These are ganache-core options passed to the internal server. You'll also want to tell solidity-coverage to use the same client you use for your regular tests by setting the `client` option to something like `require('ganache-cli')` 

There's more about this in the README options section

**Comment by cgewecke** [comment]
Closing for now. Please just ping if you're still having issues with this.
