### ISSUE TITLE
Detect when Hardhat `coverage` task is running

### ISSUE THREAD

**Issue by ItsNickBarry** [sc-forks/solidity-coverage#678]
Is there any recommended method for detecting when `test` or `compile` is being run internally by the `coverage` task?  If not, is there a clear path towards adding support for this (nothing immediately comes to mind)?

I have two plugins that would be better off disabled when `coverage` is running, because the code modifications affect their output:
https://github.com/ItsNickBarry/hardhat-contract-sizer/issues/8
https://github.com/ItsNickBarry/hardhat-abi-exporter/issues/30

**Comment by cgewecke** [comment]
Hi @ItsNickBarry :) 

Right, makes sense. I guess we'd need to set a variable on the global env when the coverage task starts that other plugins can read.

**Comment by cgewecke** [comment]
In `0.7.18`, have begun setting a variable `__SOLIDITY_COVERAGE_RUNNING` on the `hre` when the coverage task starts. 

Just lmk if this approach isn't suitable / doesn't work on your end. Thanks Nick!

**Comment by ItsNickBarry** [comment]
This will work.  I would prefer a more generalized solution, but that would have to be built into Hardhat somehow, and is probably fundamentally incompatible with the task override system.  I'll update my plugins to use this, thanks.
