### ISSUE TITLE
How to use a custom mnemonic during solidity coverage test

### ISSUE THREAD

**Issue by leykun10** [sc-forks/solidity-coverage#679]
I have a contract that implements EIP712 signature type and I have written a test that uses a private key to sign structured data. so I need to know the private keys prior to the test, to solve this problem i always instantiate ganache-cli with a custom mnemonic with -m flag so i can have a consistent account. How do i configure solidity coverage to use my mnemonic during testing. Thanks In Advance.

**Comment by cgewecke** [comment]
Hi, @leykun10. You can do this using by configuring ganache with `providerOptions` in `.solcover.js`. (See the README)

These options are expected to be formatted for `ganache-core` (which uses different parameter conventions than ganache-cli). 

They're described in the ganache docs here:
https://github.com/trufflesuite/ganache/tree/master#options
