### ISSUE TITLE
Relative path prefix args to --testfiles throw mocha error

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#684]
"./test/*.ts" will throw at the end of a successful test run. Presumably the filter doesn't work either.

```
Error in plugin solidity-coverage: Error: Cannot find module './test/myfile.ts'
Require stack:
- /Users/cgewecke/code/solidity-template/node_modules/mocha/lib/mocha.js
```

This can be worked around by removing the relative path prefix, e.g "test/*.ts" is ok.

cf: [hardhat issue 2276][1]

[1]: https://github.com/nomiclabs/hardhat/issues/2276

**Comment by Codonyat** [comment]
Oaaaahhhh, I was getting crazy about this. Spent whole day installing and removing packages.

**Comment by cgewecke** [comment]
Not sure what the problem was here but I can't reproduce it locally or in the integration tests anymore. This works
```
npx hardhat coverage --testfiles ./test/something.ts
```
