### ISSUE TITLE
Add coverage thresh hold? 

### ISSUE THREAD

**Issue by liron-navon** [sc-forks/solidity-coverage#686]
Add coverage thresh hold? 

How come there is no threshold? this is just something we need to pass to istanbul as a variable

**Comment by cgewecke** [comment]
Issue #610 contains a recipe for getting istanbul do this at the command line after coverage runs.


(If that issue covers what you're looking for, could you close this as a duplicate?)

**Comment by cgewecke** [comment]
Closing for now, just ping if you'd like this re-opened.
