### ISSUE TITLE
evm_setNextBlockTimestamp not supported

### ISSUE THREAD

**Issue by vrde** [sc-forks/solidity-coverage#687]
I have tests that set the block timestamp to an arbitrary value. These tests pass when I run them with `npx hardhat test`, but when I run them for test coverage I get this error: `ProviderError: Method evm_setNextBlockTimestamp not supported.`

Any idea on how to handle this?

My dependencies:

```
{
  "devDependencies": {
    "@ethersproject/providers": "^5.5.3",
    "@nomiclabs/hardhat-ethers": "^2.0.4",
    "@nomiclabs/hardhat-etherscan": "^3.0.0",
    "@typechain/ethers-v5": "^9.0.0",
    "@typechain/hardhat": "^4.0.0",
    "@typechain/truffle-v5": "^7.0.0",
    "@types/chai": "^4.3.0",
    "@types/chai-as-promised": "^7.1.4",
    "@types/mocha": "^9.1.0",
    "@types/node": "^17.0.15",
    "chai": "^4.3.6",
    "chai-as-promised": "^7.1.1",
    "dotenv": "^16.0.0",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.5.4",
    "hardhat": "^2.8.3",
    "hardhat-gas-reporter": "^1.0.7",
    "solidity-coverage": "^0.7.18",
    "ts-node": "^10.4.0",
    "typechain": "^7.0.0",
    "typescript": "^4.5.5"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^4.4.2"
  }
}
```

**Comment by cgewecke** [comment]
Hi @vrde,

That's surprising. Coverage shouldn't have any effect on what methods the provider supports. 

Is it possible you're accidentally connecting to a non-hardhat client when running the coverage command?

e.g if you try `npx hardhat coverage --network hardhat` (just to be explicit) do you still get this error?
