### ISSUE TITLE
Reduce package size (at least for Hardhat plugin)

### ISSUE THREAD

**Issue by frangio** [sc-forks/solidity-coverage#692]
The package includes two large files related to Truffle in `plugins/resources` (`truffle.library.js` and `truffle.library.js.map`) which together weigh almost 40Mb. These two files amount to 99% of the package size (!) (not counting dependencies), yet they are not necessary when used as a Hardhat plugin.

See https://github.com/sc-forks/solidity-coverage/issues/625 for a related issue about dependencies.

**Comment by cgewecke** [comment]
Yes these should definitely go.

**Comment by cgewecke** [comment]
Removed these with `0.7.20`

Provisionally, I think I will cease Truffle support here since the plugin has stopped working with the latest major version of Ganache. It's no longer able to hook into ganache internals due some to TS private variable restrictions. 

Will track this via #694
