### ISSUE TITLE
Doesn't work with Ganache 7.0

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#694]
Some ganache internals have been made private... plugin crashes with:

```
> UnhandledRejections detected
Promise {
  <rejected> TypeError: Cannot read private member from an object whose class did not declare it
      at __classPrivateFieldGet (/home/circleci/project/metacoin/node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:10:94)
      at close (/home/circleci/project/metacoin/node_modules/ganache/dist/node/webpack:/Ganache/core/lib/src/server.js:221:13)
      at /home/circleci/project/metacoin/node_modules/solidity-coverage/node_modules/pify/index.js:32:6
```

**Comment by cgewecke** [comment]
Would need to begin using the new provider event api:

https://github.com/trufflesuite/ganache/tree/develop/src/packages/ganache#ganache-provider-events

**Comment by sra122** [comment]
@davidmurdoch @cgewecke  How did this issue of "Cannot read private member from an object whose class did not declare it" is resolved. Could you please help me in that. I'm exactly on the same issue.

**Comment by RahulChoudhary888** [comment]
> solidity

you get solution or not??

**Comment by arithmetric** [comment]
Have you tried the beta version [described here](https://github.com/sc-forks/solidity-coverage/issues/700#issuecomment-1081367102)?

I was encountering the error `TypeError: Cannot read private member from an object whose class did not declare it` and it was fixed by upgrading to `solidity-coverage` version `0.8.0-beta.1`.

**Comment by cgewecke** [comment]
@davidmurdoch Apologies, i'll have time to take a look this week.

**Comment by johnnyshankman** [comment]
> Have you tried the beta version https://github.com/sc-forks/solidity-coverage/issues/700#issuecomment-1081367102?
>
> I was encountering the error TypeError: Cannot read private member from an object whose class did not declare it and > it was fixed by upgrading to solidity-coverage version 0.8.0-beta.1.

This just results in it using a backup legacy version of `ganache-cli` which is deprecated.

```
⚠️  There was a problem attaching to the ganache VM.
⚠️  For help, see the "client" & "providerOptions" syntax in solidity-coverage docs.
⚠️  Using ganache-cli (v2.13.2) instead.
```

@arithmetric

**Comment by johnnyshankman** [comment]
Ran into this today using `ganache` at `^7.0.0`

**Comment by magiconch** [comment]
Ran into this today using ganache at ^7.3.2

**Comment by davidmurdoch** [comment]
@cgewecke, we'd love to help here! Can you point us in the right direction to get the work done?

**Comment by monperrus** [comment]
FTR, tried today with Ganache 7.4.3, same issue.

**Comment by davidmurdoch** [comment]
@cgewecke, we'd still love to help here! Can you point us in the right direction to get the work done?

**Comment by v-pcode** [comment]
> > Have you tried the beta version [#700 (comment)](https://github.com/sc-forks/solidity-coverage/issues/700#issuecomment-1081367102)?
> > I was encountering the error TypeError: Cannot read private member from an object whose class did not declare it and > it was fixed by upgrading to solidity-coverage version 0.8.0-beta.1.
> 
> This just results in it using a backup legacy version of `ganache-cli` which is deprecated.
> 
> ```
> ⚠️  There was a problem attaching to the ganache VM.
> ⚠️  For help, see the "client" & "providerOptions" syntax in solidity-coverage docs.
> ⚠️  Using ganache-cli (v2.13.2) instead.
> ```
> 
> @arithmetric
> 
> I have this issue currently as well. My two options are pin `ganache` to an older version or as the above states, use the beta which fallsback to deprecated ganache-cli 2.13.2.

Did it work with any option?

**Comment by cgewecke** [comment]
RIP ganache.

**Comment by davidmurdoch** [comment]
Sad day.

**Comment by monperrus** [comment]
FTR, alternative solution, coverage with Foundry: 
https://book.getfoundry.sh/reference/forge/forge-coverage
