### ISSUE TITLE
Error in plugin solidity-coverage: TypeError: Cannot read properties of undefined (reading 'settings')

### ISSUE THREAD

**Issue by matejdrazic** [sc-forks/solidity-coverage#695]
After following steps listed [here](https://github.com/sc-forks/solidity-coverage) to add solidity-coverage to my project, this includes installing the package and then adding require to my hardhat.config.js file. I get this error '**Error in plugin solidity-coverage: TypeError: Cannot read properties of undefined (reading 'settings')**' every time I try to run coverage. Any previous experiences with this?

**Comment by cgewecke** [comment]
@matejdrazic Could you share your hardhat config and the complete stack trace of your error?

**Comment by matejdrazic** [comment]
Hi @cgewecke, thanks for replying!
Here is the full stack trace: ![slika](https://user-images.githubusercontent.com/73230692/154298689-b3281626-8737-4b7b-9226-2349906a684f.png)
and here are my hardhat configs:
`module.exports = {
  solidity: "0.8.0",
  paths: {
    tests: "./test", 
    cache: "./cache",
    artifacts: "./artifacts"
  },
  networks: {
    hardhat: {
      accounts: {
        count: 127
      }
    }
  },
  gasReporter: {
    currency: 'USD',
    gasPrice: 21,
    coinmarketcap: process.env.COINMARKETCAP_API_KEY,
  },
};`

**Comment by cgewecke** [comment]
@matejdrazic Could you see if the error goes away when you define the `solidity` part of your config in this format, like:
```
 solidity: {
    version: "0.8.0",
    settings: {
      optimizer: {
        enabled: true,
        runs: 1000,
      },
    },
  },
```

**Comment by matejdrazic** [comment]
@cgewecke Changing my solidity part of the code did not work unfortunately.
I'm using 2.8.4

**Comment by matejdrazic** [comment]
@cgewecke Yes, I've tried with several previous versions such as 2.5.0, 2.4.1 etc. but it still throws the same error.

**Comment by cgewecke** [comment]
I'm sorry I can't reproduce this locally - is your project public or do you have a simple reproduction case?

**Comment by matejdrazic** [comment]
Ok, so I think I know where the problem was. I had several hardhat.config.js files that were basicly named hardhat.configv[compiler version number].js since there were contracts that needed different compiler versions so that's why I needed several config files. 
Is there a way to use custom config in the parameters when running coverage?

**Comment by cgewecke** [comment]
solidity-coverage just inherits the config from hardhat... 

Hardhat supports some very granular compiler configuration options including using different compilers for different files... you should be able to do what you want from a single hardhat.config:

https://hardhat.org/guides/compile-contracts.html

**Comment by matejdrazic** [comment]
Ok great, this is the answer to my problems. Thank you very much!
