### ISSUE TITLE
allow to ignore modifiers, that are difficult to completely cover...

### ISSUE THREAD

**Issue by liron-navon** [sc-forks/solidity-coverage#697]
For example, we use the ReentrancyGuard from OpenZepplin, we use the "nonReentrant" modifier, the function itself works, but the modifier is considered as a branch, so I still cannot get 100% coverage, I cannot test this branch through hardhat, can we have a way to "skipModifiers: string[]" or something like that in the config? it would be useful for modifiers we use for protection against hackers but are very difficult to actually test.

If you know how to actually test for reentrant on hardhat that would be nice because I didn't find a way.

<img width="446" alt="Screenshot 2022-02-24 at 10 26 33" src="https://user-images.githubusercontent.com/18119833/155496573-3bdc7fd8-5b03-4b4d-9d45-c58cc6bd96df.png">

**Comment by barakman** [comment]
First of all, ignoring execution paths is pretty much against the purpose of this tool to begin with.

Second, if you have no way of testing a modifier applied on some function, then that modifier is obviously redundant there.

For example, when you use both `nonReentrant` and onlyOwner` in the same function, then it **might be** impossible to test the `nonReentrant` modifier (I haven't verified it, but it is possibly the case). But therefore, the `nonReentrant` modifier is not needed on that function.

Third, testing the `nonReentrant` modifier on some function is generally easy, provided that this function calls the function of another contract. All you need is a helper contract, which "plays both parts":
1. Implements a function which calls your nonReentrant-function
2. Implements a function which your nonReentrant-function calls back to

As I've explained above, it might be impossible if your nonReentrant-function is also onlyOwner, but in that case, you don't need to make it nonReentrant to begin with.

**Comment by Dkdaniz** [comment]
![Screen Shot 2022-03-03 at 21 53 22](https://user-images.githubusercontent.com/17903007/156678371-512b8eae-08a1-44e9-9e07-830364c247ca.png)

Hi guys, any can help me understand what is letter E in my covarage?

![Screen Shot 2022-03-03 at 22 01 46](https://user-images.githubusercontent.com/17903007/156679093-ec70d4aa-b490-40d1-ad9d-f05ddb227344.png)

only % Branch dont was 100%

**Comment by cgewecke** [comment]
@Dkdaniz This means the false case for the require statement has never been executed. 

To remove the `E`, you'll need to write a test where `_dataStorageInterface.root() == _msgSender()` and the method reverts.

**Comment by Dkdaniz** [comment]
Thanks for your answer. I will work this.

**Comment by Dkdaniz** [comment]
![Screen Shot 2022-03-03 at 23 56 23](https://user-images.githubusercontent.com/17903007/156690479-8551a046-e458-4cc6-ab67-6017b6e4573d.png)

Just dropping by to give my feedback that using hardhat and solidity-coverage there are no problems with the modifier, all the tests are being done correctly, as mentioned above, I thought I was doing the test coverage, but when I went to confront my tests, it really wasn't passing as I believed, so the way I did the tests caused a small bug, making my test show a false positive, I corrected the test and everything worked as expected.

**Comment by sanderpick** [comment]
I have a case here that I'm not sure how to test for: two modifiers, each is required by parent contracts, and both are only accessible under the same logic. tl;dr, I can only test for the first one.

<img width="390" alt="Screen Shot 2022-06-06 at 10 59 28 PM" src="https://user-images.githubusercontent.com/361000/172306602-746f68cc-d602-4334-89f1-14efe1afab99.png">

**Comment by cgewecke** [comment]
It's possible to exclude modifiers from coverage using the `modifierWhitelist` option.  Am generally sympathetic to barakman's analysis of things in the comment above. If you can't hit lines in your code with a test, something is wrong.
