### ISSUE TITLE
Uncovered lines counting lines that are covered 

### ISSUE THREAD

**Issue by fulldecent** [sc-forks/solidity-coverage#698]
I have a smart contract and testing setup.

With the command:

```sh
hardhat coverage --testfiles 'contracts/MY_CONTRACT.sol'
```

it is showing several lines under "Uncovered Lines".

However those lines are certainly covered. This is simple to check by putting a `require(false);`  next to any of the reported lines and seeing the tests fail which previously passed before the change.

Sorry to not have a minified test case yet I can share.

But I do have a workaround. Adding an event to the affected contract and putting a `emit` next to that affected line solves the problem.

Wanted to create this issue first because we have a workaround and that might be helpful for others.

---

Version: Hardhat 2.9.1

**Comment by cgewecke** [comment]
@fulldecent If you're able to share a snippet of the solidity code that would be helpful. Also, the version of solidity-coverage.

**Comment by fulldecent** [comment]
Here is an example showing the broken count and my workaround.

https://github.com/ghoul-sol/treasure-marketplace/pull/39

Sorry, don't have anything minified yet.

**Comment by cgewecke** [comment]
This comment says the missing lines were intermittent / you're no longer seeing this behavior? Is that correct? 

https://github.com/ghoul-sol/treasure-marketplace/pull/39#issuecomment-1063294763

**Comment by fulldecent** [comment]
In a separate branch I had made other changes that somehow fixed the problem.

But in this commit above it would consistently report uncovered lines unless I added the dummy lines around those lines.

**Comment by cgewecke** [comment]
Closing in lieu of reproducible example. Please just ping if you discover one.
