### ISSUE TITLE
Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon)

### ISSUE THREAD

**Issue by eerkaijun** [sc-forks/solidity-coverage#699]
I get the `Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon)` warning when I had solidity-coverage as a plugin in my Hardhat project. 

I tried adding `alloUnlimitedContractSize: true` in my network parameter in hardhat config, and also tried enabling optimisation for the compiler, however these don't work. Any ideas on how to solve this issue?

**Comment by NikolaiSch** [comment]
i think your problem may be in the fact that u said "alloUnlimitedContractSize" instead of "allowUnlimitedContractSize"

**Comment by cgewecke** [comment]
These are just warnings ... solidity-coverage injects code into the contracts to enable tracing and pushes contract sizes over the limit. 

If you'd like to silence these try using the 0.8.x beta which filters them from the logged output.
```
yarn add solidity-coverage@beta
```
