### ISSUE TITLE
Individual file coverage feature

### ISSUE THREAD

**Issue by swan-of-bodom** [sc-forks/solidity-coverage#705]
Hi, apologies for the stupid question... but is there any way to do an individual file coverage test with the **Hardhat plugin**? I have just started using this tool and I am playing around with the config file but I can't for the life of me figure out how to do this. I am trying to implement it in my work and it works really well when there is only 1 or 2 sol files:

![image](https://user-images.githubusercontent.com/97303883/161734491-8d7a41d6-14fb-471a-ac1b-e43ac91dbd1f.png)

But now that I have almost 20 sol files to compile, it gets quite hard to do individual testing:

![image](https://user-images.githubusercontent.com/97303883/161734813-1605d57e-b6b1-465a-8ddb-fd8a447aaffa.png)

![image](https://user-images.githubusercontent.com/97303883/161734983-1cad58b3-1533-40d0-bfaa-8819853bf1f4.png)

I would like to just isolate for example Erc20.sol and move forward with the rest. Is this possible?

Thank you for this amazing tool also, it has been very helpful!

Edit: typo

**Comment by cgewecke** [comment]
Thanks for the nice description here, sorry for the very belated response. Will track this feature request in #805
