### ISSUE TITLE
Error: Transaction gasPrice (1) is too low... when using `hardhat_mine`

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#707]
Reported by @pedroyan in https://github.com/sc-forks/solidity-coverage/issues/652#issuecomment-1089365208

Reproduction at: https://github.com/pedroyan/solidity-coverage-issue

**Example**
```js
// Advance block number in 1 week to end the voting
await hre.network.provider.send('hardhat_mine', ['0xB3CB'])
```

(A workaround is to specify the `berlin` fork when running coverage.)

**Comment by clemsos** [comment]
Hello, I am running into this issue but I can not specify the berlin hardfork as the code is also using  `hardhat_setNextBlockBaseFeePerGas` which requires EIP-1559. Any idea of a potential fix? Thanks !

**Comment by mikeshultz** [comment]
I've got some tests that use `hardhat_mine` to mine lots of blocks and adjust the timestamp to time travel into the future.  Using `evm_mine` is significantly slower (1 block and RPC call for every 1 second for days or weeks) and not really an ideal solution for me. 

Switching back to berlin also doesn't seem to be an option for me for reasons that weren't immediately obvious...

**Comment by cgewecke** [comment]
@mikeshultz If you just want to adjust the timestamp you can use [evm_increaseTime][1]

[1]: https://hardhat.org/hardhat-network/reference/#evm-increasetime

**Comment by mikeshultz** [comment]
> @mikeshultz If you just want to adjust the timestamp you can use [evm_increaseTime](https://hardhat.org/hardhat-network/reference/#evm-increasetime)

Forgot about that, will try it out.  Thanks for the tip.  :+1:

**Comment by sirpy** [comment]
> Hello, I am running into this issue but I can not specify the berlin hardfork as the code is also using `hardhat_setNextBlockBaseFeePerGas` which requires EIP-1559. Any idea of a potential fix? Thanks !

so actually your comment here gave me the idea of calling setNextBlock to revert any changes.
so i've simply  ` await ethers.provider.send("hardhat_setNextBlockBaseFeePerGas", ["0x0"]);` right after the call to hardhat_mine

**Comment by cgewecke** [comment]
Closing via #845 which adds a test for mining ~50k and sending a tx. Seems fine now...if anyone runs into this again please ping.
