### ISSUE TITLE
Out of gas error: when deploy the ContractFactory with Hardhat test.

### ISSUE THREAD

**Issue by jsdude0220** [sc-forks/solidity-coverage#709]
Hello, I am having issue - out of gas!
When deploy the contract on hardhat, `npx hardhat coverage` just returns out of gas error.
For example...
```
let contractFactory = new ContractFactory(mainContract.abi, mainContract.bytecode, owner);
let mainContract = await contractFactory.deploy(
    subContract1.address,
    subContract2.address,
    subContract3.address,
    subContract4.address,
    subContract5.address,
)
```
This code works fine with `npx hardhat test`
What is the main problem and how should solve this out of gas issue?
Or Are there any option to ignore gasLimit when deploy?

Thanks in advance.

**Comment by cgewecke** [comment]
Have you looked at the [Running out of gas][1] section of the FAQ? 

[1]: https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#notes-on-gas-distortion

**Comment by cgewecke** [comment]
Do you have a link to your project on Github or simple reproduction case? solidity-coverage sets the gas limits really high and it's unusual to run into this problem unless someone overwrites that logic somewhere in their code.

I can't debug given the code snippet you've provided unfortunately.

**Comment by jsdude0220** [comment]
Yes, sure.
I have invited you on that repository, so please check your email and accept the invite.
In glance, you can check the `test.js` script file in `scripts` folder.
There is waffle test scripts for testing and it works simply in npx hardhat test "test/test.js"
But when I try to check solidity coverage, it failed and returns gasLimit error.

Here is repository link.
https://github.com/jsdude0220/farm-contract

Thanks.

**Comment by cgewecke** [comment]
I think you really want to use the `hardhat-waffle` plugin which uses HardhatEVM as a client. If you follow the guidelines in this README everything should work. 

https://github.com/NomicFoundation/hardhat/tree/master/packages/hardhat-waffle#hardhat-waffle

**Comment by jsdude0220** [comment]
So I am using the ethereum-waffle, just not hardhat-waffle, so do you mean it works with hardhat-waffle?
I think hardhat-waffle is also using the ethereum-waffle as the based.
Can you please confirm if my understanding is correct?
Thanks in advance.

**Comment by cgewecke** [comment]
@jsdude0220 It's using it as a base but wires up the provider correctly.

**Comment by jsdude0220** [comment]
So I have one question.
Why it is not working on ethereum-waffle that I am using currently?
It is only working with hardhat-waffle.

**Comment by cgewecke** [comment]
`solidity-coverage` configures the hardhat provider. This is exposed by the waffle plugin via the function here:

https://github.com/NomicFoundation/hardhat/blob/ef14cb35114b3e6b28ed697fe74049c38695afb3/packages/hardhat-waffle/src/waffle-provider-adapter.ts#L36

This plugin requires access to that provider - the one injected into the hardhat environment. We set it with the correct gas values and hook into its VM to monitor the code execution path using low-level logic.  The provider exposed by the underlying package just won't work.
