### ISSUE TITLE
Can't Run With Separate Ganache

### ISSUE THREAD

**Issue by johnnyshankman** [sc-forks/solidity-coverage#710]
I already have ganache running on localhost:7545 using a specific seed phrase. Whenever I ask sol coverage to boot up using `--network=development` it tries to respin up 7545 and tells me it's already in use, instead of just using the ganache server already running there.

```
> truffle run coverage --network=development


> Using Truffle library from local node_modules.

Error: Port 7545 is already in use.
	Run: "lsof -i" to find the pid of the process using it.
	Run: "kill -9 <pid>" to kill it.
```

Is there a flag to tell coverage to not boot up a brand new ganache instance?

**Comment by johnnyshankman** [comment]
For now my best solution is to create a `.solcover.js` file and then fill it out like so
```
module.exports = {
  providerOptions: {
    "mnemonic": "..." // the mnemonic i'm using for my test server
  }
}
```

**Comment by cgewecke** [comment]
Yes, this is a basic design limitation of solidity-coverage. The tool needs to hook into ganache's vm in memory to trace code execution and can't do this with a separately launched instance.

**Comment by davidmurdoch** [comment]
@cgewecke Do you think it'd be valuable for Ganache to add in a way for solidity-coverage to hook into a remote instance?
