### ISSUE TITLE
No way to pass `--wallet.defaultBalance` to `providerOptions` from `.solcover.js`

### ISSUE THREAD

**Issue by johnnyshankman** [sc-forks/solidity-coverage#718]
I've tried all of the following permutations below and none of them cause the default balances to change in ganache core. My test `mnemonic` works just fine, insinuating that `namespace` is not being respected as in the [ganache docs seen here](https://github.com/trufflesuite/ganache#startup-options) and that something bizarre is going on.

```
module.exports = {
  providerOptions: {
    "mnemonic": "female labor pair federal fame unaware suffer village funny spice sniff ceiling",
    "wallet": {
      "defaultBalance": 4000000,
      "defaultBalanceEther": 4000000
    },
    "defaultBalance": 4000000,
    "defaultBalanceEther": 4000000,
  }
}
```

I even got desperate and tried this on the top level of `providerOptions` to no avail

```
...
    "--walet.defaultBalance": 4000000
...
```

No matter what, my tests are stuck with the 1000ETH default and fail by reporting things like
```
The upfront cost is: 700400001099511627775 and the sender's account only has: 9999999999999978573
```

I'm on the latest version of `solidity-coverage` and `truffle`.
```
"truffle": "^5.4.9",
"solidity-coverage": "^0.7.21"
```

**Comment by johnnyshankman** [comment]
Any help on this? Would be rad to to get those last few tests passing + covered.

**Comment by leiiiooo** [comment]
@davidmurdoch Do we have development plans for TruffleSite to provide unit test coverage statistics natively? It seems, currently, coverage is not easy for Truffle.

**Comment by riki-namu** [comment]
I recently had the same issue.
I'm using 
```
> truffle:           v5.5.15
> ganache-core:      v2.13.2
> solidity-coverage: v0.7.21
```

The comment below worked for me.
https://github.com/sc-forks/solidity-coverage/issues/503#issuecomment-676846529 
```
module.exports = {
  providerOptions: {
      default_balance_ether: 100000000,
  }
};
```

**Comment by cgewecke** [comment]
Closing this - ganache is deprecated - this plugin only works with hardhat EVM at the moment.
