### ISSUE TITLE
Readme Error: Ganache Provider Options

### ISSUE THREAD

**Issue by johnnyshankman** [sc-forks/solidity-coverage#719]
Currently links to:
https://github.com/trufflesuite/ganache#options

Should link to:
https://github.com/trufflesuite/ganache#startup-options

See:
https://github.com/sc-forks/solidity-coverage/blob/master/README.md#usage-notes

**Comment by cgewecke** [comment]
Closing this - ganache is deprecated - this plugin only works with hardhat EVM at the moment.
