### ISSUE TITLE
CompilerError: Stack too deep when compiling inline assembly

### ISSUE THREAD

**Issue by drop19** [sc-forks/solidity-coverage#721]
I get the following error during compilation:

```
CompilerError: Stack too deep when compiling inline assembly: Variable value0 is 1 slot(s) too deep inside the stack.
```

version: "0.7.14"

**Comment by cgewecke** [comment]
@drop19 There is section in the FAQ with workarounds for this problem here: 

https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-out-of-stack

**Comment by drop19** [comment]
Thanks. It does help. I thought `configureYulOptimizer` couldn't fix inline assembly
