### ISSUE TITLE
File level using for causes instrument error

### ISSUE THREAD

**Issue by ddnexus** [sc-forks/solidity-coverage#724]
```
using SomeLib for SomeType;
```
FIle level "using for" declaration is a feature in recent solidity, but an issue for solidity-coverage.

If you put it inside a library it will be ok for both, so it's a minor glitch with a possible workaround, but it's worth an issue.

**Comment by cgewecke** [comment]
Have added a test for this in #831 and it looks like this works now. This syntax might have been unsupported by `solidity-parser/parser` at some point. 

Closing, please just ping if anyone runs into this and can provide an example which fails.
