### ISSUE TITLE
Incorrect Results on Report

### ISSUE THREAD

**Issue by BravoNatalie** [sc-forks/solidity-coverage#726]
The first time I ran `npx hardhat coverage` it hadn't removed the files that should be ignored and I got this result, which is correct.

[![enter image description here][1]][1]

But after I added this to `.solcover.js`:
```js
module.exports = {
  skipFiles: ['ignore', "mock"]
};
```

I got this result, which doesn't make any sense, since all the tests passed.

[![enter image description here][2]][2]

What can this be?

  [1]: https://i.stack.imgur.com/DMAf2.png
  [2]: https://i.stack.imgur.com/efRQ3.png

**Comment by cgewecke** [comment]
It can also help to run `npx hardhat clean` before running the tool, especially after reconfiguring the coverage command.
