### ISSUE TITLE
`block.chainid` does not return correct chain ID in 0.8.0

### ISSUE THREAD

**Issue by cryptphil** [sc-forks/solidity-coverage#728]
I'm using solidity-coverage at version 0.8.0-beta.1 with ganache@7.2.0 (configured using `.solcover.js`) and truffle@5.5.18.

My contract performs a `block.chainid` call which has been added with Solidity 0.8.0 and which works perfectly fine when just running `truffle test`. However, when executing solidity-coverage this call returns 1 as the chain ID as opposed to the correct chain ID, 1337, that `web3.eth.getChainId()` returns.

**Comment by irzhywau** [comment]
Im not sure how but I seems having same strange thing with remix, even using `0.8.12`. `block.chainid` is always equal to `1` instead of `1337` for eg.

is there anyone for more insights?

**Comment by cgewecke** [comment]
solidity-coverage is no longer supporting ganache
