### ISSUE TITLE
Question: Parts of constructor are not covered

### ISSUE THREAD

**Issue by jacekv** [sc-forks/solidity-coverage#731]
Hey there :)

So I am currently using solidity-coverage 0.7.21 in my hardhat project and I am running currently into a problem, which I don't understand.
I have a contract, where the coverage reports tells me, that parts of the constructor are not covered:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/14347871/180293003-7f592960-36db-449f-933d-8b2ac022e6df.png">

If you look a little bit below, you see that the lines below are covered (at least that's my understanding of the number with the green background).

What am I missing here? I don't understand this behaviour.

**Comment by cgewecke** [comment]
@jacekv Sorry for the delay responding. Could you link to the repo that generated this report? 

Haven't seen this happen before ... idk what's going wrong.

**Comment by jacekv** [comment]
@cgewecke That's alright :) Thanks. I am somehow not able to reproduce the exact problem right now, yet I am still confused. 
I executed the coverage step in Github actions and here is the result: https://github.com/varkiwi/git3-contracts/runs/8044701537?check_suite_focus=true
Seems all good. But when I run it locally I get a different output:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/14347871/186992178-01b9f90c-b8ab-4339-b737-5db4e32c69f1.png">

Have you ever experience something like that?

**Comment by jacekv** [comment]
After running ‘hard hat clean’ I receive the same results as in the pipeline.

since I am currently not able to reproduce the error, I am going to close the issue as of now.
