### ISSUE TITLE
npx hardhat coverage --testfiles "test/gie-token-test.js" --network rinkeby

### ISSUE THREAD

**Issue by Bhupesh-98** [sc-forks/solidity-coverage#732]
I am trying to create coverage report of contracts I have created by running tests on rinkeby test network but facing problem stated below:

Command used -> npx hardhat coverage --testfiles "test/gie-token-test.js" --network rinkeby

The above command gives error : Error in plugin solidity-coverage: TypeError [ERR_INVALID_URL]: Invalid URL

_Originally posted by @Bhupesh-98 in https://github.com/sc-forks/solidity-coverage/issues/655#issuecomment-1193748618_

**Comment by cgewecke** [comment]
@clemsos Took a look at unlock and I see the error in your CI. 

Would it be possible debug this by changing your coverage command in package.json to ? 
```
hardhat coverage --network hardhat
```

This should coerce the task to use the built-in provider and help isolate the source of the problem (which might be in your network configuration logic).

**Comment by cgewecke** [comment]
@clemsos Hmm, strange. Will take a closer look....

**Comment by cgewecke** [comment]
@clemsos Apologies, could you also bump hardhat up to the latest version? (I think you have it at 2.15.0). 

There were changes at Hardhat and here to support an async provider creation pattern in #796  for 2.15.0 and maybe they had to patch something subsequently?

**Comment by clemsos** [comment]
Yes, this was a version issue with hardhat that has been fixed by upgrading it.. Thank you 🙏
