### ISSUE TITLE
[Hardhat] The matrix flag is not supported

### ISSUE THREAD

**Issue by zarifpour** [sc-forks/solidity-coverage#733]
The flag `--matrix` is not recognized in hardhat:

```
❯ npx hardhat coverage --matrix
Error HH303: Unrecognized task coverage --matrix
```

It is also not referenced  in `help`:

```
❯ npx hardhat help coverage
Hardhat version 2.9.2

Usage: hardhat [GLOBAL OPTIONS] coverage [--solcoverjs <STRING>] [--temp <STRING>] [--testfiles <STRING>]

OPTIONS:

  --solcoverjs  Relative path from working directory to config. Useful for monorepo packages that share settings. (default: "")
  --temp        Path to a disposable folder to store compilation artifacts in. Useful when your test setup scripts include hard-coded paths to a build directory. (default: "")
  --testfiles   Path (or glob) defining a subset of tests to run (default: "")

coverage: Generates a code coverage report for tests

For global options help run: hardhat help
```
---

https://github.com/sc-forks/solidity-coverage/blob/bc7d07623ec4bd71a2ce4c8ecb4a872af613c8ef/plugins/hardhat.plugin.js#L96-L102

https://github.com/sc-forks/solidity-coverage/blob/bc7d07623ec4bd71a2ce4c8ecb4a872af613c8ef/test/units/hardhat/flags.js#L176-L199

**Comment by cgewecke** [comment]
Hi @zarifpour, this feature is supported in the V8 `beta`. (This repo is in a slightly awkward state at the moment... apologies).

To get the version reflected in the master branch, run:
```
yarn add solidity-coverage@beta
```
