### ISSUE TITLE
Incompatible with solpp?

### ISSUE THREAD

**Issue by ddnexus** [sc-forks/solidity-coverage#735]
Not sure whether this is an issue that has some work around. The coverage is 0 on all contracts.

We need to use the [hardhat-solpp](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-solpp) plugin to inject addresses and other stuff at compilation.

The plugin configures [solpp preprocessor](https://github.com/merklejerk/solpp) so it processes the contracts sources in the `contracts` dir into the `cache/solpp-generated-contracts` and uses them when testing.

I suspect that running solpp with `solidity-coverage HH plugin` may remove the instrumentation solidity-coverage injects into the contracts (as reported in #715).

Is that a probable cause?

I guess that a possible workaround (that I don't know how to setup) would be making `solitidy-coverage` use the previously generated contracts in the `cache/solpp-generated-contracts` as the actual source (and disabling at the same time solpp).

Is there a way to tell `solitidy-coverage` to look into the generated dir for sources instead of in the `contracts` dir?

Thank you.

**Comment by ddnexus** [comment]
OK, so I tried my work around and it worked. Not sure whether this is the best solution, but it looks pretty clean to me.

```js
// hardhat.config.ts
{
...
    paths: {
        sources: (process.env["COVERAGE"] ? "./cache/solpp-generated-contracts" : "./contracts")
...
    solpp: {
        noPreprocessor: process.env["COVERAGE"] ? true : false
...
}
```

Then call the task with with `COVERAGE=true hardhat coverage`

**Comment by cgewecke** [comment]
Looks good to me! Thanks for the workaround.
