### ISSUE TITLE
the API is working but the coverage is always zero. Did I use it right?

### ISSUE THREAD

**Issue by k1nh00** [sc-forks/solidity-coverage#736]
hi, I am a user of solidity coverage API. I wrote a node file to collect the coverage of my tests with the methods provided in the API documentation. the code can run smoothly but no coverge is collected. Did I write a wrong logic?

![Js](https://user-images.githubusercontent.com/43675826/187031254-04f42c19-39a1-4828-ab4b-216dca723341.png)

I output the instrumented contract to another file. I started the server and make it serving for 7 seconds to run the tests(triggered by a child process). In the test JS file, the instrumented contract is compiled and the contract is deployed, two transactions are sent. see below:
![testJS](https://user-images.githubusercontent.com/43675826/187031398-fd776773-de86-4d66-8eb4-688d4b0536c2.png)

but the coverage is always zero. I am so confused. HELP ME WITH IT, PLZ. 
the result of code running:
![run Result](https://user-images.githubusercontent.com/43675826/187031481-1dc28d1b-2b4f-4850-8177-6251a2205aac.png)

**Comment by k1nh00** [comment]
The instrumented contract is compiled with optimizer off for sure, of course. And the client is a ganache-cli instance.

**Comment by cgewecke** [comment]
solidity-coverage is no longer supporting ganache-cli. A link to an example of a recent usage of the API can be found here:

https://github.com/sc-forks/solidity-coverage/issues/798#issuecomment-1617753176
