### ISSUE TITLE
missing `web3-utils`

### ISSUE THREAD

**Issue by naddison36** [sc-forks/solidity-coverage#742]
When I install `solidity-coverage` v0.8.0 with `Hardhat` v2.11.0, I get the following error
`Error: Cannot find module 'web3-utils'`  

I run coverage with
`node --max_old_space_size=6144 node_modules/.bin/hardhat coverage --testfiles 'test/**/*.spec.ts' --show-stack-traces --typecheck`

If I add `web3-utils` to my repository the coverage works.

**Comment by cgewecke** [comment]
@naddison36 Thanks for catching this, fixed in `0.8.1`.
