### ISSUE TITLE
bug report: unrecognized "inliner" key after upgrading package

### ISSUE THREAD

**Issue by gabririgo** [sc-forks/solidity-coverage#752]
- after upgrading project from hardhat v2.2.1 to v 2.11.2 and solidity-coverage from v.0.7.17 to 0.8.2 I receive the following error when running hardhat coverage:
`
Unknown key "inliner"
`
`
Unknown key "inliner"
`
`
CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.
`
The project compiled correctly before but needed the inliner option as would otherwise not compile.
The inliner option is set in the .solcover.js file among the `solcOptimizerDetails` and worked fine until this upgrade.

[Reference for replication](https://github.com/RigoBlock/v3-contracts/tree/build/upgrade-hardhat)

**Comment by gabririgo** [comment]
[this issue comment](https://github.com/NomicFoundation/hardhat/issues/3202#issuecomment-1254996423) helps setting up required environment constants

**Comment by BowTiedPickle** [comment]
Also getting this issue, with solidity-coverage version `0.7.22`.

**Comment by cgewecke** [comment]
Closing ... I think this resolved itself - seems to have affected multiple plugins including hardhat-deploy.
