### ISSUE TITLE
functions named 'global' cannot be instrumented

### ISSUE THREAD

**Issue by anonymoussprocket** [sc-forks/solidity-coverage#753]
The following contract fails `npx hardhat coverage` using:
- node 16.17.1
- hardhat 2.11.2
- solidity-coverage 0.8.2
- typechain 8.1.0
- typescript 4.8.3

compiled with solidity 0.8.17.

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.16;

contract Sample2 {
    function global() public returns (uint256) {
        return 1;
    }
}
```

Renaming the function to `any_other_name` allows the command to proceed to generate coverage. I get the following error:
```
Error in plugin solidity-coverage: RangeError: Could not instrument: Sample2.sol. (Please verify solc can compile this file without errors.) index parameter must be between >= 0 and <= number of children.
```

In a much larger project I have a library with a function named `global` that is used with `using ... for ...`. That fails as follows:

```
Error in plugin solidity-coverage: Error: Could not instrument: CONTRACT_NAME_REDACTED.sol. (Please verify solc can compile this file without errors.) The specified node does not exist
```

<img width="843" alt="Screen Shot 2022-09-24 at 00 51 19" src="https://user-images.githubusercontent.com/42718855/192080546-432dbc77-997c-443e-a627-2b846af46f4f.png">

**Comment by riordant** [comment]
Also same issue. In our case it is not having a function directly called 'global', but having 'global' as part of a function name, in any case format.

**Comment by PedroCailleret** [comment]
Same issue! 
![image](https://github.com/sc-forks/solidity-coverage/assets/84166519/5bff2dc3-ff03-4bc1-8698-47558a86a658)

**Comment by cgewecke** [comment]
I think this is fixed in more recent versions with an updated parser. Please ping if anyone continues to run into it
