### ISSUE TITLE
Code coverage issue.

### ISSUE THREAD

**Issue by badrik-pedalsup** [sc-forks/solidity-coverage#755]
My all test cases are passing but still, code coverage is 0.
I have written test cases using hardhat.

**Comment by SvineruS** [comment]
Had the same problem.

I had several versions of the compiler (0.4.24 and 0.8.17) and contracts with those versions.
I left only version 0.8.17, the coverage started working correctly.


But it's strange, I have another project with the same versions of solidity, but used a different hardhat environment (fork of solidity-coverage from august 2021; hardhat-deploy; without hardhat-toolbox) and everything works fine

**Comment by cgewecke** [comment]
The primary reason people are seeing 0% coverage is because viaIR is set to true. Tracking that in #715
