### ISSUE TITLE
AssertionError: Expected event "Event" to be emitted, but it wasn't

### ISSUE THREAD

**Issue by beauwilliams** [sc-forks/solidity-coverage#762]
I have a repository which will fail partially to run the coverage. However the normal `hardhat test` works fine. 

It is picking events up in one contract, but not the other, when the coverage is run, leading to the test to fail.

Is there some way to fix solidity coverage so the tests pass?

The event that is 'not emitted' even though it is is the `FooCalled` event

https://github.com/beauwilliams/Solidity-Call-Function-With-Fallback-Via-EncodeCall/blob/main/README.md

**Comment by cgewecke** [comment]
AFAIK this is not possible. The plugin does not interfere with event calling. If someone can provide a simple reproducible example am happy to look into though.
