### ISSUE TITLE
Missed package-lock.json in repo

### ISSUE THREAD

**Issue by quocle108** [sc-forks/solidity-coverage#765]
Pls add package-lock.json to your repo. I found some issues with the old version of solidity-coverage because of the mismatched versions between your package's dependencies.

This issue can reproduce at version "solidity-coverage": "^0.7.0.
If you install the following [repo](https://github.com/quocle108/erc20-testlib), it will work fines, But if you remove the package-lock.json and reinstall it, it will throw an error 
```
Error: Callback was already called.
    at /erc20-testlib/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:273"
```

I saw this issue also happens on other versions.

**Comment by cgewecke** [comment]
ganache-cli is no longer a dependency here, this should be resolved.
