### ISSUE TITLE
Add configures to exclude certain lines or functions in contracts

### ISSUE THREAD

**Issue by gusye1234** [sc-forks/solidity-coverage#767]
Hi, 
I'm wondering if `solidity-coverage` supports to exclude the code in solidity, like this [feature](https://coverage.readthedocs.io/en/latest/excluding.html#advanced-exclusion) supported in `coverage` for Python. So that I can do something like below:
```solidity
// @skip coverage
function _beforeAddEventMinter(uint256 eventId, address account)
        internal
        virtual
    {}
```
to skip the coverage test for function `_beforeAddEventMinter`.

I didn't found the answer on the docs of `solidity-coverage`

**Comment by dileepfrog** [comment]
This would be very useful - it would allow including defensive validations in contracts even if there are no known ways to break them

**Comment by luiztools** [comment]
It would be great, I'm struggling with this.

**Comment by cgewecke** [comment]
Will track this feature at #729
