### ISSUE TITLE
Only "--temp artifacts" flag seems to have the desired effect

### ISSUE THREAD

**Issue by jmendiola222** [sc-forks/solidity-coverage#771]
From solidity-coverage doc [here](https://github.com/sc-forks/solidity-coverage/blob/master/docs/advanced.md#setting-the-temporary-artifacts-directory):

> The temp command line option lets you to specify the name of a disposable folder to stage the compilation artifacts of instrumented contracts in before the tests are run.

But when trying any other folder name rather than "artifacts", it doesn't seem to work (delete it):

`hardhat coverage --temp artifacts` ----> Creates the folder, runs and then deletes it. ✅

`hardhat coverage --temp myartifacts` ----> Does not create *"myartifacts"* folder, but *"artifacts"* instead, runs and then it does not delete it. ❌

Couldn't fin anything in the doc pointing to this behavior, although some odd behavior around --temp flag is discussed in https://github.com/sc-forks/solidity-coverage/issues/573

**Comment by cgewecke** [comment]
For a while now, solidity-coverage has delegated management of the artifacts destination to Hardhat itself. The temp flag is a vestige of an earlier way stage in Hardhat's development. 

Am going to remove this is v0.9.0 - updating the roadmap in #825 to reflect that and closing here.
