### ISSUE TITLE
Coverage is %0 even tests are passed

### ISSUE THREAD

**Issue by yusufferdogan** [sc-forks/solidity-coverage#786]
version =>     "solidity-coverage": "^0.7.21", 
![image](https://user-images.githubusercontent.com/45846424/223745416-7aa25e16-37ab-4b0c-95b1-51737ee26c80.png)
![image](https://user-images.githubusercontent.com/45846424/223746698-def51747-dd4e-4f9b-80de-569a99459129.png)

My Github repo. It is up to date.
https://github.com/yusufferdogan/hardhat-foundry-template

**Comment by yusufferdogan** [comment]
@cgewecke @area

**Comment by PedroReyes** [comment]
Hello,

I am having the same problem. It seems the problem appears when `hardhat-foundry` is imported in `hardhat.config.ts`:

`import "@nomicfoundation/hardhat-foundry";`

In my case, besides the incorrect coverage report, it is likely impacting also a test that uses Axios for checking BNB/BUSD exchange rate.

Best regards,
Pedro Reyes.

**Comment by Whytecrowe** [comment]
I have the same problem if I call:
`tenderly.setup()` in my hardhat.config file

**Comment by hung-native** [comment]
same issue here. Only the interfaces `.sol` are showing 100% others 0%

**Comment by tmavroeid** [comment]
The above problem seems to appear when importing the `"@nomicfoundation/hardhat-foundry"`. So instead of importing it, you may use the proposed way to get the dependencies from the foundry remappings [here](https://book.getfoundry.sh/config/hardhat).

**Comment by dimacros** [comment]
I have the same problem, what is the reason?

**Comment by Lemmingkje** [comment]
I had a similar problem but it was resolved after doing a `hardhat clean`

**Comment by cgewecke** [comment]
Am closing here because there are a few reasons why this can happen...the primary one I see in the issues currently is when viaIR is turned on for the compiler. Tracking that in #715
