### ISSUE TITLE
CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.

### ISSUE THREAD

**Issue by sanchitdawarsd** [sc-forks/solidity-coverage#789]
CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.

**Comment by dulumao** [comment]
Same this bug.

**Comment by rya-sge** [comment]
See the following issue [https://github.com/ethereum/solidity/issues/11638](https://github.com/ethereum/solidity/issues/11638), you will find a list of possible solutions.

For me, the following fix has worked:
`solidity: {
    version: '0.8.17',
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
        details: {
          yul: true
        }
      },
      viaIR: false
    }
  }`

**Comment by bengyles** [comment]
> I think the problem comes from hardhat, instead of the coverage plugin
> 
> See the following issue [ethereum/solidity#11638](https://github.com/ethereum/solidity/issues/11638) & #760 you will find a list of possible solutions.
> 
> For me, the following fix has worked: `solidity: { version: '0.8.17', settings: { optimizer: { enabled: true, runs: 200, details: { yul: true } }, viaIR: false } }`

your fix seems to work for me, thanks!

**Comment by cgewecke** [comment]
Closing here - all stack too deep & viaIR discussion will continue at #715
