### ISSUE TITLE
skipFile for folder and within the config

### ISSUE THREAD

**Issue by mattjaf** [sc-forks/solidity-coverage#793]
is there a way to skip folders such as:
```js
},
    mocha: {
        timeout: 200000, // 200 seconds max for running tests
    },
    coverage: {
        skipFiles: [
            "contracts/drafts/**/*.sol", // Glob pattern to skip all .sol files in the folder
        ],
      },
}
```

for some reason it is not skipping even when i specify the path and/or file with `"solidity-coverage": "^0.7.13"`
I even tried with `"solidity-coverage": "^0.8.2"` which didn't seems to fix it either
```js
coverage: {
  skipFiles: [
    "contracts/drafts/ContractName.sol",
    "drafts/ContractName2.sol",
    "ContractName3.sol",
  ],
},
 ```
🤔 still instruments them for coverage
strange ---  I even tried after running `yarn hardhat clean`

I was able to get it skip by adding a `.solsover.js` within the project's directory with the following contents
```js
module.exports = {
    skipFiles: [
        "drafts/ContractName.sol",
        "drafts/ContractName2.sol",
      ]
  };
  ```

**Comment by gyengus** [comment]
I have the same issue. `skipFiles` doesn't work for me too.
My `.solcover.js` file:
```
module.exports = {
    skipFiles: ['contracts/Token.sol']
};
```
I tried it with `npx hardhat coverage --solcoverjs ./.solcover.js` and without `--solcoverjs` argument. Unfortunetely, didn't work.

**Comment by cgewecke** [comment]
This works if you follow the instructions in the README. Closing
