### ISSUE TITLE
problem: solidity-coverage and hardhat node --fork BSC mainnet

### ISSUE THREAD

**Issue by SolDev75** [sc-forks/solidity-coverage#797]
Hey all,
I have the following problem:
1) I started node forking BSC mainnet to test my smart contract (contract contains specific functions used in BSC main net, e.g. creating an LP on pancakeswap using IUniswapV2Factory).
**npx hardhat node --fork https://bsc-dataseed.binance.org/**
2) I deployed my smart contract on it:
**npx hardhat run --network localhost scripts/deploy.js**
3) I created some tests and can run them successfully:
**npx hardhat test --network localhost test/mytest.js**
Everyting is fine.

Now I would like to check the code coverage with “solidity-coverage” plugin.
My node with BSC fork is running, otherwise my tests cannot be executed.
In hardhat.config.js:
`  
networks: {
    localhost: {
      url: "http://127.0.0.1:8545",
    },
    bscmainnet: {
      url: "https://bsc-dataseed.binance.org/",
      chainId: 56,
    },
`

If I call “**npx hardhat coverage --network localhost**”, I get the error:
Error in plugin solidity-coverage: Error: Port 8545 is already in use.
        Run: "lsof -i" to find the pid of the process using it.
        Run: "kill -9 <pid>" to kill it

If I call “**npx hardhat coverage**”, all of my tests are failing, because a new local node is starting. But my tests can only run on forked BSC node.

How can I solve the problem?
Thanks a lot in advance!
I tried to find a solution on the internet, but didn't find it in the last days...

**Comment by cgewecke** [comment]
The coverage tool will not work with an independently running node. You can configure the in-memory HardhatEVM for forking following the example in the Hardhat docs here (below the CLI example): 

https://hardhat.org/hardhat-network/docs/guides/forking-other-networks#forking-from-mainnet
