### ISSUE TITLE
No release notes for 0.8.3

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#800]
Most recent release notes are for 0.8.2: https://github.com/sc-forks/solidity-coverage/releases.

Would it be possible to update this page for 0.8.3?

Thanks

**Comment by cgewecke** [comment]
Hi @barakman, sorry about that. I've just published 0.8.4 and the changes from 0.8.3 are included in its release notes. 

0.8.3 contained support for changes to the internal provider API at Hardhat. 
0.8.4 updates the solidity parser to support more recent Solidity.
