### ISSUE TITLE
Cannot use with `hardhat_impersonateAccount`

### ISSUE THREAD

**Issue by DefiCake** [sc-forks/solidity-coverage#804]
This plugin is incompatible with the impersonate feature of hardhat.

`hardhat_impersonateAccount` allows to transact from any given address, be it smart contract or EOA, even if you don't have the private key for that address. This is useful to simulate transactions from rich addresses or from smart contracts without having to implement mocks or complicated testing boilerplate.

Whenever a test impersonates an account and you try to send transactions from that account, coverage will fail with error:
`InvalidInputError: unknown account <ADDRESS OF THE ACCOUNT>`

I 'm leaving a snippet that can help with reproduction:

```ts
export async function impersonateAddress(hre: HardhatRuntimeEnvironment, address: string) {
  console.log('IMPERSONATE', address);
  await hre.network.provider.request({
    method: 'hardhat_impersonateAccount',
    params: [address],
  });

  const balance = await hre.ethers.provider.getBalance(address);

  if (balance.eq(0)) {
    await hre.network.provider.send('hardhat_setBalance', [address, parseEther('1000').toHexString()]);
  }

  return hre.ethers.getSigner(address);
}
```

**Comment by cgewecke** [comment]
Are you trying to use an independent HH node in your tests? That might be the problem. Coverage launches the node itself after hooking into its internals to track the execution trace.

**Comment by cgewecke** [comment]
Closing: stale.
