### ISSUE TITLE
Get different hashes between `npx hardhat test` and `npx hardhat coverage`

### ISSUE THREAD

**Issue by hash0725** [sc-forks/solidity-coverage#809]
Can anyone help with the reason why getInitHash() function returns different hashes between running `npx hardhat coverage` and `npx hardhat test`.
I made a UPair contract which inherits UniswapV2Pair and tried to get an init code hash result of the UPair contract.

```
pragma solidity 0.5.16;
import "@uniswap/v2-core/contracts/UniswapV2Pair.sol";
contract UPair is UniswapV2Pair {
}
```

```
// SPDX-License-Identifier: MIT
pragma solidity 0.5.16;
import "./UPair.sol";
contract CalHash {
    function getInitHash() public pure returns(bytes32){
        bytes memory bytecode = type(UPair).creationCode;
        return keccak256(abi.encodePacked(bytecode));
    }
}
```
In the test file, it returns the hash value in the console.
```
const calHash = await ethers.deployContract("CalHash");
const hash = await calHash.getInitHash();
console.log(hash);
```

When run `npx hardhat test`, it results `0x877a3ef9780a1f2a67d1b2ce7397aa3645136ba080c4101811beb6509b89aff1`.
But when run `npx hardhat coverage`, it results `0xf943e4bf157c549da86a4c42fa3fc7acb248205659d5b5eb6584bf15a24c5bb2`.
What is the reason why they results different hashes even though the same code?

**Comment by cgewecke** [comment]
(Sorry for the delay responding). Solidity-coverage injects additional solidity statements into the contracts to track the code execution path. The bytecode won't be the same. 

You can skip tests that fail under coverage using the technique [described here](https://github.com/sc-forks/solidity-coverage/blob/master/docs/advanced.md#skipping-tests)
