### ISSUE TITLE
Consider using caret range for dependencies

### ISSUE THREAD

**Issue by frangio** [sc-forks/solidity-coverage#813]
To reduce maintenance burden for this project (and improve dependency management for users of the package) it would be ideal to declare dependencies using caret ranges.

https://github.com/sc-forks/solidity-coverage/blob/fb5fd6e1d4455eb662eb1dc6f0e1cd79e4fbd7d5/package.json#L39

Mocha would ideally be declared as `"^10.2.0"`.

Is there a particular reason why the version is pinned?

**Comment by cgewecke** [comment]
> Is there a particular reason why the version is pinned?

I don't think so - thanks for catching. #814 should fix this in the next patch. (Doing a little bit more work here this week and will republish when that's done). 

@ChristopherDedominici Just to double-check did you have preference for pinning in #810?

**Comment by frangio** [comment]
My guess is @ChristopherDedominici just followed the previous convention:

![image](https://github.com/sc-forks/solidity-coverage/assets/481465/cc961092-4b64-4a4d-9418-438f20c702f2)

**Comment by cgewecke** [comment]
Unfortunately he can't do that here - it's a minefield.
