### ISSUE TITLE
uncovered else statements

### ISSUE THREAD

**Issue by msantamaria86** [sc-forks/solidity-coverage#820]
I have this kind of logic in multiple locations:

```
 function checkSubmissionStatus(uint256 _submissionId) public view returns (Review memory) {
        Submission memory submission = submissions[_submissionId];
        if (submission.status != 0) {
            for (uint256 i = 0; i < reviewCount; i++) {
                if (reviews[i].submissionId == _submissionId) {
                    return reviews[i];
                }
            }
        }
        return Review(_submissionId, address(0), "", false);
    }
```

since the internal "if" doesn't have an "else" statement the branch will be marked as incomplete. Is there a way to disable "else" statements checks when they are not present?
Creating a redundant else block just for the sake of coverage doesn't look like the best option.

**Comment by cgewecke** [comment]
@msantamaria86 Apologies for the late response and forgive me if I am misunderstanding this but I think your tests may be missing a case. 

For this loop, do you test where there are multiple reviews and the loop runs for more than a single iteration? 
```solidity
for (uint256 i = 0; i < reviewCount; i++) {
  if (reviews[i].submissionId == _submissionId) {
    return reviews[i];
  }
}
```

I realize the code is self-evidently correct but having tests for all assumptions no matter how idiotic is sometimes helpful, especially when refactoring things. 

Closing for now ... if you *do* have this test, it's a bug. Please ping I will reopen. 

cf: #190
