### ISSUE TITLE
Donating Funds to Solidity-coverage

### ISSUE THREAD

**Issue by Lfada** [sc-forks/solidity-coverage#826]
Hi Solidity-Coverage maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

[OpenZeppelin](https://www.openzeppelin.com/) has been using https://github.com/sc-forks/solidity-coverage. It's one of their most critical dependencies!

OpenZeppelin core contributors appreciate your work and want to ensure you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/)

Who can I talk to about it?

cc: @cag and @cgewecke (yes, two of the projects you are a top maintainer are getting funded)

**Comment by cgewecke** [comment]
@Lfada Thanks! That's very kind of them. I'm the principle maintainer here. You can email me at christophergewecke@gmail.com

**Comment by cgewecke** [comment]
@Lfada I was able to claim everything through your wonderful dAPP - thanks so much for this. Thank you Zeppelin as well.
