### ISSUE TITLE
Tracking Issue: using viaIR in versions >= 0.8.7

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#861]
Problems with `viaIR` resulting in 0% coverage should be resolved by v0.8.7. Release notes with advice about upgrading are [here][2]

There is a working example of the patch in this E2E test PR against the [1inch/solidity-utils][1] repo.

If you're still experiencing problems with this please report them here and
+ provide a link or invitation to your repo **OR**
+ provide a minimal reproduction case

[1]: https://github.com/cgewecke/solidity-utils/pull/1/files
[2]: https://github.com/sc-forks/solidity-coverage/releases/tag/v0.8.7

**Comment by jd1900** [comment]
I'm unfortunately having the same issues as described here:
https://github.com/sc-forks/solidity-coverage/issues/853#issuecomment-1936681415

**Comment by cgewecke** [comment]
@jd1900 Can you provide a way to reproduce this? Or invite me to the github repo where you're experiencing the problem so I can debug it?

**Comment by jd1900** [comment]
> @jd1900 Can you provide a way to reproduce this? Or invite me to the github repo where you're experiencing the problem so I can debug it?

I can't send you the whole repo.
Is it OK to share with you a solidity file that may cause the issue by itself?

**Comment by cgewecke** [comment]
@jd1900 Could you please upload it to github in a private repository and invite me to the repo through the github UI?

**Comment by cgewecke** [comment]
#870 is reporting some missing line coverage. The instrumentation disappears in two cases:
```solidity
uint24 quantity = _cancelOrdersSide(_orderIds[i], price, bidsAtPrice[tokenId][price], bids[tokenId]);
brushFromUs += quantity * price;   // <--- not covered
```

```solidity
for (uint i = _index; i < _segments.length.sub(1); ++i) {
    _segments[i] = _segments[i.inc()]; // <--- not covered
}
```
Compiling with 0.8.24

**Comment by cgewecke** [comment]
Closing b/c this seems like it's resolved now. Will re-open if there are new reports of issues.
