### ISSUE TITLE
Coverage missing when using solc v0.4.x

### ISSUE THREAD

**Issue by AntonGulak** [sc-forks/solidity-coverage#876]
hi, "solidity-coverage": "^0.8.11", + "hardhat": "^2.22.1", does not work with compiler version 4.21 (says code coverage is 0%)

**Comment by cgewecke** [comment]
@AntonGulak Thanks for reporting. (Have edited your issue title to reflect the underlying problem. A patch is in progress via  #877).

**Comment by cgewecke** [comment]
Published in v0.8.12
