### ISSUE TITLE
EISDIR error when `paths.sources`  directory name contains `.`

### ISSUE THREAD

**Issue by AntonGulak** [sc-forks/solidity-coverage#879]
Solidity Coverage crashes with the error "Error in plugin solidity-coverage: Error: EISDIR: illegal operation on a directory, read"

For example, if the contracts are in the ./Solidity-4.21 directory (crashes because of a dot in the folder name)

paths: {
     sources: `./Solidity-4.21`,
     tests: "./test",
     cache: "./cache",
     artifacts: "./artifacts",
   },

```
     HardhatPluginError: Error: EISDIR: illegal operation on a directory, read
     at SimpleTaskDefinition.action 
     solidity-coverage\plugins\hardhat.plugin.js:269:35

     at async Environment._runTaskDefinition 
     hardhat\src\internal\core\runtime-environment.ts:359:14

    at async Environment.ru
    hardhat\src\internal\core\runtime-environment.ts:192:14

    at async main
    hardhat\src\internal\cli\cli.ts:323:7

```
package versions:
"hardhat": "^2.22.1",
 "solidity-coverage": "github:sc-forks/solidity-coverage#master"

**Comment by cgewecke** [comment]
Published in v0.8.12
