### ISSUE TITLE
Comment immediately following function's opening brace breaks instrumentation

### ISSUE THREAD

**Issue by jeromerousselot** [sc-forks/solidity-coverage#88]
Hi,

using solidity-coverage 0.2.11 I get the following error on my contract:

```
/home/jerome/src/eth/contracts/coverageEnv/contracts/HeroCoin.sol:449:24: ParserError: Expected primary expression.
    returns (uint256) {/__FunctionCoverageHeroCoin('/home/jerome/src/eth/contracts/contracts/HeroCoin.sol',23);
                       ^
Compiliation failed. See above.
Cleaning up...

        There was an error generating coverage. Possible reasons include:
        1. Another application is using port 8555
        2. Truffle crashed because your tests errored

      Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
```

My truffle unit tests compile and pass.

Environment:
solcover 0.2.1
solc 0.4.11
ethereumjs-testrpc 4.0.1
truffle 3.4.5

**Comment by area** [comment]
You might have got lucky here without providing further context. Do you happen to have something like:

```
returns (uint256) {//This is a comment on the function
```

**Comment by jeromerousselot** [comment]
You are right! I added a space and it passes.

I now hit a solidity bug about calling twice the same modifier (with two different values).
Should be fixed in 0.4.15 I think, and doesnt exist in 0.4.11. 
solidity-coverage currently depends on 0.4.13.

https://github.com/ethereum/solidity/issues/2621

```
,/home/jerome/src/eth/contracts/coverageEnv/contracts/HeroCoin.sol:356:5: DeclarationError: Modifier already used for this function.
    updateAccount(_to) //update receivers rake before transfer as well, to avoid over-attributing rake
    ^----------------^
,/home/jerome/src/eth/contracts/coverageEnv/contracts/HeroCoin.sol:372:5: DeclarationError: Modifier already used for this function.
    updateAccount(_to) //update receivers rake before transfer as well, to avoid over-attributing rake

**Comment by area** [comment]
That's only a dev dependency, needed for running our tests. During the tests of your project, your contracts should still be compiled by truffle, so it's not a solidity-coverage issue.

**Comment by jeromerousselot** [comment]
I agree, ultimately I think it is a package management issue.
I have a globally installed truffle using globally installed solc 0.4.11 which compiles my contracts.
Locally I have another truffle and solidity-coverage. When running solidity-coverage I believe it uses solc 0.4.13.
I'll try again when truffle uses latest solc.
Thanks!

**Comment by area** [comment]
Reopening issue because the interaction with comments is a legitimate bug for us to fix.
