### ISSUE TITLE
Compilation fails when return type is a function

### ISSUE THREAD

**Issue by thedarkjester** [sc-forks/solidity-coverage#888]
When compiling a function that has a return type of a function (using something like a strategy to determine function at execution time) the compilation fails with a parse error.

Something similar to:
```
ParserError: Expected ',' but got ';'
   --> contracts/DynamicFunctionHelper.sol:268:32:
    |
268 | (abi.encode(0xe4534e4205b06427);  /* statement */ 
```

The function looks like so:
```
function getTradeStatusFunction(
    TradeType _tradeType
  ) internal pure returns (function(address, uint256, address) view returns (bool, bool)) {
 //  
}
```

**Comment by thedarkjester** [comment]
@cgewecke it turns out that it was my issue, so I am closing this, but for context, using the provided example I was doing:
```
(bool exampleVal1, bool exampleVal2) = (getTradeStatusFunction(TradeType.ExampleValue))(params here);
```

The issue was the extra brackets. The plugin works fine with:

```
(bool exampleVal1, bool exampleVal2) = getTradeStatusFunction(TradeType.ExampleValue)(params here);
```

**Comment by cgewecke** [comment]
@thedarkjester Ah! Thanks so much for the additional repro...will take another look.
