### ISSUE TITLE
Test fail with Invalid data returned on OP mainnet fork, hardhat-ignition and hardhat-viem

### ISSUE THREAD

**Issue by Chomtana** [sc-forks/solidity-coverage#891]
All testcases are failed with `FarcasterResolverModule#registerSchema/1: Simulating the transaction failed with error: Invalid data returned` but succeed on `npx hardhat test`

## Source Code

* Hardhat Iginition module: https://github.com/Farcaster-Attestation/farcaster-resolver/blob/coverage-bug/ignition/modules/FarcasterResolver.ts
* Hardhat test 1: https://github.com/Farcaster-Attestation/farcaster-resolver/blob/coverage-bug/test/FarcasterPublicKeyVerifier.ts
* Hardhat test 2: https://github.com/Farcaster-Attestation/farcaster-resolver/blob/coverage-bug/test/FarcasterWalletVerifier.ts

## Coverage

![image](https://github.com/user-attachments/assets/7db50817-2bac-41da-97b9-009d6812972b)

## npx hardhat test

![image](https://github.com/user-attachments/assets/72af6600-66ea-4e64-a11b-5f371d72e624)

**Comment by cgewecke** [comment]
@Chomtana Apologies for the delay fixing this. It should be patched via #893 which is published in the latest release (0.8.13)

Ran your farcaster repo locally with the changes and saw the results below, but just lmk if you're continuing to see problems and will re-open...

![Screen Shot 2024-08-28 at 9 56 40 PM](https://github.com/user-attachments/assets/ba8ea8f4-0e61-49e8-b1c5-99b3fc7dc826)
