### ISSUE TITLE
Truffle test to begin auto-launching an in-memory testrpc.

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#90]
[This](https://github.com/trufflesuite/truffle/issues/490) development [here](https://github.com/trufflesuite/truffle-core/pull/38/commits/d88c075b7b3c8d9f7e39be43b4e27a1ce2cea424) might be a breaking change? At the moment if we don't detect a coverage network we stub in a development network with high deployment gas. Not sure if this will affect us or not but worth checking when they publish.

**Comment by area** [comment]
I don't think this should affect us, but yeah, good spot and worth keeping in mind until we can confirm one way or the other.

**Comment by cgewecke** [comment]
From the Truffle 4.0 Beta release notes re: auto-launch:
> For all you Truffle veterans though, there's a catch: You need to remove your development network from your truffle.js config file if you'd like to use this feature. We did this so upgrading to Truffle 4.0 doesn't completely blow away your testing process. You're welcome.

Thanks! So we're safe with the default run because we use development, and we're safe with a coverage network since we use the `--network` flag. We're also safe on `8555`, they'll be auto-launching on `9545`. 

Closing.
