### ISSUE TITLE
Support alternative truffle config filename

### ISSUE THREAD

**Issue by frangio** [sc-forks/solidity-coverage#93]
solidity-coverage assumes the Truffle config is at `truffle.js`. There is an alternative filename `truffle-config.js` as seen in [the documentation](http://truffleframework.com/docs/advanced/configuration#resolving-naming-conflicts-on-windows).

**Comment by cgewecke** [comment]
@frangio Thanks! This should be fixed and published with `0.2.2`. 
Please re-open if it doesn't work. 😄
